<?php
/**
 * TotpProvider — RFC 6238 TOTP second-factor provider for site users.
 *
 * Algorithm:
 *   - SHA1 / 6 digits / 30-second period (matches major authenticator apps).
 *   - ±2 step (±60s) skew window to tolerate clock drift (GH #215).
 *   - Single-use step burn: the accepted counter step is stored in user-meta
 *     so the same code cannot be replayed within its validity window, even
 *     across the wider skew window; the enrollment activation step is burned
 *     too, so the setup-confirm code cannot be reused as the first login.
 *   - TOTP secret (160-bit, base32-encoded) stored encrypted in user-meta via
 *     the agent's AgeCrypto (AgeIdentity keypair). Decrypt failure = provider
 *     reports "configured but unusable" (never silent bypass).
 *
 * QR enrolment: the provider can generate an otpauth:// URI for registration.
 * The interstitial module handles rendering the URI to a QR code.
 *
 * Clean-room implementation: all HOTP/TOTP math is in this file.
 *
 * @package WPMgr\Agent\Security
 */

declare(strict_types=1);

namespace WPMgr\Agent\Security;

use WPMgr\Agent\Support\AgeIdentity;

/**
 * RFC 6238 TOTP provider.
 */
final class TotpProvider implements SiteTwoFactorProvider
{
    /** User-meta key for the encrypted TOTP secret (age ciphertext, base64). */
    public const META_SECRET = 'wpmgr_2fa_totp_secret';

    /**
     * User-meta key for the PENDING (not-yet-confirmed) TOTP secret during enrollment.
     *
     * The pending secret is stored encrypted at rest exactly like the active secret.
     * It is ONLY promoted to META_SECRET once the user proves a valid code (the
     * activation step). An abandoned enrollment never writes META_SECRET.
     */
    public const META_PENDING_SECRET = 'wpmgr_2fa_totp_secret_pending';

    /** User-meta key for the last accepted counter step (replay burn). */
    public const META_LAST_USED = 'wpmgr_2fa_totp_last_used';

    /** Base32 alphabet (RFC 4648). */
    private const BASE32_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

    /** TOTP period in seconds. */
    private const PERIOD = 30;

    /** Code length in digits. */
    private const DIGITS = 6;

    /**
     * Acceptable window (±N steps on either side of current), i.e. ±(N*PERIOD)
     * seconds of clock-drift tolerance. Widened from 1 to 2 (±60s) to absorb
     * client clock drift (GH #215); the single-use step burn below still
     * prevents replay across the wider window — a step is only ever accepted
     * once regardless of how many steps the window spans.
     */
    private const WINDOW = 2;

    private AgeIdentity $ageIdentity;

    /**
     * @param AgeIdentity $ageIdentity Used to encrypt/decrypt the TOTP secret.
     */
    public function __construct(AgeIdentity $ageIdentity)
    {
        $this->ageIdentity = $ageIdentity;
    }

    /** {@inheritDoc} */
    public function key(): string
    {
        return 'totp';
    }

    /** {@inheritDoc} */
    public function label(): string
    {
        return 'Authenticator App (TOTP)';
    }

    /** {@inheritDoc} */
    public function isConfiguredFor(\WP_User $user): bool
    {
        if (!function_exists('get_user_meta')) {
            return false;
        }
        $enc = (string) get_user_meta((int) $user->ID, self::META_SECRET, true);
        return $enc !== '';
    }

    /** {@inheritDoc} — TOTP has no pre-render side-effect. */
    public function preRender(\WP_User $user): void
    {
        // No-op: TOTP codes are generated by the authenticator app.
    }

    /** {@inheritDoc} */
    public function renderForm(\WP_User $user): string
    {
        $label = esc_html($this->label());
        $field = esc_attr('wpmgr_totp_code');
        $placeholder = esc_attr('6-digit code');
        return '<p><label for="' . $field . '">'
            . $label
            . '</label>'
            . '<br><input type="text" id="' . $field . '" name="' . $field . '" '
            . 'autocomplete="one-time-code" inputmode="numeric" pattern="[0-9]{6}" '
            . 'maxlength="6" placeholder="' . $placeholder . '" required autofocus></p>';
    }

    /** {@inheritDoc} */
    public function validate(\WP_User $user, array $input): bool
    {
        $userId = (int) $user->ID;
        $code   = isset($input['wpmgr_totp_code']) ? preg_replace('/\D/', '', $input['wpmgr_totp_code']) : '';
        if (!is_string($code) || strlen($code) !== self::DIGITS) {
            return false;
        }

        $secret = $this->loadSecret($user);
        if ($secret === '') {
            return false;
        }

        $now  = (int) (time() / self::PERIOD);
        $last = (int) get_user_meta($userId, self::META_LAST_USED, true);

        for ($offset = -self::WINDOW; $offset <= self::WINDOW; $offset++) {
            $counter = $now + $offset;
            // Replay burn: skip already-used steps.
            if ($counter <= $last) {
                continue;
            }
            if (hash_equals($this->generateCode($secret, $counter), $code)) {
                // Burn this step to prevent replay.
                update_user_meta($userId, self::META_LAST_USED, $counter);
                return true;
            }
        }

        return false;
    }

    // -------------------------------------------------------------------------
    // Enrollment helpers (called by the interstitial during setup)
    // -------------------------------------------------------------------------

    /**
     * Generate a new TOTP secret, encrypt it, and store it as PENDING (not active).
     *
     * The returned secret is shown to the user to scan into their authenticator app.
     * The secret is stored in META_PENDING_SECRET (NOT META_SECRET). It is only
     * promoted to the active META_SECRET when the user validates a correct code via
     * activatePendingSecret(). An abandoned setup never activates the secret.
     *
     * The pending secret is age-encrypted at rest, identical to the active secret.
     *
     * @param \WP_User $user
     * @return string Raw base32 secret (display/QR use only; NOT stored in plaintext).
     */
    public function generateAndStorePending(\WP_User $user): string
    {
        // 20 bytes = 160-bit secret.
        $rawBytes = random_bytes(20);
        $secret   = self::base32Encode($rawBytes);

        $this->storeSecretToMeta($user, $secret, self::META_PENDING_SECRET);
        return $secret;
    }

    /**
     * Validate a TOTP code against the PENDING secret and, on success, promote it
     * to the active secret (META_SECRET). Clears the pending meta on either outcome
     * to prevent re-use of the pending value.
     *
     * Returns true when the code is valid and activation succeeded.
     * Returns false when the code is invalid; the pending secret remains available
     * for a retry (caller may re-present the same QR) — the pending meta is NOT
     * cleared on failure so the user can re-try without re-generating the QR.
     *
     * Attempt limiting is enforced at the interstitial session layer (not here).
     *
     * @param \WP_User $user
     * @param string   $code  6-digit code submitted by the user.
     * @return bool
     */
    public function activatePendingSecret(\WP_User $user, string $code): bool
    {
        $secret = $this->loadSecretFromMeta($user, self::META_PENDING_SECRET);
        if ($secret === '') {
            return false;
        }

        $code = preg_replace('/\D/', '', $code);
        if (!is_string($code) || strlen($code) !== self::DIGITS) {
            return false;
        }

        $now  = (int) (time() / self::PERIOD);

        for ($offset = -self::WINDOW; $offset <= self::WINDOW; $offset++) {
            $counter = $now + $offset;
            if (hash_equals($this->generateCode($secret, $counter), $code)) {
                // Code valid: promote pending → active.
                $this->storeSecretToMeta($user, $secret, self::META_SECRET);
                // Burn the activation step so the same confirm code cannot be
                // replayed as the very first login validate() call (the
                // activation step was previously never recorded in
                // META_LAST_USED, leaving a one-time replay window).
                update_user_meta((int) $user->ID, self::META_LAST_USED, $counter);
                // Clear pending (it is now active).
                if (function_exists('delete_user_meta')) {
                    delete_user_meta((int) $user->ID, self::META_PENDING_SECRET);
                }
                return true;
            }
        }

        return false;
    }

    /**
     * Clear the pending secret (called when a setup flow is abandoned or re-started).
     *
     * @param \WP_User $user
     * @return void
     */
    public function clearPendingSecret(\WP_User $user): void
    {
        if (function_exists('delete_user_meta')) {
            delete_user_meta((int) $user->ID, self::META_PENDING_SECRET);
        }
    }

    /**
     * Generate a new TOTP secret, encrypt it, and store it in user-meta AS ACTIVE.
     *
     * @deprecated  Use generateAndStorePending() + activatePendingSecret() for the
     *              enrollment flow so the secret is only activated after proof-of-code.
     *              This method writes directly to the active meta and is retained
     *              for backward-compat (e.g. operator CLI reset flows).
     *
     * @param \WP_User $user
     * @return string Raw base32 secret (display/QR use only).
     */
    public function generateAndStore(\WP_User $user): string
    {
        // 20 bytes = 160-bit secret.
        $rawBytes = random_bytes(20);
        $secret   = self::base32Encode($rawBytes);

        $this->storeSecretToMeta($user, $secret, self::META_SECRET);
        return $secret;
    }

    /**
     * Build an otpauth:// URI for QR generation.
     *
     * @param \WP_User $user
     * @param string   $secret Raw base32 secret.
     * @param string   $issuer Human-readable issuer name (site URL).
     * @return string
     */
    public function buildOtpauthUri(\WP_User $user, string $secret, string $issuer): string
    {
        $label = rawurlencode($issuer . ':' . $user->user_login);
        return 'otpauth://totp/'
            . $label
            . '?secret=' . rawurlencode($secret)
            . '&issuer=' . rawurlencode($issuer)
            . '&algorithm=SHA1&digits=' . self::DIGITS . '&period=' . self::PERIOD;
    }

    /**
     * Delete the stored secret (used when operator clears 2FA for a user).
     *
     * @param \WP_User $user
     * @return void
     */
    public function clearSecret(\WP_User $user): void
    {
        if (function_exists('delete_user_meta')) {
            delete_user_meta((int) $user->ID, self::META_SECRET);
            delete_user_meta((int) $user->ID, self::META_LAST_USED);
        }
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    /**
     * Load and decrypt the active TOTP secret. Returns '' on any failure
     * (the "configured-but-unusable" state described in §4 of the design doc).
     *
     * @param \WP_User $user
     * @return string Raw base32 secret or ''.
     */
    private function loadSecret(\WP_User $user): string
    {
        return $this->loadSecretFromMeta($user, self::META_SECRET);
    }

    /**
     * Load and decrypt a TOTP secret from a specific meta key.
     * Returns '' on any failure.
     *
     * @param \WP_User $user
     * @param string   $metaKey  META_SECRET or META_PENDING_SECRET.
     * @return string Raw base32 secret or ''.
     */
    private function loadSecretFromMeta(\WP_User $user, string $metaKey): string
    {
        if (!function_exists('get_user_meta')) {
            return '';
        }
        $enc = (string) get_user_meta((int) $user->ID, $metaKey, true);
        if ($enc === '') {
            return '';
        }
        try {
            $ciphertext = base64_decode($enc, true);
            if ($ciphertext === false) {
                return '';
            }
            return $this->ageIdentity->decryptChunk($ciphertext);
        } catch (\Throwable $e) {
            return '';
        }
    }

    /**
     * Encrypt and store a TOTP secret in a specific user-meta key.
     *
     * @param \WP_User $user
     * @param string   $secret  Raw base32 secret.
     * @param string   $metaKey META_SECRET or META_PENDING_SECRET.
     * @return void
     */
    private function storeSecretToMeta(\WP_User $user, string $secret, string $metaKey): void
    {
        if (!function_exists('update_user_meta')) {
            return;
        }
        try {
            $ciphertext = $this->ageIdentity->encryptChunk($secret);
            update_user_meta((int) $user->ID, $metaKey, base64_encode($ciphertext));
        } catch (\Throwable $e) {
            // Storage failure is non-fatal; the enrollment flow will surface this.
        }
    }

    /**
     * Encrypt and store a TOTP secret in user-meta (active slot).
     *
     * @param \WP_User $user
     * @param string   $secret Raw base32 secret.
     * @return void
     */
    private function storeSecret(\WP_User $user, string $secret): void
    {
        $this->storeSecretToMeta($user, $secret, self::META_SECRET);
    }

    /**
     * RFC 6238 / RFC 4226 HOTP: generate a 6-digit code for the given counter.
     *
     * @param string $secret  Raw base32-encoded secret.
     * @param int    $counter 8-byte counter value (TOTP: floor(time/period)).
     * @return string 6-digit zero-padded code.
     */
    private function generateCode(string $secret, int $counter): string
    {
        $key  = self::base32Decode($secret);
        // Pack counter as big-endian 8-byte integer.
        $msg  = pack('N*', 0) . pack('N*', $counter);
        $hash = hash_hmac('sha1', $msg, $key, true);
        // Dynamic truncation (RFC 4226 §5.3).
        $offset = ord($hash[19]) & 0x0F;
        $code   = (
            ((ord($hash[$offset]) & 0x7F) << 24)
            | ((ord($hash[$offset + 1]) & 0xFF) << 16)
            | ((ord($hash[$offset + 2]) & 0xFF) << 8)
            | (ord($hash[$offset + 3]) & 0xFF)
        ) % (10 ** self::DIGITS);

        return str_pad((string) $code, self::DIGITS, '0', STR_PAD_LEFT);
    }

    /**
     * Encode raw bytes to base32 (RFC 4648, no padding).
     *
     * @param string $data
     * @return string
     */
    private static function base32Encode(string $data): string
    {
        $alphabet = self::BASE32_CHARS;
        $out      = '';
        $buf      = 0;
        $bufLen   = 0;
        $dataLen  = strlen($data);
        for ($i = 0; $i < $dataLen; $i++) {
            $buf    = ($buf << 8) | ord($data[$i]);
            $bufLen += 8;
            while ($bufLen >= 5) {
                $bufLen -= 5;
                $out    .= $alphabet[($buf >> $bufLen) & 0x1F];
            }
        }
        if ($bufLen > 0) {
            $out .= $alphabet[($buf << (5 - $bufLen)) & 0x1F];
        }
        return $out;
    }

    /**
     * Decode a base32 string to raw bytes.
     *
     * @param string $data
     * @return string
     */
    private static function base32Decode(string $data): string
    {
        $alphabet = self::BASE32_CHARS;
        $data     = strtoupper($data);
        $lookup   = array_flip(str_split($alphabet));
        $out      = '';
        $buf      = 0;
        $bufLen   = 0;
        $dataLen  = strlen($data);
        for ($i = 0; $i < $dataLen; $i++) {
            $ch = $data[$i];
            if (!isset($lookup[$ch])) {
                continue;
            }
            $buf    = ($buf << 5) | $lookup[$ch];
            $bufLen += 5;
            if ($bufLen >= 8) {
                $bufLen -= 8;
                $out    .= chr(($buf >> $bufLen) & 0xFF);
            }
        }
        return $out;
    }
}
