-- name: CreateInvitation :one
INSERT INTO invitations (
    tenant_id, email, scope, site_id, role,
    token_hash, invited_by, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING *;

-- name: GetInvitationByTokenHash :one
-- Pre-auth lookup: must be run under InInviteLookupTx (app.invite_lookup='on').
SELECT * FROM invitations
WHERE token_hash = $1;

-- name: MarkInvitationAccepted :one
UPDATE invitations
SET accepted_at      = now(),
    accepted_user_id = $2
WHERE id = $1
  AND accepted_at IS NULL
RETURNING *;

-- name: IncrementInviteAttempts :one
UPDATE invitations
SET attempts = attempts + 1
WHERE id = $1
RETURNING *;

-- name: ListPendingInvitations :many
-- List pending (not yet accepted, not expired, not revoked) invitations for the
-- current tenant.
SELECT * FROM invitations
WHERE tenant_id  = $1
  AND accepted_at IS NULL
  AND revoked_at  IS NULL
  AND expires_at > now()
ORDER BY created_at DESC;

-- name: ListInvitationsForSite :many
-- Link history for one site: pending + accepted + expired + revoked, newest
-- first. Tenant-scoped by RLS; site-bound + scope-bound here. The caller derives
-- the display status (pending/accepted/expired/revoked) from the columns.
SELECT * FROM invitations
WHERE tenant_id = $1
  AND scope     = 'site'
  AND site_id   = $2
ORDER BY created_at DESC;

-- name: GetInvitationByID :one
-- By-id load for the per-site invitation management routes (revoke/regenerate).
-- Tenant isolation is enforced by RLS; the handler additionally verifies
-- site_id + scope against the path before mutating.
SELECT * FROM invitations
WHERE id = $1;

-- name: RevokeInvitation :one
-- Soft-revoke a still-pending invitation. Idempotent / race-safe: only an
-- un-accepted, un-revoked row is touched (RETURNING -> ErrNoRows if it was
-- accepted or already revoked between load and update).
UPDATE invitations
SET revoked_at = now(),
    revoked_by = $2
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at  IS NULL
RETURNING *;

-- name: RegenerateInvitationToken :one
-- Rotate the token of a still-pending invitation: overwrite token_hash (kills
-- the old link), reset expiry + attempts, and clear any prior soft-revoke.
-- Only an un-accepted row is touched (RETURNING -> ErrNoRows if already
-- accepted). The new raw token is generated by the caller.
UPDATE invitations
SET token_hash = $2,
    expires_at = $3,
    attempts   = 0,
    revoked_at = NULL,
    revoked_by = NULL
WHERE id = $1
  AND accepted_at IS NULL
RETURNING *;
