// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_billing.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminAccountPlanStatusCounts = `-- name: AdminAccountPlanStatusCounts :many

SELECT plan, plan_status, COUNT(*)::bigint AS cnt
FROM tenants
GROUP BY plan, plan_status
`

type AdminAccountPlanStatusCountsRow struct {
	Plan       string `json:"plan"`
	PlanStatus string `json:"plan_status"`
	Cnt        int64  `json:"cnt"`
}

// M16 Phase C1 — superadmin billing-admin panel (internal/admin). tenants
// carries no RLS (see schema.sql header), so every query below that touches
// ONLY tenants runs on the bare pool. Queries that join sites/memberships/
// backup_chunks/audit_log/billing_events must run under the tx wrapper noted
// on each query: InAgentTx for a query that spans MULTIPLE tenants in one
// pass (the *_agent SELECT-only policies — see m92 for backup_chunks_agent/
// audit_log_agent, which this feature adds; sites_agent/memberships_agent/
// billing_events_system already existed), InTenantTx(tenantID) for a query
// scoped to exactly one target tenant (the ordinary tenant_isolation policy
// already covers that — no agent scope needed).
// The instance-wide (plan, plan_status) census: source data for BOTH the
// accounts-page header tiles (MRR total via internal/billing's price ladder,
// active subs, past_due count, accounts total) and the revenue page's plan-
// distribution table + MRR tiles. tenants carries no RLS — bare pool.
// Deliberately NOT filtered by the accounts-list search/status/plan filters:
// these tiles always reflect the FULL instance regardless of what the
// operator is currently filtering the list by.
func (q *Queries) AdminAccountPlanStatusCounts(ctx context.Context) ([]AdminAccountPlanStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, adminAccountPlanStatusCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAccountPlanStatusCountsRow
	for rows.Next() {
		var i AdminAccountPlanStatusCountsRow
		if err := rows.Scan(&i.Plan, &i.PlanStatus, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminClearCompReason = `-- name: AdminClearCompReason :exec
UPDATE tenants
SET comp_reason = NULL, updated_at = now()
WHERE id = $1
`

// Clears comp_reason only, leaving plan/plan_status exactly as just written
// by billing.Service.ReconcileOneNow (used when a live provider subscription
// was adopted instead of falling back to free).
func (q *Queries) AdminClearCompReason(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, adminClearCompReason, tenantID)
	return err
}

const adminClearSuspended = `-- name: AdminClearSuspended :exec
UPDATE tenants
SET suspended_at = NULL, suspended_reason = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) AdminClearSuspended(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, adminClearSuspended, tenantID)
	return err
}

const adminForceState = `-- name: AdminForceState :exec
UPDATE tenants
SET plan = $1, plan_status = $2, grace_until = NULL, updated_at = now()
WHERE id = $3
`

type AdminForceStateParams struct {
	Plan       string    `json:"plan"`
	PlanStatus string    `json:"plan_status"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

// The manual force-state escape hatch for webhook drift: sets plan +
// plan_status directly, clearing grace_until (a forced state is authoritative
// — it should not inherit a stale grace window from whatever state preceded
// it).
func (q *Queries) AdminForceState(ctx context.Context, arg AdminForceStateParams) error {
	_, err := q.db.Exec(ctx, adminForceState, arg.Plan, arg.PlanStatus, arg.TenantID)
	return err
}

const adminGetAccountHeader = `-- name: AdminGetAccountHeader :one
WITH owner AS (
    SELECT DISTINCT ON (m.tenant_id) m.tenant_id, u.email
    FROM memberships m
    JOIN users u ON u.id = m.user_id
    WHERE m.role = 'owner'
    ORDER BY m.tenant_id, m.created_at ASC
)
SELECT
    t.id, t.name, t.slug, t.plan, t.plan_status, t.plan_overrides,
    t.grace_until, t.billing_provider, t.provider_customer_id,
    t.provider_subscription_id, t.current_period_end,
    t.comp_reason, t.suspended_at, t.suspended_reason, t.cancel_at_period_end,
    t.created_at,
    owner.email AS owner_email
FROM tenants t
LEFT JOIN owner ON owner.tenant_id = t.id
WHERE t.id = $1
`

type AdminGetAccountHeaderRow struct {
	ID                     uuid.UUID          `json:"id"`
	Name                   string             `json:"name"`
	Slug                   string             `json:"slug"`
	Plan                   string             `json:"plan"`
	PlanStatus             string             `json:"plan_status"`
	PlanOverrides          []byte             `json:"plan_overrides"`
	GraceUntil             pgtype.Timestamptz `json:"grace_until"`
	BillingProvider        *string            `json:"billing_provider"`
	ProviderCustomerID     *string            `json:"provider_customer_id"`
	ProviderSubscriptionID *string            `json:"provider_subscription_id"`
	CurrentPeriodEnd       pgtype.Timestamptz `json:"current_period_end"`
	CompReason             *string            `json:"comp_reason"`
	SuspendedAt            pgtype.Timestamptz `json:"suspended_at"`
	SuspendedReason        *string            `json:"suspended_reason"`
	CancelAtPeriodEnd      bool               `json:"cancel_at_period_end"`
	CreatedAt              time.Time          `json:"created_at"`
	OwnerEmail             *string            `json:"owner_email"`
}

// Account-detail header: org identity, plan/status, subscription card fields,
// comp/suspend state, + the first-owner email. Runs under
// InTenantTx(@tenant_id): tenants/users are unRLS'd; the owner-email join
// against memberships is covered by memberships_tenant_isolation once
// app.tenant_id = @tenant_id (no cross-tenant agent scope needed — this is a
// single target tenant). The "owner" CTE is joined via a plain LEFT JOIN
// (mirroring AdminListAccounts' "owners" CTE exactly) — sqlc only infers a
// LEFT-JOIN-ed column as nullable when the joined relation is a CTE, not an
// inline derived-table subquery, so this MUST stay a WITH ... AS () CTE.
func (q *Queries) AdminGetAccountHeader(ctx context.Context, tenantID uuid.UUID) (AdminGetAccountHeaderRow, error) {
	row := q.db.QueryRow(ctx, adminGetAccountHeader, tenantID)
	var i AdminGetAccountHeaderRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.PlanStatus,
		&i.PlanOverrides,
		&i.GraceUntil,
		&i.BillingProvider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodEnd,
		&i.CompReason,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.OwnerEmail,
	)
	return i, err
}

const adminGetAccountUsage = `-- name: AdminGetAccountUsage :one
SELECT
    billing_count_active_sites($1)::bigint AS sites_used,
    COALESCE((SELECT SUM(size) FROM backup_chunks WHERE tenant_id = $1), 0)::bigint AS managed_storage_bytes,
    (SELECT COUNT(*) FROM memberships WHERE tenant_id = $1)::bigint AS seats_used
`

type AdminGetAccountUsageRow struct {
	SitesUsed           int64 `json:"sites_used"`
	ManagedStorageBytes int64 `json:"managed_storage_bytes"`
	SeatsUsed           int64 `json:"seats_used"`
}

// Account-detail usage meters: sites/storage/seats. Runs under
// InTenantTx(@tenant_id) — billing_count_active_sites() is self-scoping
// (SECURITY DEFINER, see schema.sql) so it works under any tx context; the
// storage SUM and seats COUNT are covered by backup_chunks_tenant_isolation /
// memberships_tenant_isolation once app.tenant_id = @tenant_id.
func (q *Queries) AdminGetAccountUsage(ctx context.Context, tenantID uuid.UUID) (AdminGetAccountUsageRow, error) {
	row := q.db.QueryRow(ctx, adminGetAccountUsage, tenantID)
	var i AdminGetAccountUsageRow
	err := row.Scan(&i.SitesUsed, &i.ManagedStorageBytes, &i.SeatsUsed)
	return i, err
}

const adminGetLastBillingEventForTenant = `-- name: AdminGetLastBillingEventForTenant :one
SELECT occurred_at
FROM billing_events
WHERE tenant_id = $1
ORDER BY occurred_at DESC
LIMIT 1
`

// The account-detail subscription card's "last billing_events.occurred_at" +
// staleness flag input. Runs under InTenantTx(@tenant_id)
// (billing_events_tenant_isolation).
func (q *Queries) AdminGetLastBillingEventForTenant(ctx context.Context, tenantID pgtype.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, adminGetLastBillingEventForTenant, tenantID)
	var occurred_at time.Time
	err := row.Scan(&occurred_at)
	return occurred_at, err
}

const adminListAccountAuditEvents = `-- name: AdminListAccountAuditEvents :many
SELECT id, actor_type, actor_id, action, metadata, created_at
FROM audit_log
WHERE tenant_id = $1
  AND (action LIKE 'admin.billing.%' OR action LIKE 'billing.%')
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type AdminListAccountAuditEventsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	RowLimit int32     `json:"row_limit"`
}

type AdminListAccountAuditEventsRow struct {
	ID        uuid.UUID `json:"id"`
	ActorType string    `json:"actor_type"`
	ActorID   string    `json:"actor_id"`
	Action    string    `json:"action"`
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
}

// Account-detail timeline (audit half): only the admin.billing.*/billing.*
// prefixed actions (per the spec's "merged" timeline — everything else in
// the tenant's full audit trail is already visible via the ordinary Audit
// Log page). Runs under InTenantTx(@tenant_id) (audit_log_tenant_isolation).
func (q *Queries) AdminListAccountAuditEvents(ctx context.Context, arg AdminListAccountAuditEventsParams) ([]AdminListAccountAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, adminListAccountAuditEvents, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListAccountAuditEventsRow
	for rows.Next() {
		var i AdminListAccountAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAccountBillingEvents = `-- name: AdminListAccountBillingEvents :many
SELECT id, provider, kind, occurred_at, payload
FROM billing_events
WHERE tenant_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type AdminListAccountBillingEventsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	RowLimit int32       `json:"row_limit"`
}

type AdminListAccountBillingEventsRow struct {
	ID         uuid.UUID `json:"id"`
	Provider   string    `json:"provider"`
	Kind       string    `json:"kind"`
	OccurredAt time.Time `json:"occurred_at"`
	Payload    []byte    `json:"payload"`
}

// Account-detail timeline (billing half). Runs under InTenantTx(@tenant_id)
// (billing_events_tenant_isolation).
func (q *Queries) AdminListAccountBillingEvents(ctx context.Context, arg AdminListAccountBillingEventsParams) ([]AdminListAccountBillingEventsRow, error) {
	rows, err := q.db.Query(ctx, adminListAccountBillingEvents, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListAccountBillingEventsRow
	for rows.Next() {
		var i AdminListAccountBillingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Kind,
			&i.OccurredAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAccountMembers = `-- name: AdminListAccountMembers :many
SELECT
    u.id, u.email, u.name, m.role,
    u.status, u.email_verified_at IS NOT NULL AS email_verified,
    u.last_login_at, m.created_at AS member_since
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.tenant_id = $1
ORDER BY m.created_at ASC, u.id ASC
`

type AdminListAccountMembersRow struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	Name          string             `json:"name"`
	Role          string             `json:"role"`
	Status        string             `json:"status"`
	EmailVerified interface{}        `json:"email_verified"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	MemberSince   time.Time          `json:"member_since"`
}

// Account-detail member roster. Runs under InTenantTx(@tenant_id)
// (memberships_tenant_isolation).
func (q *Queries) AdminListAccountMembers(ctx context.Context, tenantID uuid.UUID) ([]AdminListAccountMembersRow, error) {
	rows, err := q.db.Query(ctx, adminListAccountMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListAccountMembersRow
	for rows.Next() {
		var i AdminListAccountMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.EmailVerified,
			&i.LastLoginAt,
			&i.MemberSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAccountSites = `-- name: AdminListAccountSites :many
SELECT id, url, connection_state, created_at
FROM sites
WHERE tenant_id = $1
ORDER BY created_at DESC, id DESC
`

type AdminListAccountSitesRow struct {
	ID              uuid.UUID `json:"id"`
	Url             string    `json:"url"`
	ConnectionState string    `json:"connection_state"`
	CreatedAt       time.Time `json:"created_at"`
}

// Account-detail compact site list. Runs under InTenantTx(@tenant_id)
// (sites_tenant_isolation).
func (q *Queries) AdminListAccountSites(ctx context.Context, tenantID uuid.UUID) ([]AdminListAccountSitesRow, error) {
	rows, err := q.db.Query(ctx, adminListAccountSites, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListAccountSitesRow
	for rows.Next() {
		var i AdminListAccountSitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.ConnectionState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAccounts = `-- name: AdminListAccounts :many
WITH owners AS (
    -- A plain (non-LATERAL) derived table joined by an explicit ON below: sqlc
    -- correctly infers this join's columns as nullable (mirrors
    -- AdminRevenueRecentEvents' "LEFT JOIN tenants" below), unlike a scalar
    -- subquery or LATERAL join in the SELECT list, which sqlc's analyzer does
    -- NOT mark nullable even though a zero-row lateral genuinely yields NULL
    -- (the same class of gap LastProcessedBillingEventOccurredAtForTenant's
    -- doc comment describes for aggregates) — DISTINCT ON picks exactly the
    -- first-created owner per tenant.
    SELECT DISTINCT ON (m.tenant_id) m.tenant_id, u.email
    FROM memberships m
    JOIN users u ON u.id = m.user_id
    WHERE m.role = 'owner'
    ORDER BY m.tenant_id, m.created_at ASC
),
acct AS (
    SELECT
        t.id                                        AS tenant_id,
        t.name                                       AS org_name,
        t.slug                                       AS org_slug,
        t.plan,
        t.plan_status,
        t.plan_overrides,
        t.grace_until,
        t.suspended_at,
        t.created_at,
        owners.email                                 AS owner_email,
        billing_count_active_sites(t.id)::bigint      AS sites_used,
        COALESCE(chunks.total_size, 0)::bigint        AS managed_storage_bytes,
        GREATEST(audit_row.last_at, sites_row.last_seen, members_row.last_login) AS last_activity
    FROM tenants t
    LEFT JOIN owners ON owners.tenant_id = t.id
    LEFT JOIN LATERAL (
        SELECT SUM(bc.size)::bigint AS total_size
        FROM backup_chunks bc
        WHERE bc.tenant_id = t.id
    ) chunks ON true
    LEFT JOIN LATERAL (
        SELECT MAX(al.created_at) AS last_at
        FROM audit_log al
        WHERE al.tenant_id = t.id
    ) audit_row ON true
    LEFT JOIN LATERAL (
        SELECT MAX(s.last_seen_at) AS last_seen
        FROM sites s
        WHERE s.tenant_id = t.id
    ) sites_row ON true
    LEFT JOIN LATERAL (
        SELECT MAX(u.last_login_at) AS last_login
        FROM memberships m
        JOIN users u ON u.id = m.user_id
        WHERE m.tenant_id = t.id
    ) members_row ON true
    WHERE
        ($2::bool = false OR
            t.name ILIKE '%' || $3 || '%' OR
            t.slug ILIKE '%' || $3 || '%' OR
            EXISTS (
                SELECT 1 FROM memberships m2
                JOIN users u2 ON u2.id = m2.user_id
                WHERE m2.tenant_id = t.id AND u2.email ILIKE '%' || $3 || '%'
            )
        )
        AND ($4::bool    = false OR t.plan_status = ANY($5::text[]))
        AND ($6::bool      = false OR t.plan = ANY($7::text[]))
        AND ($8::bool  = false OR t.plan_status = 'past_due')
        AND ($9::bool    = false OR t.plan_status = 'comped')
        AND ($10::bool = false OR t.plan_overrides <> '{}'::jsonb)
    ORDER BY t.created_at DESC, t.id DESC
    LIMIT 5000
)
SELECT tenant_id, org_name, org_slug, plan, plan_status, plan_overrides, grace_until, suspended_at, created_at, owner_email, sites_used, managed_storage_bytes, last_activity
FROM acct
WHERE ($1::bool = false OR
        (last_activity IS NOT NULL AND last_activity < now() - interval '90 days') OR
        (last_activity IS NULL AND created_at < now() - interval '90 days')
      )
ORDER BY created_at DESC, tenant_id DESC
`

type AdminListAccountsParams struct {
	IdleFilter      bool     `json:"idle_filter"`
	SearchFilter    bool     `json:"search_filter"`
	Search          *string  `json:"search"`
	StatusFilter    bool     `json:"status_filter"`
	Statuses        []string `json:"statuses"`
	PlanFilter      bool     `json:"plan_filter"`
	Plans           []string `json:"plans"`
	PastDueFilter   bool     `json:"past_due_filter"`
	CompedFilter    bool     `json:"comped_filter"`
	OverridesFilter bool     `json:"overrides_filter"`
}

type AdminListAccountsRow struct {
	TenantID            uuid.UUID          `json:"tenant_id"`
	OrgName             string             `json:"org_name"`
	OrgSlug             string             `json:"org_slug"`
	Plan                string             `json:"plan"`
	PlanStatus          string             `json:"plan_status"`
	PlanOverrides       []byte             `json:"plan_overrides"`
	GraceUntil          pgtype.Timestamptz `json:"grace_until"`
	SuspendedAt         pgtype.Timestamptz `json:"suspended_at"`
	CreatedAt           time.Time          `json:"created_at"`
	OwnerEmail          *string            `json:"owner_email"`
	SitesUsed           int64              `json:"sites_used"`
	ManagedStorageBytes int64              `json:"managed_storage_bytes"`
	LastActivity        interface{}        `json:"last_activity"`
}

// The accounts-list aggregate: one row per tenant with every raw field the
// superadmin billing panel's list view needs, computed via LEFT JOIN LATERAL
// (NOT a query-per-tenant). MRR, effective caps, near-limit, and the
// needs-attention sort are computed in Go (internal/admin/billing_service.go)
// from internal/billing's price ladder / entitlement resolver — this query
// only returns the raw counts/timestamps/plan fields those computations need.
//
// DB-native filters (search/status/plan/past_due/comped/has_overrides) are
// applied here; idle-90d (which depends on the computed last_activity
// column) is applied in the outer SELECT over the "acct" CTE, since a
// LATERAL-computed alias cannot be referenced in the same query's own WHERE
// clause. near-limit is NOT filterable here (ladder-aware; computed in Go
// from MaxSites/ManagedStorageBytes, which are Go constants).
//
// LIMIT 5000 inside the CTE is a safety valve bounding how many tenants this
// single query will ever join/aggregate in one pass, independent of the
// caller's requested page size (which is applied AFTER Go-side sort/filter);
// add real keyset pagination here if an instance ever exceeds it.
//
// Runs under InAgentTx: sites_agent + memberships_agent + backup_chunks_agent
// (m92) + audit_log_agent (m92) all gate on app.agent='on'.
func (q *Queries) AdminListAccounts(ctx context.Context, arg AdminListAccountsParams) ([]AdminListAccountsRow, error) {
	rows, err := q.db.Query(ctx, adminListAccounts,
		arg.IdleFilter,
		arg.SearchFilter,
		arg.Search,
		arg.StatusFilter,
		arg.Statuses,
		arg.PlanFilter,
		arg.Plans,
		arg.PastDueFilter,
		arg.CompedFilter,
		arg.OverridesFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListAccountsRow
	for rows.Next() {
		var i AdminListAccountsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.OrgName,
			&i.OrgSlug,
			&i.Plan,
			&i.PlanStatus,
			&i.PlanOverrides,
			&i.GraceUntil,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.OwnerEmail,
			&i.SitesUsed,
			&i.ManagedStorageBytes,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRevenueActivationCountsThisMonth = `-- name: AdminRevenueActivationCountsThisMonth :one
SELECT
    COUNT(DISTINCT tenant_id) FILTER (
        WHERE payload->>'normalized_kind' = 'activated'
          AND occurred_at >= date_trunc('month', now())
    )::bigint AS new_this_month,
    COUNT(DISTINCT tenant_id) FILTER (
        WHERE payload->>'normalized_kind' = 'canceled'
          AND occurred_at >= date_trunc('month', now())
    )::bigint AS canceled_this_month
FROM billing_events
WHERE tenant_id IS NOT NULL
`

type AdminRevenueActivationCountsThisMonthRow struct {
	NewThisMonth      int64 `json:"new_this_month"`
	CanceledThisMonth int64 `json:"canceled_this_month"`
}

// "new-this-month" / "canceled-this-month": distinct tenants with an
// activation-shaped / cancellation-shaped billing event this calendar month.
// Reads payload->>'normalized_kind' (billing.EventActivated /
// billing.EventCanceled — the PROVIDER-AGNOSTIC normalized kind, not the raw
// provider event-type string) rather than a provider-specific literal, so
// this stays correct if a second provider adapter is ever wired. Runs under
// InAgentTx (billing_events_system spans all tenants).
func (q *Queries) AdminRevenueActivationCountsThisMonth(ctx context.Context) (AdminRevenueActivationCountsThisMonthRow, error) {
	row := q.db.QueryRow(ctx, adminRevenueActivationCountsThisMonth)
	var i AdminRevenueActivationCountsThisMonthRow
	err := row.Scan(&i.NewThisMonth, &i.CanceledThisMonth)
	return i, err
}

const adminRevenueLastWebhookReceivedAt = `-- name: AdminRevenueLastWebhookReceivedAt :one
SELECT created_at
FROM billing_events
WHERE provider <> 'admin'
ORDER BY created_at DESC
LIMIT 1
`

// The revenue page's "last webhook received" staleness footer: the newest
// created_at (CP receipt time, not the provider's own occurred_at) among
// REAL provider deliveries — provider <> 'admin' excludes the superadmin's
// own manual billing_events rows (see RecordAdminBillingEvent), which are not
// webhook deliveries and would otherwise mask a genuinely stalled webhook
// pipe. Deliberately NOT a bare MAX() aggregate (see
// LastProcessedBillingEventOccurredAtForTenant's doc comment in billing.sql
// for why): an empty billing_events table must yield "no rows" rather than a
// NULL scan panic. Runs under InAgentTx (billing_events_system).
func (q *Queries) AdminRevenueLastWebhookReceivedAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, adminRevenueLastWebhookReceivedAt)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const adminRevenuePastDueList = `-- name: AdminRevenuePastDueList :many

WITH owner AS (
    SELECT DISTINCT ON (m.tenant_id) m.tenant_id, u.email
    FROM memberships m
    JOIN users u ON u.id = m.user_id
    WHERE m.role = 'owner'
    ORDER BY m.tenant_id, m.created_at ASC
),
last_failed AS (
    SELECT DISTINCT ON (be.tenant_id) be.tenant_id, be.occurred_at
    FROM billing_events be
    WHERE be.payload->>'normalized_kind' = 'payment_failed'
    ORDER BY be.tenant_id, be.occurred_at DESC
)
SELECT
    t.id AS tenant_id, t.name AS org_name, t.slug AS org_slug, t.plan,
    t.grace_until,
    owner.email AS owner_email,
    last_failed.occurred_at AS last_payment_failed_at
FROM tenants t
LEFT JOIN owner ON owner.tenant_id = t.id
LEFT JOIN last_failed ON last_failed.tenant_id = t.id
WHERE t.plan_status = 'past_due'
ORDER BY t.grace_until ASC NULLS LAST, t.id ASC
`

type AdminRevenuePastDueListRow struct {
	TenantID            uuid.UUID          `json:"tenant_id"`
	OrgName             string             `json:"org_name"`
	OrgSlug             string             `json:"org_slug"`
	Plan                string             `json:"plan"`
	GraceUntil          pgtype.Timestamptz `json:"grace_until"`
	OwnerEmail          *string            `json:"owner_email"`
	LastPaymentFailedAt pgtype.Timestamptz `json:"last_payment_failed_at"`
}

// ---------------------------------------------------------------------------
// Revenue page (internal/admin) — local state only, zero provider API calls.
// ---------------------------------------------------------------------------
// The past-due list: org + owner email + amount (Go computes amount from the
// ladder price for t.plan) + grace_until (Go computes "days past due" from
// this using billing.PastDueGracePeriod()) + last payment-failed event. Both
// are CTEs joined via a plain LEFT JOIN (see AdminGetAccountHeader's "owner"
// CTE comment for why this must be a CTE, not an inline derived-table
// subquery, for sqlc to infer the columns nullable). Runs under InAgentTx:
// the owner join spans multiple tenants (memberships_agent) and the
// payment-failed join reads billing_events cross-tenant
// (billing_events_system, already existed pre-m92).
func (q *Queries) AdminRevenuePastDueList(ctx context.Context) ([]AdminRevenuePastDueListRow, error) {
	rows, err := q.db.Query(ctx, adminRevenuePastDueList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminRevenuePastDueListRow
	for rows.Next() {
		var i AdminRevenuePastDueListRow
		if err := rows.Scan(
			&i.TenantID,
			&i.OrgName,
			&i.OrgSlug,
			&i.Plan,
			&i.GraceUntil,
			&i.OwnerEmail,
			&i.LastPaymentFailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRevenueRecentEvents = `-- name: AdminRevenueRecentEvents :many
SELECT be.id, be.provider, be.kind, be.occurred_at, be.created_at,
       be.tenant_id, t.name AS org_name, t.slug AS org_slug
FROM billing_events be
LEFT JOIN tenants t ON t.id = be.tenant_id
ORDER BY be.occurred_at DESC, be.id DESC
LIMIT 20
`

type AdminRevenueRecentEventsRow struct {
	ID         uuid.UUID   `json:"id"`
	Provider   string      `json:"provider"`
	Kind       string      `json:"kind"`
	OccurredAt time.Time   `json:"occurred_at"`
	CreatedAt  time.Time   `json:"created_at"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	OrgName    *string     `json:"org_name"`
	OrgSlug    *string     `json:"org_slug"`
}

// The last 20 billing_events across every tenant, for the revenue page's
// recent-activity feed. Runs under InAgentTx (billing_events_system).
func (q *Queries) AdminRevenueRecentEvents(ctx context.Context) ([]AdminRevenueRecentEventsRow, error) {
	rows, err := q.db.Query(ctx, adminRevenueRecentEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminRevenueRecentEventsRow
	for rows.Next() {
		var i AdminRevenueRecentEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Kind,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.TenantID,
			&i.OrgName,
			&i.OrgSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRevokeCompToFree = `-- name: AdminRevokeCompToFree :exec
UPDATE tenants
SET plan = 'free', plan_status = 'none', comp_reason = NULL, grace_until = NULL, updated_at = now()
WHERE id = $1
`

// Reverts a comp when the tenant has no live provider subscription to adopt
// instead: falls back to the same "never subscribed" resting state a brand
// new tenant starts in.
func (q *Queries) AdminRevokeCompToFree(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, adminRevokeCompToFree, tenantID)
	return err
}

const adminSetGrace = `-- name: AdminSetGrace :exec
UPDATE tenants
SET grace_until = $1, updated_at = now()
WHERE id = $2
`

type AdminSetGraceParams struct {
	GraceUntil pgtype.Timestamptz `json:"grace_until"`
	TenantID   uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) AdminSetGrace(ctx context.Context, arg AdminSetGraceParams) error {
	_, err := q.db.Exec(ctx, adminSetGrace, arg.GraceUntil, arg.TenantID)
	return err
}

const adminSetOverrides = `-- name: AdminSetOverrides :exec
UPDATE tenants
SET plan_overrides = $1, updated_at = now()
WHERE id = $2
`

type AdminSetOverridesParams struct {
	PlanOverrides []byte    `json:"plan_overrides"`
	TenantID      uuid.UUID `json:"tenant_id"`
}

// Persists the FULL resolved plan_overrides object (the caller has already
// merged the requested deltas onto the existing overrides in Go).
func (q *Queries) AdminSetOverrides(ctx context.Context, arg AdminSetOverridesParams) error {
	_, err := q.db.Exec(ctx, adminSetOverrides, arg.PlanOverrides, arg.TenantID)
	return err
}

const adminSetSuspended = `-- name: AdminSetSuspended :exec
UPDATE tenants
SET suspended_at = now(), suspended_reason = $1, updated_at = now()
WHERE id = $2
`

type AdminSetSuspendedParams struct {
	SuspendedReason *string   `json:"suspended_reason"`
	TenantID        uuid.UUID `json:"tenant_id"`
}

func (q *Queries) AdminSetSuspended(ctx context.Context, arg AdminSetSuspendedParams) error {
	_, err := q.db.Exec(ctx, adminSetSuspended, arg.SuspendedReason, arg.TenantID)
	return err
}

const adminSetTenantComp = `-- name: AdminSetTenantComp :exec

UPDATE tenants
SET plan = $1, plan_status = 'comped', comp_reason = $2, updated_at = now()
WHERE id = $3
`

type AdminSetTenantCompParams struct {
	Plan       string    `json:"plan"`
	CompReason *string   `json:"comp_reason"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

// ---------------------------------------------------------------------------
// Mutations (all superadmin-only; internal/admin validates + audits around
// each of these). Every query below runs on the bare pool (tenants carries no
// RLS) except where noted.
// ---------------------------------------------------------------------------
// Grants a manual comp: plan_status='comped', plan=@plan, comp_reason set.
func (q *Queries) AdminSetTenantComp(ctx context.Context, arg AdminSetTenantCompParams) error {
	_, err := q.db.Exec(ctx, adminSetTenantComp, arg.Plan, arg.CompReason, arg.TenantID)
	return err
}
