// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_trust.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applySiteAIModeEnableDefault = `-- name: ApplySiteAIModeEnableDefault :one
UPDATE sites SET
    ai_mode         = 'ai_drafts',
    ai_mode_source  = 'enable_default',
    ai_mode_set_by  = $1::uuid,
    ai_mode_set_at  = now(),
    ai_mode_version = ai_mode_version + 1,
    updated_at      = now()
WHERE tenant_id = $2
  AND id = $3
  AND ai_mode_source = 'unset'
  AND content_editing_enabled_at IS NOT NULL
RETURNING id, ai_mode, ai_mode_source, ai_mode_set_by, ai_mode_set_at, ai_mode_version
`

type ApplySiteAIModeEnableDefaultParams struct {
	EnabledBy uuid.UUID `json:"enabled_by"`
	TenantID  uuid.UUID `json:"tenant_id"`
	SiteID    uuid.UUID `json:"site_id"`
}

type ApplySiteAIModeEnableDefaultRow struct {
	ID            uuid.UUID          `json:"id"`
	AiMode        string             `json:"ai_mode"`
	AiModeSource  string             `json:"ai_mode_source"`
	AiModeSetBy   pgtype.UUID        `json:"ai_mode_set_by"`
	AiModeSetAt   pgtype.Timestamptz `json:"ai_mode_set_at"`
	AiModeVersion int64              `json:"ai_mode_version"`
}

// The default a site gets when a person turns AI editing on: Auto for AI
// drafts, source 'enable_default', that person as the setter. Run it in the
// same transaction as MarkSiteContentEditingEnabled, with that person's
// app.user_id. It moves only a site whose mode no one has set ('unset') and
// whose AI editing is on, so turning AI editing on again never resets a
// choice a person made, the launch default or a tightening. No row
// (pgx.ErrNoRows) means the site already carries a mode and nothing changed,
// or the site is not visible to the caller.
func (q *Queries) ApplySiteAIModeEnableDefault(ctx context.Context, arg ApplySiteAIModeEnableDefaultParams) (ApplySiteAIModeEnableDefaultRow, error) {
	row := q.db.QueryRow(ctx, applySiteAIModeEnableDefault, arg.EnabledBy, arg.TenantID, arg.SiteID)
	var i ApplySiteAIModeEnableDefaultRow
	err := row.Scan(
		&i.ID,
		&i.AiMode,
		&i.AiModeSource,
		&i.AiModeSetBy,
		&i.AiModeSetAt,
		&i.AiModeVersion,
	)
	return i, err
}

const claimSiteAILaunchNotices = `-- name: ClaimSiteAILaunchNotices :many
UPDATE sites SET
    ai_mode_launch_emailed_at = now()
WHERE tenant_id = $1
  AND ai_mode_source = 'launch_default'
  AND ai_mode_launch_emailed_at IS NULL
RETURNING id, name, url, ai_mode_launch_emailed_at
`

type ClaimSiteAILaunchNoticesRow struct {
	ID                    uuid.UUID          `json:"id"`
	Name                  string             `json:"name"`
	Url                   string             `json:"url"`
	AiModeLaunchEmailedAt pgtype.Timestamptz `json:"ai_mode_launch_emailed_at"`
}

// One tenant's sites still on the launch default whose owners have not been
// told, claimed by stamping ai_mode_launch_emailed_at. Every row this
// statement claims carries the same stamp (now() is the transaction's start
// time); pass it to ReleaseSiteAILaunchNotices when the send fails, so the
// next run claims the sites again. A site whose mode a person has since
// chosen is no longer on the launch default and is not claimed. The stamp is
// not one of the columns sites_ai_mode_guard watches.
func (q *Queries) ClaimSiteAILaunchNotices(ctx context.Context, tenantID uuid.UUID) ([]ClaimSiteAILaunchNoticesRow, error) {
	rows, err := q.db.Query(ctx, claimSiteAILaunchNotices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimSiteAILaunchNoticesRow
	for rows.Next() {
		var i ClaimSiteAILaunchNoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.AiModeLaunchEmailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAIConnectionPolicyApprovals = `-- name: CountAIConnectionPolicyApprovals :one
SELECT count(*)::bigint                AS changes,
       count(DISTINCT site_id)::bigint AS sites
FROM assistant_ability_requests
WHERE tenant_id = $1
  AND proposed_by_grant_id = $2
  AND approval_source = 'policy'
  AND change_class = ANY($3::text[])
  AND decided_at > now() - ($4::int * interval '1 second')
`

type CountAIConnectionPolicyApprovalsParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	GrantID       uuid.UUID `json:"grant_id"`
	Classes       []string  `json:"classes"`
	WindowSeconds int32     `json:"window_seconds"`
}

type CountAIConnectionPolicyApprovalsRow struct {
	Changes int64 `json:"changes"`
	Sites   int64 `json:"sites"`
}

// What one connection ran by a site's setting in the window: approvals with
// approval_source 'policy' whose class is in classes, and on how many sites.
// Site changes only; cache clears are counted from their own table.
func (q *Queries) CountAIConnectionPolicyApprovals(ctx context.Context, arg CountAIConnectionPolicyApprovalsParams) (CountAIConnectionPolicyApprovalsRow, error) {
	row := q.db.QueryRow(ctx, countAIConnectionPolicyApprovals,
		arg.TenantID,
		arg.GrantID,
		arg.Classes,
		arg.WindowSeconds,
	)
	var i CountAIConnectionPolicyApprovalsRow
	err := row.Scan(&i.Changes, &i.Sites)
	return i, err
}

const getAIConnectionAuto = `-- name: GetAIConnectionAuto :one

SELECT g.id,
       g.status,
       g.expires_at,
       g.created_by_user_id,
       g.ai_auto,
       g.ai_auto_set_by,
       g.ai_auto_set_at,
       u.name AS auto_set_by_name,
       (g.ai_auto_set_by IS NOT NULL AND u.id IS NULL)::boolean AS auto_set_by_account_deleted
FROM mcp_grants g
LEFT JOIN users u ON u.id = g.ai_auto_set_by
WHERE g.tenant_id = $1
  AND g.id = $2
`

type GetAIConnectionAutoParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	GrantID  uuid.UUID `json:"grant_id"`
}

type GetAIConnectionAutoRow struct {
	ID                      uuid.UUID          `json:"id"`
	Status                  string             `json:"status"`
	ExpiresAt               time.Time          `json:"expires_at"`
	CreatedByUserID         pgtype.UUID        `json:"created_by_user_id"`
	AiAuto                  string             `json:"ai_auto"`
	AiAutoSetBy             pgtype.UUID        `json:"ai_auto_set_by"`
	AiAutoSetAt             pgtype.Timestamptz `json:"ai_auto_set_at"`
	AutoSetByName           *string            `json:"auto_set_by_name"`
	AutoSetByAccountDeleted bool               `json:"auto_set_by_account_deleted"`
}

// ---------------------------------------------------------------------------
// The connection's switch and usage
// ---------------------------------------------------------------------------
// The connection's switch: 'site_setting' (runs a change where the site's
// mode allows it) or 'never', who allowed it and when, and whether that
// account still exists. created_by_user_id is NULL for a connection minted
// with an API key. No row (pgx.ErrNoRows) when there is no such connection in
// the tenant, or the transaction is site-scoped.
func (q *Queries) GetAIConnectionAuto(ctx context.Context, arg GetAIConnectionAutoParams) (GetAIConnectionAutoRow, error) {
	row := q.db.QueryRow(ctx, getAIConnectionAuto, arg.TenantID, arg.GrantID)
	var i GetAIConnectionAutoRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedByUserID,
		&i.AiAuto,
		&i.AiAutoSetBy,
		&i.AiAutoSetAt,
		&i.AutoSetByName,
		&i.AutoSetByAccountDeleted,
	)
	return i, err
}

const getSiteAIMode = `-- name: GetSiteAIMode :one


SELECT s.id,
       s.ai_mode,
       s.ai_mode_source,
       s.ai_mode_set_by,
       s.ai_mode_set_at,
       s.ai_mode_version,
       s.ai_mode_step_up,
       s.ai_mode_launch_emailed_at,
       s.content_editing_enabled_at,
       u.name AS set_by_name,
       (s.ai_mode_set_by IS NOT NULL AND u.id IS NULL)::boolean AS set_by_account_deleted
FROM sites s
LEFT JOIN users u ON u.id = s.ai_mode_set_by
WHERE s.tenant_id = $1
  AND s.id = $2
`

type GetSiteAIModeParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
}

type GetSiteAIModeRow struct {
	ID                      uuid.UUID          `json:"id"`
	AiMode                  string             `json:"ai_mode"`
	AiModeSource            string             `json:"ai_mode_source"`
	AiModeSetBy             pgtype.UUID        `json:"ai_mode_set_by"`
	AiModeSetAt             pgtype.Timestamptz `json:"ai_mode_set_at"`
	AiModeVersion           int64              `json:"ai_mode_version"`
	AiModeStepUp            *string            `json:"ai_mode_step_up"`
	AiModeLaunchEmailedAt   pgtype.Timestamptz `json:"ai_mode_launch_emailed_at"`
	ContentEditingEnabledAt pgtype.Timestamptz `json:"content_editing_enabled_at"`
	SetByName               *string            `json:"set_by_name"`
	SetByAccountDeleted     bool               `json:"set_by_account_deleted"`
}

// ai_trust (m174): the site's AI mode, the connection's switch, the
// connection's automatic usage, the AI activity feed, and the one-time
// notice to organisations whose sites moved to the launch default.
//
// WHICH TRANSACTION, PER STATEMENT.
//
//   - The site mode statements run in the caller's own tenant transaction
//     (db.RunTenantTx with the request's principal). sites is FORCE ROW LEVEL
//     SECURITY with sites_tenant_isolation and the RESTRICTIVE
//     sites_site_scope, so a site collaborator reads and writes only their own
//     sites. sites_ai_mode_guard decides who may write which mode: a mode
//     above ask is written only with app.user_id equal to the recorded setter,
//     and with no user the only write is down to ask, recorded as tightened.
//   - The connection statements run in an organisation-wide tenant
//     transaction. mcp_grants_site_scope_select and _update refuse every
//     grant row while app.site_scope is 'on', so a site-scoped principal reads
//     and writes none (a connection is an organisation-wide credential).
//     mcp_grants_ai_auto_guard requires app.user_id to be the recorded setter
//     whenever a connection is allowed to run by the site's setting.
//   - The usage count runs organisation-wide (db.InTenantTx), as the decision
//     engine's own count does: a site allowlist in the transaction would
//     undercount and fail open.
//   - The activity page runs under the caller's principal: row security
//     narrows a site collaborator to their own sites on both request tables.
//   - The launch notice runs once per tenant under db.InTenantTx. sites is
//     FORCE ROW LEVEL SECURITY, so a statement with no tenant in the
//     transaction sees no site and claims nothing.
//
// TIME IS THE DATABASE'S. Windows arrive as whole seconds and are measured
// against now() in the database.
// ---------------------------------------------------------------------------
// The site's AI mode
// ---------------------------------------------------------------------------
// The site's mode, how it was chosen, by whom and when, its version, and
// whether AI editing is on. set_by_name is a person's name (render it as
// text); set_by_account_deleted is true when a setter is recorded and that
// account no longer exists. No row (pgx.ErrNoRows) when the site is not
// visible to the caller.
func (q *Queries) GetSiteAIMode(ctx context.Context, arg GetSiteAIModeParams) (GetSiteAIModeRow, error) {
	row := q.db.QueryRow(ctx, getSiteAIMode, arg.TenantID, arg.SiteID)
	var i GetSiteAIModeRow
	err := row.Scan(
		&i.ID,
		&i.AiMode,
		&i.AiModeSource,
		&i.AiModeSetBy,
		&i.AiModeSetAt,
		&i.AiModeVersion,
		&i.AiModeStepUp,
		&i.AiModeLaunchEmailedAt,
		&i.ContentEditingEnabledAt,
		&i.SetByName,
		&i.SetByAccountDeleted,
	)
	return i, err
}

const listAIActivityPage = `-- name: ListAIActivityPage :many

SELECT a.kind::text             AS kind,
       a.id::uuid               AS id,
       a.created_at::timestamptz AS created_at
FROM (
    SELECT 'ability_request'::text AS kind, r.id, r.created_at
    FROM assistant_ability_requests r
    WHERE r.tenant_id = $1
      AND r.state IN ('approved', 'dispatched', 'done', 'failed', 'not_sent', 'outcome_unknown')
      AND ($2::uuid IS NULL OR r.site_id = $2::uuid)
      AND ($3::uuid IS NULL OR r.proposed_by_grant_id = $3::uuid)
      AND CASE $4::text
              WHEN 'all'                THEN true
              WHEN 'ran_automatically'  THEN r.approval_source <> 'person'
              WHEN 'approved_by_person' THEN r.approval_source = 'person'
              WHEN 'failed_or_unknown'  THEN r.state IN ('failed', 'outcome_unknown')
              WHEN 'undone'             THEN r.undo_state IS NOT DISTINCT FROM 'undone'
              ELSE false
          END
      AND ($5::timestamptz IS NULL
           OR (r.created_at, r.id) < ($5::timestamptz, $6::uuid))
    UNION ALL
    SELECT 'cache_purge_request'::text AS kind, p.id, p.created_at
    FROM assistant_cache_purge_requests p
    WHERE p.tenant_id = $1
      AND p.state IN ('approved_undispatched', 'dispatched')
      AND ($2::uuid IS NULL OR p.site_id = $2::uuid)
      AND ($3::uuid IS NULL OR p.proposed_by_grant_id = $3::uuid)
      AND CASE $4::text
              WHEN 'all'                THEN true
              WHEN 'ran_automatically'  THEN p.approval_source <> 'person'
              WHEN 'approved_by_person' THEN p.approval_source = 'person'
              WHEN 'failed_or_unknown'  THEN p.outcome IS NOT NULL
                                             AND p.outcome IN ('site_reported_failure', 'agent_failed', 'outcome_unknown')
              ELSE false
          END
      AND ($5::timestamptz IS NULL
           OR (p.created_at, p.id) < ($5::timestamptz, $6::uuid))
) a
ORDER BY a.created_at DESC, a.id DESC
LIMIT $7::int
`

type ListAIActivityPageParams struct {
	TenantID        uuid.UUID          `json:"tenant_id"`
	SiteID          pgtype.UUID        `json:"site_id"`
	GrantID         pgtype.UUID        `json:"grant_id"`
	Filter          string             `json:"filter"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	RowLimit        int32              `json:"row_limit"`
}

type ListAIActivityPageRow struct {
	Kind      string    `json:"kind"`
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

// ---------------------------------------------------------------------------
// AI activity
// ---------------------------------------------------------------------------
// One page of the activity feed: every approved request from both request
// tables, newest first, keyset on (created_at, id). It returns which table
// and which id; ListAbilityRequestsByIDs and
// ListAssistantCachePurgeRequestsByIDs read the rows, in the same
// transaction.
//
// Approved means the request entered the approved states: for site changes
// approved, dispatched, done, failed, not_sent or outcome_unknown; for cache
// clears approved_undispatched or dispatched. Waiting, declined, withdrawn
// and expired requests are not listed.
//
// filter is one of all, ran_automatically (approved by a setting or a
// session), approved_by_person, failed_or_unknown or undone; anything else
// lists nothing. site_id and grant_id narrow the page when set. The first
// page passes NULL cursor_created_at and cursor_id; a later page passes the
// created_at and id of the previous page's last row.
func (q *Queries) ListAIActivityPage(ctx context.Context, arg ListAIActivityPageParams) ([]ListAIActivityPageRow, error) {
	rows, err := q.db.Query(ctx, listAIActivityPage,
		arg.TenantID,
		arg.SiteID,
		arg.GrantID,
		arg.Filter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIActivityPageRow
	for rows.Next() {
		var i ListAIActivityPageRow
		if err := rows.Scan(&i.Kind, &i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAbilityRequestsByIDs = `-- name: ListAbilityRequestsByIDs :many
SELECT id, tenant_id, site_id, proposed_by_grant_id, entry_id, entry_sha256, ability_name, operator_permission, input_json, input_sha256, target_post_id, target_key, precheck_digest, preview_digest, base_fingerprint, site_label, site_host, grant_label, grant_via, setup_client, title_excerpt, editor, post_type, effect_copy, snapshot, card_copy_version, digest_nonce, presented_digest, state, created_at, expires_at, decided_at, decided_by_user_id, withdrawn_at, dispatch_deadline_at, claimed_at, dispatch_attempts, last_attempt_at, last_attempt_code, unknown_since, ledger_checked_at, outcome, outcome_at, outcome_code, not_sent_reason, created_post_id, restored, trashed, site_reported_text, undo_state, undo_available_until, undo_by_user_id, undo_started_at, undo_finished_at, route_id, route_sha256, card_facts, approval_source, approval_site_mode, approval_mode_source, approval_mode_version, approval_setter_user_id, approval_setter_set_at, approval_session_id, base_change_class, change_class, ask_reason, policy_checked_at, checked_target_status, snapshot_sha256, undo_code
FROM assistant_ability_requests
WHERE tenant_id = $1
  AND id = ANY($2::uuid[])
ORDER BY created_at DESC, id DESC
`

type ListAbilityRequestsByIDsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Ids      []uuid.UUID `json:"ids"`
}

// The site-change rows of one activity page, newest first.
func (q *Queries) ListAbilityRequestsByIDs(ctx context.Context, arg ListAbilityRequestsByIDsParams) ([]AssistantAbilityRequest, error) {
	rows, err := q.db.Query(ctx, listAbilityRequestsByIDs, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistantAbilityRequest
	for rows.Next() {
		var i AssistantAbilityRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.ProposedByGrantID,
			&i.EntryID,
			&i.EntrySha256,
			&i.AbilityName,
			&i.OperatorPermission,
			&i.InputJson,
			&i.InputSha256,
			&i.TargetPostID,
			&i.TargetKey,
			&i.PrecheckDigest,
			&i.PreviewDigest,
			&i.BaseFingerprint,
			&i.SiteLabel,
			&i.SiteHost,
			&i.GrantLabel,
			&i.GrantVia,
			&i.SetupClient,
			&i.TitleExcerpt,
			&i.Editor,
			&i.PostType,
			&i.EffectCopy,
			&i.Snapshot,
			&i.CardCopyVersion,
			&i.DigestNonce,
			&i.PresentedDigest,
			&i.State,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.DecidedAt,
			&i.DecidedByUserID,
			&i.WithdrawnAt,
			&i.DispatchDeadlineAt,
			&i.ClaimedAt,
			&i.DispatchAttempts,
			&i.LastAttemptAt,
			&i.LastAttemptCode,
			&i.UnknownSince,
			&i.LedgerCheckedAt,
			&i.Outcome,
			&i.OutcomeAt,
			&i.OutcomeCode,
			&i.NotSentReason,
			&i.CreatedPostID,
			&i.Restored,
			&i.Trashed,
			&i.SiteReportedText,
			&i.UndoState,
			&i.UndoAvailableUntil,
			&i.UndoByUserID,
			&i.UndoStartedAt,
			&i.UndoFinishedAt,
			&i.RouteID,
			&i.RouteSha256,
			&i.CardFacts,
			&i.ApprovalSource,
			&i.ApprovalSiteMode,
			&i.ApprovalModeSource,
			&i.ApprovalModeVersion,
			&i.ApprovalSetterUserID,
			&i.ApprovalSetterSetAt,
			&i.ApprovalSessionID,
			&i.BaseChangeClass,
			&i.ChangeClass,
			&i.AskReason,
			&i.PolicyCheckedAt,
			&i.CheckedTargetStatus,
			&i.SnapshotSha256,
			&i.UndoCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantCachePurgeRequestsByIDs = `-- name: ListAssistantCachePurgeRequestsByIDs :many
SELECT id, tenant_id, site_id, proposed_by_grant_id, scope, url, site_label, site_host, grant_label, grant_via, setup_client, digest_nonce, presented_digest, state, created_at, expires_at, decided_at, decided_by_user_id, withdrawn_at, claimed_at, cache_purge_audit_id, dispatch_attempts, last_attempt_at, last_attempt_code, outcome, not_sent_reason, outcome_at, hosting_caches_cleared, hosting_caches_skipped, origin_only_confirmed, wpmgr_cdn, site_reported_text, approval_source, approval_site_mode, approval_mode_source, approval_mode_version, approval_setter_user_id, approval_setter_set_at, approval_session_id, base_change_class, change_class, ask_reason, policy_checked_at
FROM assistant_cache_purge_requests
WHERE tenant_id = $1
  AND id = ANY($2::uuid[])
ORDER BY created_at DESC, id DESC
`

type ListAssistantCachePurgeRequestsByIDsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Ids      []uuid.UUID `json:"ids"`
}

// The cache-clear rows of one activity page, newest first.
func (q *Queries) ListAssistantCachePurgeRequestsByIDs(ctx context.Context, arg ListAssistantCachePurgeRequestsByIDsParams) ([]AssistantCachePurgeRequest, error) {
	rows, err := q.db.Query(ctx, listAssistantCachePurgeRequestsByIDs, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistantCachePurgeRequest
	for rows.Next() {
		var i AssistantCachePurgeRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.ProposedByGrantID,
			&i.Scope,
			&i.Url,
			&i.SiteLabel,
			&i.SiteHost,
			&i.GrantLabel,
			&i.GrantVia,
			&i.SetupClient,
			&i.DigestNonce,
			&i.PresentedDigest,
			&i.State,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.DecidedAt,
			&i.DecidedByUserID,
			&i.WithdrawnAt,
			&i.ClaimedAt,
			&i.CachePurgeAuditID,
			&i.DispatchAttempts,
			&i.LastAttemptAt,
			&i.LastAttemptCode,
			&i.Outcome,
			&i.NotSentReason,
			&i.OutcomeAt,
			&i.HostingCachesCleared,
			&i.HostingCachesSkipped,
			&i.OriginOnlyConfirmed,
			&i.WpmgrCdn,
			&i.SiteReportedText,
			&i.ApprovalSource,
			&i.ApprovalSiteMode,
			&i.ApprovalModeSource,
			&i.ApprovalModeVersion,
			&i.ApprovalSetterUserID,
			&i.ApprovalSetterSetAt,
			&i.ApprovalSessionID,
			&i.BaseChangeClass,
			&i.ChangeClass,
			&i.AskReason,
			&i.PolicyCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNamesByIDs = `-- name: ListUserNamesByIDs :many
SELECT id, name
FROM users
WHERE id = ANY($1::uuid[])
`

type ListUserNamesByIDsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// Display names for the setters and approvers recorded on rows the caller
// has already read in its own tenant. An id with no row is an account that
// no longer exists. Pass only ids read from the caller's tenant.
func (q *Queries) ListUserNamesByIDs(ctx context.Context, ids []uuid.UUID) ([]ListUserNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listUserNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserNamesByIDsRow
	for rows.Next() {
		var i ListUserNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSiteAILaunchNotices = `-- name: ReleaseSiteAILaunchNotices :execrows
UPDATE sites SET
    ai_mode_launch_emailed_at = NULL
WHERE tenant_id = $1
  AND id = ANY($2::uuid[])
  AND ai_mode_launch_emailed_at = $3::timestamptz
`

type ReleaseSiteAILaunchNoticesParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	SiteIds   []uuid.UUID `json:"site_ids"`
	ClaimedAt time.Time   `json:"claimed_at"`
}

// Undoes one claim after a failed send. It clears only the stamp that claim
// wrote (claimed_at is the stamp ClaimSiteAILaunchNotices returned), so it
// never clears a later claim or a notice that was sent.
func (q *Queries) ReleaseSiteAILaunchNotices(ctx context.Context, arg ReleaseSiteAILaunchNoticesParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseSiteAILaunchNotices, arg.TenantID, arg.SiteIds, arg.ClaimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAIConnectionAuto = `-- name: SetAIConnectionAuto :one
UPDATE mcp_grants SET
    ai_auto        = $1::text,
    ai_auto_set_by = CASE WHEN $1::text = 'site_setting'
                          THEN $2::uuid
                     END,
    ai_auto_set_at = now()
WHERE tenant_id = $3
  AND id = $4
  AND status = 'active'
  AND expires_at > now()
RETURNING id, ai_auto, ai_auto_set_by, ai_auto_set_at
`

type SetAIConnectionAutoParams struct {
	AiAuto   string      `json:"ai_auto"`
	SetBy    pgtype.UUID `json:"set_by"`
	TenantID uuid.UUID   `json:"tenant_id"`
	GrantID  uuid.UUID   `json:"grant_id"`
}

type SetAIConnectionAutoRow struct {
	ID          uuid.UUID          `json:"id"`
	AiAuto      string             `json:"ai_auto"`
	AiAutoSetBy pgtype.UUID        `json:"ai_auto_set_by"`
	AiAutoSetAt pgtype.Timestamptz `json:"ai_auto_set_at"`
}

// Sets the connection's switch. 'site_setting' records set_by, the signed-in
// person allowing it, even when the switch already reads 'site_setting'
// (that is how a connection is allowed again after the person who allowed it
// lost the access it needs). 'never' records no person. Only an active,
// unexpired connection is written. No row (pgx.ErrNoRows) means there is no
// such connection, or it is revoked or expired; GetAIConnectionAuto tells
// the two apart.
func (q *Queries) SetAIConnectionAuto(ctx context.Context, arg SetAIConnectionAutoParams) (SetAIConnectionAutoRow, error) {
	row := q.db.QueryRow(ctx, setAIConnectionAuto,
		arg.AiAuto,
		arg.SetBy,
		arg.TenantID,
		arg.GrantID,
	)
	var i SetAIConnectionAutoRow
	err := row.Scan(
		&i.ID,
		&i.AiAuto,
		&i.AiAutoSetBy,
		&i.AiAutoSetAt,
	)
	return i, err
}

const setSiteAIMode = `-- name: SetSiteAIMode :one
WITH changed AS (
    UPDATE sites AS s SET
        ai_mode         = $1::text,
        ai_mode_source  = $2::text,
        ai_mode_set_by  = $3::uuid,
        ai_mode_step_up = CASE
            WHEN (s.ai_mode, s.ai_mode_source, s.ai_mode_set_by)
                 IS DISTINCT FROM ($1::text, $2::text, $3::uuid)
            THEN $4::text
            ELSE s.ai_mode_step_up
        END,
        ai_mode_set_at = CASE
            WHEN (s.ai_mode, s.ai_mode_source, s.ai_mode_set_by)
                 IS DISTINCT FROM ($1::text, $2::text, $3::uuid)
            THEN now()
            ELSE s.ai_mode_set_at
        END,
        ai_mode_version = s.ai_mode_version + CASE
            WHEN (s.ai_mode, s.ai_mode_source, s.ai_mode_set_by)
                 IS DISTINCT FROM ($1::text, $2::text, $3::uuid)
            THEN 1
            ELSE 0
        END,
        updated_at = now()
    WHERE s.tenant_id = $5
      AND s.id = $6
      AND s.ai_mode_version = $7::bigint
    RETURNING s.id, s.ai_mode, s.ai_mode_source, s.ai_mode_set_by, s.ai_mode_set_at,
              s.ai_mode_version, s.ai_mode_step_up
)
SELECT true AS applied,
       c.id, c.ai_mode, c.ai_mode_source, c.ai_mode_set_by, c.ai_mode_set_at,
       c.ai_mode_version, c.ai_mode_step_up
FROM changed c
UNION ALL
SELECT false AS applied,
       s.id, s.ai_mode, s.ai_mode_source, s.ai_mode_set_by, s.ai_mode_set_at,
       s.ai_mode_version, s.ai_mode_step_up
FROM sites s
WHERE s.tenant_id = $5
  AND s.id = $6
  AND NOT EXISTS (SELECT 1 FROM changed)
`

type SetSiteAIModeParams struct {
	Mode            string      `json:"mode"`
	Source          string      `json:"source"`
	SetBy           pgtype.UUID `json:"set_by"`
	StepUp          *string     `json:"step_up"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	SiteID          uuid.UUID   `json:"site_id"`
	ExpectedVersion int64       `json:"expected_version"`
}

type SetSiteAIModeRow struct {
	Applied       bool               `json:"applied"`
	ID            uuid.UUID          `json:"id"`
	AiMode        string             `json:"ai_mode"`
	AiModeSource  string             `json:"ai_mode_source"`
	AiModeSetBy   pgtype.UUID        `json:"ai_mode_set_by"`
	AiModeSetAt   pgtype.Timestamptz `json:"ai_mode_set_at"`
	AiModeVersion int64              `json:"ai_mode_version"`
	AiModeStepUp  *string            `json:"ai_mode_step_up"`
}

// Sets the site's mode as a compare-and-set on ai_mode_version. Exactly one
// row comes back for a visible site:
//
//   - applied = true: the write was made. When the mode, its source or its
//     setter differ from what is stored, the version moves by one and the set
//     time and step-up are recorded; when all three are what is stored, the
//     row is left as it is (saving the setting that is already set changes
//     nothing).
//   - applied = false: expected_version is not the stored version. Nothing
//     was written, and the row carries the stored mode and version, which is
//     what a 409 stale_version answer reports.
//
// No row (pgx.ErrNoRows) means the site is not visible to the caller.
//
// The values an applied = false row carries are the ones this statement's
// snapshot saw. A caller that holds the tenant's policy lock, as every mode
// writer does, has no concurrent mode write to miss.
//
// set_by is the signed-in person recording the choice, or NULL for a
// lowering made without one (source 'tightened'). step_up is NULL except for
// Full auto. sites_ai_mode_guard refuses a combination a caller may not
// write.
func (q *Queries) SetSiteAIMode(ctx context.Context, arg SetSiteAIModeParams) (SetSiteAIModeRow, error) {
	row := q.db.QueryRow(ctx, setSiteAIMode,
		arg.Mode,
		arg.Source,
		arg.SetBy,
		arg.StepUp,
		arg.TenantID,
		arg.SiteID,
		arg.ExpectedVersion,
	)
	var i SetSiteAIModeRow
	err := row.Scan(
		&i.Applied,
		&i.ID,
		&i.AiMode,
		&i.AiModeSource,
		&i.AiModeSetBy,
		&i.AiModeSetAt,
		&i.AiModeVersion,
		&i.AiModeStepUp,
	)
	return i, err
}
