// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_reports.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimAdvanceReportSchedule = `-- name: ClaimAdvanceReportSchedule :one
UPDATE report_schedules
SET next_run_at = $1,
    last_run_at = now(),
    updated_at  = now()
WHERE id = $2
  AND tenant_id = $3
  AND enabled
  AND next_run_at <= now()
RETURNING id, tenant_id, client_id, enabled, cadence, send_day, send_hour, recipients, sections, intro_text, closing_text, powered_by_removed, next_run_at, last_run_at, created_at, updated_at
`

type ClaimAdvanceReportScheduleParams struct {
	NewNextRunAt pgtype.Timestamptz `json:"new_next_run_at"`
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
}

// Atomically advances next_run_at to @new_next_run_at for a schedule row,
// recording last_run_at = now(). Returns no row when the claim races
// (already claimed by another worker). Runs under InAgentTx.
func (q *Queries) ClaimAdvanceReportSchedule(ctx context.Context, arg ClaimAdvanceReportScheduleParams) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, claimAdvanceReportSchedule, arg.NewNextRunAt, arg.ID, arg.TenantID)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Enabled,
		&i.Cadence,
		&i.SendDay,
		&i.SendHour,
		&i.Recipients,
		&i.Sections,
		&i.IntroText,
		&i.ClosingText,
		&i.PoweredByRemoved,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeReport = `-- name: CompleteReport :one
UPDATE generated_reports
SET status        = 'completed',
    html_blob_key = $1,
    pdf_blob_key  = $2,
    data_snapshot = $3,
    completed_at  = now(),
    updated_at    = now()
WHERE id = $4 AND tenant_id = $5
RETURNING id, tenant_id, client_id, schedule_id, period_start, period_end, status, data_snapshot, html_blob_key, pdf_blob_key, error, created_at, updated_at, completed_at
`

type CompleteReportParams struct {
	HtmlBlobKey  string    `json:"html_blob_key"`
	PdfBlobKey   string    `json:"pdf_blob_key"`
	DataSnapshot []byte    `json:"data_snapshot"`
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CompleteReport(ctx context.Context, arg CompleteReportParams) (GeneratedReport, error) {
	row := q.db.QueryRow(ctx, completeReport,
		arg.HtmlBlobKey,
		arg.PdfBlobKey,
		arg.DataSnapshot,
		arg.ID,
		arg.TenantID,
	)
	var i GeneratedReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ScheduleID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.DataSnapshot,
		&i.HtmlBlobKey,
		&i.PdfBlobKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one

INSERT INTO generated_reports (
    tenant_id, client_id, schedule_id, period_start, period_end, status
) VALUES (
    $1, $2, $3, $4, $5, 'pending'
)
RETURNING id, tenant_id, client_id, schedule_id, period_start, period_end, status, data_snapshot, html_blob_key, pdf_blob_key, error, created_at, updated_at, completed_at
`

type CreateReportParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	ClientID    uuid.UUID   `json:"client_id"`
	ScheduleID  pgtype.UUID `json:"schedule_id"`
	PeriodStart time.Time   `json:"period_start"`
	PeriodEnd   time.Time   `json:"period_end"`
}

// ---------------------------------------------------------------------------
// generated_reports — one row per rendered report
// ---------------------------------------------------------------------------
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (GeneratedReport, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.TenantID,
		arg.ClientID,
		arg.ScheduleID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i GeneratedReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ScheduleID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.DataSnapshot,
		&i.HtmlBlobKey,
		&i.PdfBlobKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :execrows
DELETE FROM generated_reports
WHERE id = $1 AND tenant_id = $2 AND client_id = $3
`

type DeleteReportParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) DeleteReport(ctx context.Context, arg DeleteReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReport, arg.ID, arg.TenantID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failReport = `-- name: FailReport :one
UPDATE generated_reports
SET status     = 'failed',
    error      = $1,
    updated_at = now()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, client_id, schedule_id, period_start, period_end, status, data_snapshot, html_blob_key, pdf_blob_key, error, created_at, updated_at, completed_at
`

type FailReportParams struct {
	Error    string    `json:"error"`
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) FailReport(ctx context.Context, arg FailReportParams) (GeneratedReport, error) {
	row := q.db.QueryRow(ctx, failReport, arg.Error, arg.ID, arg.TenantID)
	var i GeneratedReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ScheduleID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.DataSnapshot,
		&i.HtmlBlobKey,
		&i.PdfBlobKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getBackupReportStats = `-- name: GetBackupReportStats :one

SELECT
    COUNT(*)::bigint                    AS completed_count,
    COALESCE(SUM(total_size), 0)::bigint AS total_bytes,
    MAX(finished_at)                    AS last_completed_at
FROM backup_snapshots
WHERE tenant_id  = $1
  AND site_id    = $2
  AND status     = 'completed'
  AND finished_at >= $3
  AND finished_at  < $4
`

type GetBackupReportStatsParams struct {
	TenantID uuid.UUID          `json:"tenant_id"`
	SiteID   uuid.UUID          `json:"site_id"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type GetBackupReportStatsRow struct {
	CompletedCount  int64       `json:"completed_count"`
	TotalBytes      int64       `json:"total_bytes"`
	LastCompletedAt interface{} `json:"last_completed_at"`
}

// ---------------------------------------------------------------------------
// Per-section data queries for the aggregator
// ---------------------------------------------------------------------------
// Backup section: completed snapshots in [from, to) for a site.
func (q *Queries) GetBackupReportStats(ctx context.Context, arg GetBackupReportStatsParams) (GetBackupReportStatsRow, error) {
	row := q.db.QueryRow(ctx, getBackupReportStats,
		arg.TenantID,
		arg.SiteID,
		arg.FromTime,
		arg.ToTime,
	)
	var i GetBackupReportStatsRow
	err := row.Scan(&i.CompletedCount, &i.TotalBytes, &i.LastCompletedAt)
	return i, err
}

const getClientWithTimezone = `-- name: GetClientWithTimezone :one
SELECT id, tenant_id, name, contact_email, company, phone, notes, color, logo_url, archived_at, created_at, updated_at, timezone FROM clients WHERE id = $1 AND tenant_id = $2
`

type GetClientWithTimezoneParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetClientWithTimezone(ctx context.Context, arg GetClientWithTimezoneParams) (Client, error) {
	row := q.db.QueryRow(ctx, getClientWithTimezone, arg.ID, arg.TenantID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactEmail,
		&i.Company,
		&i.Phone,
		&i.Notes,
		&i.Color,
		&i.LogoUrl,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
	)
	return i, err
}

const getCompletedReportForPortal = `-- name: GetCompletedReportForPortal :one
SELECT id, tenant_id, client_id, period_start, period_end,
       status, html_blob_key, pdf_blob_key, created_at, completed_at
FROM generated_reports
WHERE id        = $1
  AND tenant_id = $2
  AND client_id = ANY($3::uuid[])
  AND status    = 'completed'
`

type GetCompletedReportForPortalParams struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	ClientIds []uuid.UUID `json:"client_ids"`
}

type GetCompletedReportForPortalRow struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	ClientID    uuid.UUID          `json:"client_id"`
	PeriodStart time.Time          `json:"period_start"`
	PeriodEnd   time.Time          `json:"period_end"`
	Status      string             `json:"status"`
	HtmlBlobKey string             `json:"html_blob_key"`
	PdfBlobKey  string             `json:"pdf_blob_key"`
	CreatedAt   time.Time          `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

// Load a single completed report checking client_id membership in the caller's
// client list. Returns ErrNoRows when the report is not found, not completed,
// or the client_id is not in the provided list (cross-client IDOR guard).
func (q *Queries) GetCompletedReportForPortal(ctx context.Context, arg GetCompletedReportForPortalParams) (GetCompletedReportForPortalRow, error) {
	row := q.db.QueryRow(ctx, getCompletedReportForPortal, arg.ID, arg.TenantID, arg.ClientIds)
	var i GetCompletedReportForPortalRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.HtmlBlobKey,
		&i.PdfBlobKey,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, tenant_id, client_id, schedule_id, period_start, period_end, status, data_snapshot, html_blob_key, pdf_blob_key, error, created_at, updated_at, completed_at FROM generated_reports
WHERE id = $1 AND tenant_id = $2 AND client_id = $3
`

type GetReportParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) GetReport(ctx context.Context, arg GetReportParams) (GeneratedReport, error) {
	row := q.db.QueryRow(ctx, getReport, arg.ID, arg.TenantID, arg.ClientID)
	var i GeneratedReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ScheduleID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.DataSnapshot,
		&i.HtmlBlobKey,
		&i.PdfBlobKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getReportSchedule = `-- name: GetReportSchedule :one

SELECT id, tenant_id, client_id, enabled, cadence, send_day, send_hour, recipients, sections, intro_text, closing_text, powered_by_removed, next_run_at, last_run_at, created_at, updated_at FROM report_schedules
WHERE client_id = $1 AND tenant_id = $2
`

type GetReportScheduleParams struct {
	ClientID uuid.UUID `json:"client_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// ---------------------------------------------------------------------------
// report_schedules — singleton schedule per client
// ---------------------------------------------------------------------------
func (q *Queries) GetReportSchedule(ctx context.Context, arg GetReportScheduleParams) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, getReportSchedule, arg.ClientID, arg.TenantID)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Enabled,
		&i.Cadence,
		&i.SendDay,
		&i.SendHour,
		&i.Recipients,
		&i.Sections,
		&i.IntroText,
		&i.ClosingText,
		&i.PoweredByRemoved,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantName = `-- name: GetTenantName :one


SELECT name FROM tenants WHERE id = $1
`

// Client Reports queries (M64 — White-label client reports Phase 2).
// All queries are tenant-scoped both explicitly (tenant_id in WHERE/VALUES)
// and by RLS. The repo wraps each call in the appropriate tx helper
// (InTenantTx for operator path, InAgentTx for the due-scanner / worker).
// updated_at is set by now() in mutations (project convention, no trigger).
// ---------------------------------------------------------------------------
// Shared tenant name lookup (used by the aggregator for agency branding).
// ---------------------------------------------------------------------------
func (q *Queries) GetTenantName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTenantName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUpdateReportStats = `-- name: GetUpdateReportStats :many
SELECT
    target_type,
    COUNT(*) FILTER (WHERE status = 'succeeded')               AS succeeded,
    COUNT(*) FILTER (WHERE status IN ('failed','rolled_back')) AS failed
FROM update_tasks
WHERE tenant_id  = $1
  AND site_id    = $2
  AND finished_at >= $3
  AND finished_at  < $4
GROUP BY target_type
`

type GetUpdateReportStatsParams struct {
	TenantID uuid.UUID          `json:"tenant_id"`
	SiteID   uuid.UUID          `json:"site_id"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type GetUpdateReportStatsRow struct {
	TargetType string `json:"target_type"`
	Succeeded  int64  `json:"succeeded"`
	Failed     int64  `json:"failed"`
}

// Update section: succeeded/failed tasks grouped by target_type in [from, to).
func (q *Queries) GetUpdateReportStats(ctx context.Context, arg GetUpdateReportStatsParams) ([]GetUpdateReportStatsRow, error) {
	rows, err := q.db.Query(ctx, getUpdateReportStats,
		arg.TenantID,
		arg.SiteID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpdateReportStatsRow
	for rows.Next() {
		var i GetUpdateReportStatsRow
		if err := rows.Scan(&i.TargetType, &i.Succeeded, &i.Failed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedReportsForClients = `-- name: ListCompletedReportsForClients :many

SELECT id, tenant_id, client_id, period_start, period_end,
       status, created_at, completed_at
FROM generated_reports
WHERE tenant_id = $1
  AND client_id = ANY($2::uuid[])
  AND status    = 'completed'
  AND (
        $3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::uuid)
      )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListCompletedReportsForClientsParams struct {
	TenantID        uuid.UUID          `json:"tenant_id"`
	ClientIds       []uuid.UUID        `json:"client_ids"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
	RowLimit        int32              `json:"row_limit"`
}

type ListCompletedReportsForClientsRow struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	ClientID    uuid.UUID          `json:"client_id"`
	PeriodStart time.Time          `json:"period_start"`
	PeriodEnd   time.Time          `json:"period_end"`
	Status      string             `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

// ---------------------------------------------------------------------------
// m66 — Portal report queries
// ---------------------------------------------------------------------------
// Portal report list: completed reports for a set of client IDs. The
// client_id = ANY(@client_ids) predicate is the cross-client isolation gate
// (generated_reports has no site_scope restrictive policy). Only
// status='completed' rows are returned — the portal must not surface
// pending/generating/failed states (locked decision, section 8).
// Keyset cursor: composite (created_at, id) predicate matches ListReports.
func (q *Queries) ListCompletedReportsForClients(ctx context.Context, arg ListCompletedReportsForClientsParams) ([]ListCompletedReportsForClientsRow, error) {
	rows, err := q.db.Query(ctx, listCompletedReportsForClients,
		arg.TenantID,
		arg.ClientIds,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedReportsForClientsRow
	for rows.Next() {
		var i ListCompletedReportsForClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueReportSchedules = `-- name: ListDueReportSchedules :many
SELECT
    rs.id, rs.tenant_id, rs.client_id, rs.enabled, rs.cadence, rs.send_day, rs.send_hour, rs.recipients, rs.sections, rs.intro_text, rs.closing_text, rs.powered_by_removed, rs.next_run_at, rs.last_run_at, rs.created_at, rs.updated_at,
    c.name          AS client_name,
    c.contact_email AS client_contact_email,
    c.timezone      AS client_timezone
FROM report_schedules rs
JOIN clients c ON c.id = rs.client_id AND c.tenant_id = rs.tenant_id
WHERE rs.enabled
  AND rs.next_run_at <= now()
ORDER BY rs.next_run_at ASC
LIMIT $1
`

type ListDueReportSchedulesRow struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	ClientID           uuid.UUID          `json:"client_id"`
	Enabled            bool               `json:"enabled"`
	Cadence            string             `json:"cadence"`
	SendDay            int32              `json:"send_day"`
	SendHour           int32              `json:"send_hour"`
	Recipients         []byte             `json:"recipients"`
	Sections           []byte             `json:"sections"`
	IntroText          string             `json:"intro_text"`
	ClosingText        string             `json:"closing_text"`
	PoweredByRemoved   bool               `json:"powered_by_removed"`
	NextRunAt          pgtype.Timestamptz `json:"next_run_at"`
	LastRunAt          pgtype.Timestamptz `json:"last_run_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	ClientName         string             `json:"client_name"`
	ClientContactEmail *string            `json:"client_contact_email"`
	ClientTimezone     string             `json:"client_timezone"`
}

// Returns up to @limit enabled schedules where next_run_at <= now(), JOINed
// with the client for timezone/name/contact_email. Runs under InAgentTx.
func (q *Queries) ListDueReportSchedules(ctx context.Context, rowLimit int32) ([]ListDueReportSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listDueReportSchedules, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueReportSchedulesRow
	for rows.Next() {
		var i ListDueReportSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.Enabled,
			&i.Cadence,
			&i.SendDay,
			&i.SendHour,
			&i.Recipients,
			&i.Sections,
			&i.IntroText,
			&i.ClosingText,
			&i.PoweredByRemoved,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientName,
			&i.ClientContactEmail,
			&i.ClientTimezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReports = `-- name: ListReports :many
SELECT id, tenant_id, client_id, schedule_id, period_start, period_end, status, data_snapshot, html_blob_key, pdf_blob_key, error, created_at, updated_at, completed_at FROM generated_reports
WHERE tenant_id  = $1
  AND client_id  = $2
  AND (
        $3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::uuid)
      )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListReportsParams struct {
	TenantID        uuid.UUID          `json:"tenant_id"`
	ClientID        uuid.UUID          `json:"client_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
	RowLimit        int32              `json:"row_limit"`
}

// Keyset cursor pagination: composite predicate (created_at, id) < (cursor_at, cursor_id)
// because batch inserts can share created_at and a bare compare skips co-timestamped rows
// (standing keyset-cursor-composite rule).
func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]GeneratedReport, error) {
	rows, err := q.db.Query(ctx, listReports,
		arg.TenantID,
		arg.ClientID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedReport
	for rows.Next() {
		var i GeneratedReport
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.ScheduleID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.DataSnapshot,
			&i.HtmlBlobKey,
			&i.PdfBlobKey,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportGenerating = `-- name: MarkReportGenerating :one
UPDATE generated_reports
SET status = 'generating',
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, client_id, schedule_id, period_start, period_end, status, data_snapshot, html_blob_key, pdf_blob_key, error, created_at, updated_at, completed_at
`

type MarkReportGeneratingParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) MarkReportGenerating(ctx context.Context, arg MarkReportGeneratingParams) (GeneratedReport, error) {
	row := q.db.QueryRow(ctx, markReportGenerating, arg.ID, arg.TenantID)
	var i GeneratedReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ScheduleID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.DataSnapshot,
		&i.HtmlBlobKey,
		&i.PdfBlobKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateClientTimezone = `-- name: UpdateClientTimezone :one

UPDATE clients
SET timezone   = $1,
    updated_at = now()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, name, contact_email, company, phone, notes, color, logo_url, archived_at, created_at, updated_at, timezone
`

type UpdateClientTimezoneParams struct {
	Timezone string    `json:"timezone"`
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// ---------------------------------------------------------------------------
// clients.timezone (D-0: client-level timezone field, decision 6)
// ---------------------------------------------------------------------------
func (q *Queries) UpdateClientTimezone(ctx context.Context, arg UpdateClientTimezoneParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientTimezone, arg.Timezone, arg.ID, arg.TenantID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactEmail,
		&i.Company,
		&i.Phone,
		&i.Notes,
		&i.Color,
		&i.LogoUrl,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
	)
	return i, err
}

const upsertReportSchedule = `-- name: UpsertReportSchedule :one
INSERT INTO report_schedules (
    tenant_id, client_id, enabled, cadence, send_day, send_hour,
    recipients, sections, intro_text, closing_text, powered_by_removed,
    next_run_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, now()
)
ON CONFLICT (client_id) DO UPDATE
    SET enabled            = EXCLUDED.enabled,
        cadence            = EXCLUDED.cadence,
        send_day           = EXCLUDED.send_day,
        send_hour          = EXCLUDED.send_hour,
        recipients         = EXCLUDED.recipients,
        sections           = EXCLUDED.sections,
        intro_text         = EXCLUDED.intro_text,
        closing_text       = EXCLUDED.closing_text,
        powered_by_removed = EXCLUDED.powered_by_removed,
        next_run_at        = EXCLUDED.next_run_at,
        updated_at         = now()
RETURNING id, tenant_id, client_id, enabled, cadence, send_day, send_hour, recipients, sections, intro_text, closing_text, powered_by_removed, next_run_at, last_run_at, created_at, updated_at
`

type UpsertReportScheduleParams struct {
	TenantID         uuid.UUID          `json:"tenant_id"`
	ClientID         uuid.UUID          `json:"client_id"`
	Enabled          bool               `json:"enabled"`
	Cadence          string             `json:"cadence"`
	SendDay          int32              `json:"send_day"`
	SendHour         int32              `json:"send_hour"`
	Recipients       []byte             `json:"recipients"`
	Sections         []byte             `json:"sections"`
	IntroText        string             `json:"intro_text"`
	ClosingText      string             `json:"closing_text"`
	PoweredByRemoved bool               `json:"powered_by_removed"`
	NextRunAt        pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpsertReportSchedule(ctx context.Context, arg UpsertReportScheduleParams) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, upsertReportSchedule,
		arg.TenantID,
		arg.ClientID,
		arg.Enabled,
		arg.Cadence,
		arg.SendDay,
		arg.SendHour,
		arg.Recipients,
		arg.Sections,
		arg.IntroText,
		arg.ClosingText,
		arg.PoweredByRemoved,
		arg.NextRunAt,
	)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Enabled,
		&i.Cadence,
		&i.SendDay,
		&i.SendHour,
		&i.Recipients,
		&i.Sections,
		&i.IntroText,
		&i.ClosingText,
		&i.PoweredByRemoved,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
