// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content_inventory.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminUpsertContentIntegration = `-- name: AdminUpsertContentIntegration :one
SELECT integration_id, display_name, enabled, status, descriptor, abilities, min_version, max_tested_version, min_wp_version, integration_entry_sha256, created_at, updated_at, updated_by_user_id FROM admin_upsert_content_integration(
    $1::uuid,
    $2::text,
    $3::text,
    $4::boolean,
    $5::text,
    $6::jsonb,
    $7::jsonb,
    $8::text,
    $9::text,
    $10::text,
    $11::text
)
`

type AdminUpsertContentIntegrationParams struct {
	ActorUserID            uuid.UUID `json:"actor_user_id"`
	IntegrationID          string    `json:"integration_id"`
	DisplayName            string    `json:"display_name"`
	Enabled                bool      `json:"enabled"`
	Status                 string    `json:"status"`
	Descriptor             []byte    `json:"descriptor"`
	Abilities              []byte    `json:"abilities"`
	MinVersion             *string   `json:"min_version"`
	MaxTestedVersion       *string   `json:"max_tested_version"`
	MinWpVersion           *string   `json:"min_wp_version"`
	IntegrationEntrySha256 *string   `json:"integration_entry_sha256"`
}

// The ONLY write path. Call it only behind requireSuperadmin. The function
// refuses (SQLSTATE 42501) unless actor_user_id names a superadmin, and it
// writes a content_integrations_audit row in the same statement.
func (q *Queries) AdminUpsertContentIntegration(ctx context.Context, arg AdminUpsertContentIntegrationParams) (ContentIntegration, error) {
	row := q.db.QueryRow(ctx, adminUpsertContentIntegration,
		arg.ActorUserID,
		arg.IntegrationID,
		arg.DisplayName,
		arg.Enabled,
		arg.Status,
		arg.Descriptor,
		arg.Abilities,
		arg.MinVersion,
		arg.MaxTestedVersion,
		arg.MinWpVersion,
		arg.IntegrationEntrySha256,
	)
	var i ContentIntegration
	err := row.Scan(
		&i.IntegrationID,
		&i.DisplayName,
		&i.Enabled,
		&i.Status,
		&i.Descriptor,
		&i.Abilities,
		&i.MinVersion,
		&i.MaxTestedVersion,
		&i.MinWpVersion,
		&i.IntegrationEntrySha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
	)
	return i, err
}

const deleteStaleSiteContentInventory = `-- name: DeleteStaleSiteContentInventory :execrows
DELETE FROM site_content_inventory
WHERE tenant_id = $1::uuid
  AND site_id = $2::uuid
  AND checked_at < $3::timestamptz
`

type DeleteStaleSiteContentInventoryParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	SiteID    uuid.UUID `json:"site_id"`
	CheckedAt time.Time `json:"checked_at"`
}

// The second half of a replace: drops the site's rows the latest refresh did
// not report. Pass the checked_at the upsert used.
func (q *Queries) DeleteStaleSiteContentInventory(ctx context.Context, arg DeleteStaleSiteContentInventoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleSiteContentInventory, arg.TenantID, arg.SiteID, arg.CheckedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fleetContentShareByBuilder = `-- name: FleetContentShareByBuilder :many
SELECT owner_integration_id::text AS owner_integration_id,
       owner_version,
       count(*)::bigint AS pages,
       count(DISTINCT site_id)::bigint AS sites
FROM site_content_inventory
WHERE owner_integration_id IS NOT NULL
GROUP BY owner_integration_id, owner_version
ORDER BY owner_integration_id, owner_version NULLS FIRST
`

type FleetContentShareByBuilderRow struct {
	OwnerIntegrationID string  `json:"owner_integration_id"`
	OwnerVersion       *string `json:"owner_version"`
	Pages              int64   `json:"pages"`
	Sites              int64   `json:"sites"`
}

// Owner fleet report: builder pages per builder and version, across every
// tenant. Run under pool.InAgentTx.
func (q *Queries) FleetContentShareByBuilder(ctx context.Context) ([]FleetContentShareByBuilderRow, error) {
	rows, err := q.db.Query(ctx, fleetContentShareByBuilder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FleetContentShareByBuilderRow
	for rows.Next() {
		var i FleetContentShareByBuilderRow
		if err := rows.Scan(
			&i.OwnerIntegrationID,
			&i.OwnerVersion,
			&i.Pages,
			&i.Sites,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fleetContentShareByVerdict = `-- name: FleetContentShareByVerdict :many
SELECT verdict, route_number,
       count(*)::bigint AS pages,
       count(DISTINCT site_id)::bigint AS sites
FROM site_content_inventory
GROUP BY verdict, route_number
ORDER BY verdict, route_number
`

type FleetContentShareByVerdictRow struct {
	Verdict     string `json:"verdict"`
	RouteNumber int16  `json:"route_number"`
	Pages       int64  `json:"pages"`
	Sites       int64  `json:"sites"`
}

// Owner fleet report: pages and sites per verdict and route, across every
// tenant. Run under pool.InAgentTx (site_content_inventory_agent, FOR SELECT).
func (q *Queries) FleetContentShareByVerdict(ctx context.Context) ([]FleetContentShareByVerdictRow, error) {
	rows, err := q.db.Query(ctx, fleetContentShareByVerdict)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FleetContentShareByVerdictRow
	for rows.Next() {
		var i FleetContentShareByVerdictRow
		if err := rows.Scan(
			&i.Verdict,
			&i.RouteNumber,
			&i.Pages,
			&i.Sites,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentIntegrationAudit = `-- name: ListContentIntegrationAudit :many
SELECT id, integration_id, action, actor_user_id, before_sha256, after_sha256, before_enabled, after_enabled, at FROM content_integrations_audit
WHERE integration_id = $1::text
ORDER BY id DESC
LIMIT $2::int
`

type ListContentIntegrationAuditParams struct {
	IntegrationID string `json:"integration_id"`
	RowLimit      int32  `json:"row_limit"`
}

// Newest first, for the admin screen.
func (q *Queries) ListContentIntegrationAudit(ctx context.Context, arg ListContentIntegrationAuditParams) ([]ContentIntegrationsAudit, error) {
	rows, err := q.db.Query(ctx, listContentIntegrationAudit, arg.IntegrationID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentIntegrationsAudit
	for rows.Next() {
		var i ContentIntegrationsAudit
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Action,
			&i.ActorUserID,
			&i.BeforeSha256,
			&i.AfterSha256,
			&i.BeforeEnabled,
			&i.AfterEnabled,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentIntegrations = `-- name: ListContentIntegrations :many

SELECT integration_id, display_name, enabled, status, descriptor, abilities, min_version, max_tested_version, min_wp_version, integration_entry_sha256, created_at, updated_at, updated_by_user_id FROM content_integrations
ORDER BY integration_id
`

// m153: content_integrations (global allowlist) and site_content_inventory
// (per-site probe results). See the migration header for the grant model.
// Every allowlist row, for the probe dispatch and the admin screen. Readable
// in any transaction: the table is global and its one policy is FOR SELECT
// USING (true).
func (q *Queries) ListContentIntegrations(ctx context.Context) ([]ContentIntegration, error) {
	rows, err := q.db.Query(ctx, listContentIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentIntegration
	for rows.Next() {
		var i ContentIntegration
		if err := rows.Scan(
			&i.IntegrationID,
			&i.DisplayName,
			&i.Enabled,
			&i.Status,
			&i.Descriptor,
			&i.Abilities,
			&i.MinVersion,
			&i.MaxTestedVersion,
			&i.MinWpVersion,
			&i.IntegrationEntrySha256,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledContentIntegrations = `-- name: ListEnabledContentIntegrations :many
SELECT integration_id, display_name, enabled, status, descriptor, abilities, min_version, max_tested_version, min_wp_version, integration_entry_sha256, created_at, updated_at, updated_by_user_id FROM content_integrations
WHERE enabled
ORDER BY integration_id
`

// The rows the probe is sent. A disabled row is the kill switch.
func (q *Queries) ListEnabledContentIntegrations(ctx context.Context) ([]ContentIntegration, error) {
	rows, err := q.db.Query(ctx, listEnabledContentIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentIntegration
	for rows.Next() {
		var i ContentIntegration
		if err := rows.Scan(
			&i.IntegrationID,
			&i.DisplayName,
			&i.Enabled,
			&i.Status,
			&i.Descriptor,
			&i.Abilities,
			&i.MinVersion,
			&i.MaxTestedVersion,
			&i.MinWpVersion,
			&i.IntegrationEntrySha256,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteContentInventory = `-- name: ListSiteContentInventory :many
SELECT tenant_id, site_id, post_id, post_type, post_status, verdict, route_number, route_reason, owner_integration_id, owner_display_name, owner_version, fingerprint, title, checked_at FROM site_content_inventory
WHERE tenant_id = $1::uuid
  AND site_id = $2::uuid
  AND post_id > $3::bigint
  AND (
    $4::text IS NULL
    OR ($4::text = 'classic'
        AND owner_integration_id IS NULL)
    OR owner_integration_id = $4::text
  )
ORDER BY post_id
LIMIT $5::int
`

type ListSiteContentInventoryParams struct {
	TenantID           uuid.UUID `json:"tenant_id"`
	SiteID             uuid.UUID `json:"site_id"`
	AfterPostID        int64     `json:"after_post_id"`
	OwnerIntegrationID *string   `json:"owner_integration_id"`
	RowLimit           int32     `json:"row_limit"`
}

// One page of a site's inventory, keyset-paged on post_id ascending. Pass
// after_post_id = 0 for the first page. owner_integration_id filters by
// editor: NULL for every row, 'classic' for rows no builder owns, or an
// integration id.
func (q *Queries) ListSiteContentInventory(ctx context.Context, arg ListSiteContentInventoryParams) ([]SiteContentInventory, error) {
	rows, err := q.db.Query(ctx, listSiteContentInventory,
		arg.TenantID,
		arg.SiteID,
		arg.AfterPostID,
		arg.OwnerIntegrationID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteContentInventory
	for rows.Next() {
		var i SiteContentInventory
		if err := rows.Scan(
			&i.TenantID,
			&i.SiteID,
			&i.PostID,
			&i.PostType,
			&i.PostStatus,
			&i.Verdict,
			&i.RouteNumber,
			&i.RouteReason,
			&i.OwnerIntegrationID,
			&i.OwnerDisplayName,
			&i.OwnerVersion,
			&i.Fingerprint,
			&i.Title,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSiteContentInventory = `-- name: UpsertSiteContentInventory :execrows
INSERT INTO site_content_inventory (
    tenant_id, site_id, post_id, post_type, post_status, verdict,
    route_number, route_reason, owner_integration_id, owner_display_name,
    owner_version, fingerprint, title, checked_at
)
SELECT
    $1::uuid,
    $2::uuid,
    r.post_id, r.post_type, r.post_status, r.verdict,
    r.route_number, r.route_reason,
    nullif(r.owner_integration_id, ''),
    nullif(r.owner_display_name, ''),
    nullif(r.owner_version, ''),
    nullif(r.fingerprint, ''),
    nullif(r.title, ''),
    $3::timestamptz
FROM (
    -- Parallel unnests in one select list zip element-wise.
    SELECT
        unnest($4::bigint[]) AS post_id,
        unnest($5::text[]) AS post_type,
        unnest($6::text[]) AS post_status,
        unnest($7::text[]) AS verdict,
        unnest($8::smallint[]) AS route_number,
        unnest($9::text[]) AS route_reason,
        unnest($10::text[]) AS owner_integration_id,
        unnest($11::text[]) AS owner_display_name,
        unnest($12::text[]) AS owner_version,
        unnest($13::text[]) AS fingerprint,
        unnest($14::text[]) AS title
) AS r
ON CONFLICT (site_id, post_id) DO UPDATE SET
    post_type = EXCLUDED.post_type,
    post_status = EXCLUDED.post_status,
    verdict = EXCLUDED.verdict,
    route_number = EXCLUDED.route_number,
    route_reason = EXCLUDED.route_reason,
    owner_integration_id = EXCLUDED.owner_integration_id,
    owner_display_name = EXCLUDED.owner_display_name,
    owner_version = EXCLUDED.owner_version,
    fingerprint = EXCLUDED.fingerprint,
    title = EXCLUDED.title,
    checked_at = EXCLUDED.checked_at
`

type UpsertSiteContentInventoryParams struct {
	TenantID            uuid.UUID `json:"tenant_id"`
	SiteID              uuid.UUID `json:"site_id"`
	CheckedAt           time.Time `json:"checked_at"`
	PostIds             []int64   `json:"post_ids"`
	PostTypes           []string  `json:"post_types"`
	PostStatuses        []string  `json:"post_statuses"`
	Verdicts            []string  `json:"verdicts"`
	RouteNumbers        []int16   `json:"route_numbers"`
	RouteReasons        []string  `json:"route_reasons"`
	OwnerIntegrationIds []string  `json:"owner_integration_ids"`
	OwnerDisplayNames   []string  `json:"owner_display_names"`
	OwnerVersions       []string  `json:"owner_versions"`
	Fingerprints        []string  `json:"fingerprints"`
	Titles              []string  `json:"titles"`
}

// One refresh's rows for ONE site, in one statement. Run in the site's tenant
// transaction, then DeleteStaleSiteContentInventory with the same checked_at
// in the same transaction: together they replace the site's inventory.
// The arrays are parallel, one element per post. Nullable text columns take
// ” for NULL (pgx cannot carry a NULL element in []string).
func (q *Queries) UpsertSiteContentInventory(ctx context.Context, arg UpsertSiteContentInventoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertSiteContentInventory,
		arg.TenantID,
		arg.SiteID,
		arg.CheckedAt,
		arg.PostIds,
		arg.PostTypes,
		arg.PostStatuses,
		arg.Verdicts,
		arg.RouteNumbers,
		arg.RouteReasons,
		arg.OwnerIntegrationIds,
		arg.OwnerDisplayNames,
		arg.OwnerVersions,
		arg.Fingerprints,
		arg.Titles,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
