// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = now(), attempts = attempts + 1
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, token_hash, expires_at, used_at, attempts, requested_ip, created_at
`

// Atomically consume a token: mark it used IFF it exists, is unused, and is not
// expired. Returns the row (incl. user_id) only when the consume succeeded, so
// the caller cannot distinguish wrong/expired/used by anything but "no row".
func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Attempts,
		&i.RequestedIp,
		&i.CreatedAt,
	)
	return i, err
}

const insertPasswordResetToken = `-- name: InsertPasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at, requested_ip)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, expires_at, used_at, attempts, requested_ip, created_at
`

type InsertPasswordResetTokenParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	TokenHash   []byte      `json:"token_hash"`
	ExpiresAt   time.Time   `json:"expires_at"`
	RequestedIp *netip.Addr `json:"requested_ip"`
}

// Record a new reset token. Run under Pool.InAgentTx (app.agent='on').
func (q *Queries) InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, insertPasswordResetToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.RequestedIp,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Attempts,
		&i.RequestedIp,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUserPasswordResetTokens = `-- name: InvalidateUserPasswordResetTokens :exec
UPDATE password_reset_tokens
SET used_at = now()
WHERE user_id = $1 AND used_at IS NULL
`

// Burn all outstanding reset tokens for a user (after a successful reset/change).
func (q *Queries) InvalidateUserPasswordResetTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateUserPasswordResetTokens, userID)
	return err
}
