// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Records that a scheduled backup was enqueued and advances next_run_at. The
	// scheduler resolves the tenant from the due-row first, then advances within
	// that tenant's scope (the per-tenant isolation policy permits the UPDATE).
	AdvanceBackupScheduleRun(ctx context.Context, arg AdvanceBackupScheduleRunParams) (BackupSchedule, error)
	// Re-enrollment: rotate the agent key and mark the site active/enrolled again.
	AttachAgentToSite(ctx context.Context, arg AttachAgentToSiteParams) (Site, error)
	CompleteBackupSnapshot(ctx context.Context, arg CompleteBackupSnapshotParams) (BackupSnapshot, error)
	// Consume path (app.agent). Atomic single-shot UPDATE that wins exactly once
	// across concurrent agent callbacks: the (consumed_at IS NULL) predicate makes
	// the second consume a 0-row update; RETURNING tells the caller it lost. The
	// site_id check binds the consume to the agent's verified identity (anti
	// cross-tenant replay).
	ConsumeAutologinToken(ctx context.Context, arg ConsumeAutologinTokenParams) (ConsumeAutologinTokenRow, error)
	// Enroll path (app.enroll GUC): mark consumed only if still unconsumed.
	ConsumePairingCode(ctx context.Context, id uuid.UUID) (int64, error)
	// Best-effort per-tenant in-flight task count, used by the parallelism guard so
	// one tenant cannot saturate the worker pool. Runs in the tenant's RLS scope.
	CountRunningTasksForTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// Counts tasks not yet in a terminal state, used to decide when a run completes.
	CountUnfinishedTasksForRun(ctx context.Context, arg CountUnfinishedTasksForRunParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// M4 backup queries. Every statement is tenant-scoped both explicitly
	// (tenant_id in the WHERE/VALUES) and by RLS (the app.tenant_id policy).
	// ---------------------------------------------------------------------------
	// backup_snapshots
	// ---------------------------------------------------------------------------
	CreateBackupSnapshot(ctx context.Context, arg CreateBackupSnapshotParams) (BackupSnapshot, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	// ---------------------------------------------------------------------------
	// backup_manifest_entries
	// ---------------------------------------------------------------------------
	CreateManifestEntry(ctx context.Context, arg CreateManifestEntryParams) (BackupManifestEntry, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	// Tenant-scoped (app.tenant_id) — operator generates a code for the tenant.
	CreatePairingCode(ctx context.Context, arg CreatePairingCodeParams) (PairingCode, error)
	// Upsert on (site_id, user_id): if a share already exists for this (site, user)
	// pair, update the role, granted_by and expires_at in place.
	CreateShare(ctx context.Context, arg CreateShareParams) (SiteShare, error)
	// tenant_id is supplied explicitly for defense-in-depth; RLS additionally
	// enforces that it matches the current app.tenant_id setting.
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	CreateSiteForEnroll(ctx context.Context, arg CreateSiteForEnrollParams) (Site, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// M3 bulk-update queries. Every statement is tenant-scoped both explicitly
	// (tenant_id in the WHERE/VALUES) and by RLS (the app.tenant_id policy).
	// tenant_id is supplied explicitly for defense-in-depth; RLS additionally
	// enforces it matches the current app.tenant_id setting.
	CreateUpdateRun(ctx context.Context, arg CreateUpdateRunParams) (UpdateRun, error)
	CreateUpdateTask(ctx context.Context, arg CreateUpdateTaskParams) (UpdateTask, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Decrements but never below zero. Returns the new refcount + s3_key so the GC
	// job can delete the object from storage when the count reaches zero.
	DecrementChunkRefcount(ctx context.Context, arg DecrementChunkRefcountParams) (DecrementChunkRefcountRow, error)
	DeleteBackupSnapshot(ctx context.Context, arg DeleteBackupSnapshotParams) (int64, error)
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error)
	// Deletes a chunk row only if its refcount is zero (the object was already
	// removed from storage by the GC job). Tenant-scoped.
	DeleteOrphanChunk(ctx context.Context, arg DeleteOrphanChunkParams) (int64, error)
	DeleteShare(ctx context.Context, arg DeleteShareParams) (int64, error)
	DeleteSite(ctx context.Context, arg DeleteSiteParams) (int64, error)
	FailBackupSnapshot(ctx context.Context, arg FailBackupSnapshotParams) (BackupSnapshot, error)
	// Records a terminal task state (succeeded|failed|rolled_back|skipped) with the
	// resolved versions and any detail/error. Tenant-scoped by id+tenant_id.
	FinishUpdateTask(ctx context.Context, arg FinishUpdateTaskParams) (UpdateTask, error)
	GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error)
	// GetAPIKeyByPrefix resolves a presented key by its unique prefix. This runs
	// WITHOUT a tenant GUC (the auth layer does not yet know the tenant), so it must
	// be executed via InAdminTx which sets app.tenant_id to the row's own tenant is
	// impossible chicken/egg — instead this query is run with RLS disabled scope by
	// using the prefix-unique lookup helper that sets the GUC after. See repo.
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error)
	// Auth-time allowlist resolver: returns all non-expired site shares for a given
	// (user, tenant) pair. The result is used to build the AllowedSiteIDs list for a
	// site-scoped principal. Run under InUserTx (app.user_id set) or directly with
	// explicit params.
	GetActiveSharesForUserTenant(ctx context.Context, arg GetActiveSharesForUserTenantParams) ([]SiteShare, error)
	// M5 uptime alerting: per-tenant alert config + per-site alert state.
	// Tenant-scoped read of the tenant's default alert channel.
	GetAlertConfig(ctx context.Context, tenantID uuid.UUID) (AlertConfig, error)
	// Mint path (app.tenant_id). When no row exists the service auto-creates the
	// default policy on first read (see UpsertAutologinPolicyDefault).
	GetAutologinPolicy(ctx context.Context, arg GetAutologinPolicyParams) (AutologinPolicy, error)
	// Consume path (app.agent). Cross-tenant SELECT-only read of the policy so the
	// agent learns which WP roles it may log in as. NULL row -> defaults applied.
	GetAutologinPolicyForAgent(ctx context.Context, siteID uuid.UUID) (AutologinPolicy, error)
	// ---------------------------------------------------------------------------
	// backup_chunks  (content-addressed dedup + refcount GC)
	// ---------------------------------------------------------------------------
	GetBackupChunk(ctx context.Context, arg GetBackupChunkParams) (BackupChunk, error)
	// ---------------------------------------------------------------------------
	// backup_schedules
	// ---------------------------------------------------------------------------
	GetBackupScheduleForSite(ctx context.Context, arg GetBackupScheduleForSiteParams) (BackupSchedule, error)
	// Returns the site fields the backup scheduler needs: enrollment status,
	// agent URL, age recipient for encryption, and the WP timezone columns
	// added in M17 (wp_timezone IANA name + wp_gmt_offset fallback).
	// Runs tenant-scoped (the caller sets app.tenant_id before this query).
	GetBackupSiteInfo(ctx context.Context, arg GetBackupSiteInfoParams) (GetBackupSiteInfoRow, error)
	GetBackupSnapshot(ctx context.Context, arg GetBackupSnapshotParams) (BackupSnapshot, error)
	// Pre-auth lookup: must be run under InInviteLookupTx (app.invite_lookup='on').
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error)
	GetLastAuditHash(ctx context.Context, tenantID uuid.UUID) (string, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	// Enroll path (app.enroll GUC): resolve a presented code by its hash before the
	// tenant is known.
	GetPairingCodeByHash(ctx context.Context, codeHash string) (PairingCode, error)
	GetScheduleRun(ctx context.Context, arg GetScheduleRunParams) (BackupScheduleRun, error)
	GetSite(ctx context.Context, arg GetSiteParams) (Site, error)
	// Cross-tenant read of one site's alert state (app.agent GUC) for the probe job.
	GetSiteAlertState(ctx context.Context, siteID uuid.UUID) (SiteAlertState, error)
	// ---------------------------------------------------------------------------
	// Agent-auth path (app.agent GUC). Resolve a site by its agent public key.
	// ---------------------------------------------------------------------------
	GetSiteByAgentKey(ctx context.Context, agentPublicKey string) (Site, error)
	// ---------------------------------------------------------------------------
	// Enrollment path (app.enroll GUC). These run before any tenant scope exists.
	// ---------------------------------------------------------------------------
	GetSiteByURLForEnroll(ctx context.Context, arg GetSiteByURLForEnrollParams) (Site, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	// GetTenantForUser returns a tenant by id only when the given user is a member.
	// Like ListTenantsForUser it relies on the memberships_self_read policy and must
	// be run via InUserTx; a non-member (or unknown tenant) yields no rows.
	GetTenantForUser(ctx context.Context, arg GetTenantForUserParams) (Tenant, error)
	GetUpdateRun(ctx context.Context, arg GetUpdateRunParams) (UpdateRun, error)
	GetUpdateTask(ctx context.Context, arg GetUpdateTaskParams) (UpdateTask, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (User, error)
	IncrementChunkRefcount(ctx context.Context, arg IncrementChunkRefcountParams) (BackupChunk, error)
	IncrementInviteAttempts(ctx context.Context, id uuid.UUID) (Invitation, error)
	// Enroll path (app.enroll GUC): record a failed validation attempt.
	IncrementPairingCodeAttempts(ctx context.Context, id uuid.UUID) (int64, error)
	// Agent-auth path (app.agent GUC). The unique (site_id, nonce) index makes a
	// replayed nonce a no-op via ON CONFLICT, returning 0 rows affected.
	InsertAgentNonce(ctx context.Context, arg InsertAgentNonceParams) (int64, error)
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditLog, error)
	// ============================================================================
	// autologin (Phase 5.5 — One-Click Login) sqlc queries.
	//
	// The MINT path runs tenant-scoped (app.tenant_id) so RLS isolates the
	// INSERT. The CONSUME path runs cross-tenant under app.agent (the agent
	// presents the verified site_id + nonce — no tenant context yet); the
	// autologin_tokens_agent / autologin_tokens_agent_consume policies cover it.
	// The same policy split applies to autologin_policies (tenant-scoped read/
	// upsert + cross-tenant SELECT under app.agent for the agent's roles lookup).
	// ============================================================================
	// Mint path (app.tenant_id). The id is the JWT jti (base64url 32B random).
	InsertAutologinToken(ctx context.Context, arg InsertAutologinTokenParams) (AutologinToken, error)
	LinkUserOIDC(ctx context.Context, arg LinkUserOIDCParams) (User, error)
	ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error)
	// Cross-tenant enumeration for the evaluator (app.agent GUC). Only enabled
	// configs are returned.
	ListAlertConfigsAllTenants(ctx context.Context) ([]AlertConfig, error)
	ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditLog, error)
	ListAuditEntriesForVerify(ctx context.Context, tenantID uuid.UUID) ([]AuditLog, error)
	// Returns the tenant's already-stored chunks among the given hashes (dedup: the
	// agent only uploads hashes NOT returned here).
	ListBackupChunksByHashes(ctx context.Context, arg ListBackupChunksByHashesParams) ([]BackupChunk, error)
	// Distinct site IDs that have at least one snapshot in this tenant (GC iterates
	// per site to apply the per-site monthly-archive rule).
	ListBackupSiteIDsForTenant(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error)
	ListBackupSnapshotsForSite(ctx context.Context, arg ListBackupSnapshotsForSiteParams) ([]BackupSnapshot, error)
	// Completed snapshots for a site, newest first, used to compute the retention
	// archive set (newest per calendar month).
	ListCompletedSnapshotsForSite(ctx context.Context, arg ListCompletedSnapshotsForSiteParams) ([]ListCompletedSnapshotsForSiteRow, error)
	// Cross-tenant enumeration of enabled schedules whose next_run_at has passed,
	// for the periodic scheduler. Runs under the app.agent GUC (scheduler policy).
	ListDueBackupSchedules(ctx context.Context, arg ListDueBackupSchedulesParams) ([]BackupSchedule, error)
	// ---------------------------------------------------------------------------
	// Health-check job (runs in each enrolled site's tenant scope).
	// ---------------------------------------------------------------------------
	// Cross-tenant enumeration for the periodic health job. Runs under the
	// app.agent GUC (sites_agent policy) since it spans tenants.
	ListEnrolledSitesAllTenants(ctx context.Context) ([]ListEnrolledSitesAllTenantsRow, error)
	// Cross-tenant enumeration of enrolled sites WITH their URL for the M5 uptime
	// probe job. Runs under the app.agent GUC (sites_agent policy) since it spans
	// tenants. Only enrolled sites have an agent URL worth probing.
	ListEnrolledSitesForProbe(ctx context.Context) ([]ListEnrolledSitesForProbeRow, error)
	// Completed snapshots older than the cutoff that are NOT archive-retained, in a
	// single tenant scope. The GC job decrements chunk refcounts for each then
	// deletes the snapshot (manifest entries cascade).
	ListExpiredBackupSnapshots(ctx context.Context, arg ListExpiredBackupSnapshotsParams) ([]BackupSnapshot, error)
	ListManifestEntries(ctx context.Context, arg ListManifestEntriesParams) ([]BackupManifestEntry, error)
	ListMembershipsForTenant(ctx context.Context, arg ListMembershipsForTenantParams) ([]Membership, error)
	// ListMembershipsForUser reads the caller's own memberships across all tenants.
	// It relies on the memberships_self_read policy (app.user_id GUC), so it must be
	// run via InUserTx, not InTenantTx.
	ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]Membership, error)
	// Terminal runs (completed/failed/skipped/canceled) for a site, newest first.
	ListPastScheduleRuns(ctx context.Context, arg ListPastScheduleRunsParams) ([]BackupScheduleRun, error)
	// List pending (not yet accepted, not expired) invitations for the current tenant.
	ListPendingInvitations(ctx context.Context, tenantID uuid.UUID) ([]Invitation, error)
	// All runs for a site (upcoming + past), newest scheduled_for first.
	ListScheduleRunsBySite(ctx context.Context, arg ListScheduleRunsBySiteParams) ([]BackupScheduleRun, error)
	ListSharesForSite(ctx context.Context, siteID uuid.UUID) ([]SiteShare, error)
	// Self-read: returns the caller's own non-expired shares across all tenants.
	// Must be run under a tx that sets app.user_id (site_shares_self_read policy).
	ListSharesForUser(ctx context.Context, userID uuid.UUID) ([]SiteShare, error)
	ListSites(ctx context.Context, arg ListSitesParams) ([]Site, error)
	// Watchdog feeder: a running snapshot whose latest progress is older than the
	// stall threshold (or whose runner never reported any progress despite being
	// running for longer than the threshold). The new index
	// backup_snapshots_running_progress_idx makes the predicate selective.
	// Cross-tenant select via the GC RLS policy (app.agent='on').
	ListStalledRunningSnapshots(ctx context.Context, dollar_1 pgtype.Interval) ([]ListStalledRunningSnapshotsRow, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	// ListTenantsForUser returns only the tenants the given user is a member of.
	// It joins memberships under the memberships_self_read policy (app.user_id GUC),
	// so it MUST be run via InUserTx; the join itself restricts the result to the
	// caller's own memberships, preventing cross-tenant enumeration.
	ListTenantsForUser(ctx context.Context, arg ListTenantsForUserParams) ([]Tenant, error)
	// Distinct tenant IDs that have at least one completed snapshot, for the
	// periodic retention GC. Runs cross-tenant under the app.agent GUC (the
	// backup_snapshots_gc SELECT policy); the prune then runs per tenant.
	ListTenantsWithCompletedSnapshots(ctx context.Context) ([]uuid.UUID, error)
	// Runs that have not yet fired: status 'scheduled' or 'queued', scheduled_for
	// in the future. Used for the UI upcoming preview (typically 1–3 rows).
	ListUpcomingScheduleRuns(ctx context.Context, arg ListUpcomingScheduleRunsParams) ([]BackupScheduleRun, error)
	ListUpdateRuns(ctx context.Context, arg ListUpdateRunsParams) ([]UpdateRun, error)
	ListUpdateTasksForRun(ctx context.Context, arg ListUpdateTasksForRunParams) ([]UpdateTask, error)
	// Used on the Redis-hot-path success: Redis already produced the payload, but
	// we still UPDATE the PG row so the audit/observability story is complete.
	// Idempotent: returns 0 if another path already marked it (safe).
	MarkAutologinTokenConsumed(ctx context.Context, arg MarkAutologinTokenConsumedParams) (int64, error)
	MarkBackupSnapshotRunning(ctx context.Context, arg MarkBackupSnapshotRunningParams) (BackupSnapshot, error)
	MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) (Invitation, error)
	// Marks a site unreachable. Runs under app.agent GUC (cross-tenant job).
	MarkSiteUnreachable(ctx context.Context, id uuid.UUID) (int64, error)
	MarkUpdateTaskRunning(ctx context.Context, arg MarkUpdateTaskRunningParams) (UpdateTask, error)
	// Drops nonces older than the freshness window; called opportunistically.
	PruneAgentNonces(ctx context.Context, createdAt time.Time) (int64, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	SetBackupSnapshotArchived(ctx context.Context, arg SetBackupSnapshotArchivedParams) error
	// Links the pending snapshot_id to a run and advances its status to 'queued'.
	SetScheduleRunSnapshot(ctx context.Context, arg SetScheduleRunSnapshotParams) (BackupScheduleRun, error)
	// Advances a run to a terminal or intermediate status by its primary key.
	// started_at and finished_at are set conditionally so they are only written
	// once (the scheduler calls this for running→completed/failed transitions).
	SetScheduleRunStatusByID(ctx context.Context, arg SetScheduleRunStatusByIDParams) (BackupScheduleRun, error)
	// Reconciliation path: when the linked snapshot reaches a terminal status,
	// update the run row to match. Keyed on snapshot_id so the snapshot finalize
	// path does not need to carry the run id. Runs tenant-scoped.
	SetScheduleRunStatusBySnapshot(ctx context.Context, arg SetScheduleRunStatusBySnapshotParams) (BackupScheduleRun, error)
	// Stores the per-site age PUBLIC recipient backups are encrypted to. The CP
	// never holds the matching identity (private key); it cannot decrypt backups.
	SetSiteAgeRecipient(ctx context.Context, arg SetSiteAgeRecipientParams) (Site, error)
	// Sets a site's health_status from an M5 probe result (cross-tenant probe job,
	// app.agent GUC). Only writes when the value actually changes to avoid churn.
	SetSiteHealthStatus(ctx context.Context, arg SetSiteHealthStatusParams) (int64, error)
	SetSiteTags(ctx context.Context, arg SetSiteTagsParams) (Site, error)
	SetUpdateRunStatus(ctx context.Context, arg SetUpdateRunStatusParams) (UpdateRun, error)
	SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error
	TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error
	TouchSiteSeen(ctx context.Context, arg TouchSiteSeenParams) (Site, error)
	TouchUserLogin(ctx context.Context, id uuid.UUID) error
	// M5.6 / ADR-032: agent runner posts a JSONB progress payload at every phpbu
	// stage transition + per-chunk during the custom PresignedS3 Sync. We always
	// replace (no append/history) — the latest phase is what the UI renders, and
	// the watchdog scans by progress_updated_at. Tenant-scoped via RLS; the agent
	// handler injects the tenant from the verified Ed25519 identity, never from
	// the body.
	UpdateBackupSnapshotProgress(ctx context.Context, arg UpdateBackupSnapshotProgressParams) (BackupSnapshot, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error)
	// Tenant-scoped metadata update (used by the agent path inside the resolved
	// site's own tenant scope).
	UpdateSiteMetadata(ctx context.Context, arg UpdateSiteMetadataParams) (Site, error)
	// Tenant-scoped create-or-update of the tenant's default alert channel.
	UpsertAlertConfig(ctx context.Context, arg UpsertAlertConfigParams) (AlertConfig, error)
	// Mint path (app.tenant_id). Idempotent insert-or-return: the first call seeds
	// the default policy (enabled, allowed=administrator, 2FA off, max age 30m);
	// subsequent calls return the existing row unchanged.
	UpsertAutologinPolicyDefault(ctx context.Context, arg UpsertAutologinPolicyDefaultParams) (AutologinPolicy, error)
	// Records a chunk's storage location idempotently. On conflict (the chunk
	// already exists) it leaves size/s3_key as-is (content-addressed: identical
	// hash ⇒ identical bytes) and returns the existing row. refcount is managed
	// separately by IncrementChunkRefcount.
	UpsertBackupChunk(ctx context.Context, arg UpsertBackupChunkParams) (BackupChunk, error)
	// Inserts or updates a backup schedule. next_run_at is intentionally NOT
	// included in the ON CONFLICT DO UPDATE set: the service decides when to
	// recompute it (only when timing fields actually change). This prevents a
	// non-timing edit (e.g. retention_days change) from resetting the next run.
	UpsertBackupSchedule(ctx context.Context, arg UpsertBackupScheduleParams) (BackupSchedule, error)
	// Tenant-create helper: insert an owner membership for the creator; on conflict
	// (e.g. migration replay or second create attempt) update role to 'owner'.
	UpsertOwnerMembership(ctx context.Context, arg UpsertOwnerMembershipParams) (Membership, error)
	// M17 backup_schedule_runs queries. Mirrors the restore_runs query style.
	// Every tenant-scoped method is called with app.tenant_id already set.
	// The scheduler's cross-tenant materializer writes run under the agent context
	// (app.agent='on'), like ListDueBackupSchedules.
	// ---------------------------------------------------------------------------
	// backup_schedule_runs
	// ---------------------------------------------------------------------------
	// Pre-inserts the next scheduled run row idempotently. On conflict
	// (schedule_id, scheduled_for) — e.g. CP restart — updates status only when
	// the existing row is still 'scheduled' so a queued/running row is untouched.
	UpsertScheduleRun(ctx context.Context, arg UpsertScheduleRunParams) (BackupScheduleRun, error)
	// Cross-tenant upsert of a site's alert state (app.agent GUC). The probe worker
	// writes the new transition memory after each probe.
	UpsertSiteAlertState(ctx context.Context, arg UpsertSiteAlertStateParams) (SiteAlertState, error)
}

var _ Querier = (*Queries)(nil)
