// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule_runs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getScheduleRun = `-- name: GetScheduleRun :one
SELECT id, tenant_id, site_id, schedule_id, snapshot_id, scheduled_for, status, kind, error, triggered_by, created_at, started_at, finished_at, updated_at FROM backup_schedule_runs
WHERE id = $1 AND tenant_id = $2
`

type GetScheduleRunParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetScheduleRun(ctx context.Context, arg GetScheduleRunParams) (BackupScheduleRun, error) {
	row := q.db.QueryRow(ctx, getScheduleRun, arg.ID, arg.TenantID)
	var i BackupScheduleRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.ScheduleID,
		&i.SnapshotID,
		&i.ScheduledFor,
		&i.Status,
		&i.Kind,
		&i.Error,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPastScheduleRuns = `-- name: ListPastScheduleRuns :many
SELECT id, tenant_id, site_id, schedule_id, snapshot_id, scheduled_for, status, kind, error, triggered_by, created_at, started_at, finished_at, updated_at FROM backup_schedule_runs
WHERE tenant_id = $1 AND site_id = $2
  AND status IN ('completed', 'failed', 'skipped', 'canceled')
ORDER BY scheduled_for DESC
LIMIT $3 OFFSET $4
`

type ListPastScheduleRunsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

// Terminal runs (completed/failed/skipped/canceled) for a site, newest first.
func (q *Queries) ListPastScheduleRuns(ctx context.Context, arg ListPastScheduleRunsParams) ([]BackupScheduleRun, error) {
	rows, err := q.db.Query(ctx, listPastScheduleRuns,
		arg.TenantID,
		arg.SiteID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupScheduleRun
	for rows.Next() {
		var i BackupScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.ScheduleID,
			&i.SnapshotID,
			&i.ScheduledFor,
			&i.Status,
			&i.Kind,
			&i.Error,
			&i.TriggeredBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRunsBySite = `-- name: ListScheduleRunsBySite :many
SELECT id, tenant_id, site_id, schedule_id, snapshot_id, scheduled_for, status, kind, error, triggered_by, created_at, started_at, finished_at, updated_at FROM backup_schedule_runs
WHERE tenant_id = $1 AND site_id = $2
ORDER BY scheduled_for DESC
LIMIT $3 OFFSET $4
`

type ListScheduleRunsBySiteParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

// All runs for a site (upcoming + past), newest scheduled_for first.
func (q *Queries) ListScheduleRunsBySite(ctx context.Context, arg ListScheduleRunsBySiteParams) ([]BackupScheduleRun, error) {
	rows, err := q.db.Query(ctx, listScheduleRunsBySite,
		arg.TenantID,
		arg.SiteID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupScheduleRun
	for rows.Next() {
		var i BackupScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.ScheduleID,
			&i.SnapshotID,
			&i.ScheduledFor,
			&i.Status,
			&i.Kind,
			&i.Error,
			&i.TriggeredBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingScheduleRuns = `-- name: ListUpcomingScheduleRuns :many
SELECT id, tenant_id, site_id, schedule_id, snapshot_id, scheduled_for, status, kind, error, triggered_by, created_at, started_at, finished_at, updated_at FROM backup_schedule_runs
WHERE tenant_id = $1 AND site_id = $2
  AND status IN ('scheduled', 'queued')
  AND scheduled_for > now()
ORDER BY scheduled_for ASC
LIMIT $3
`

type ListUpcomingScheduleRunsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
	Limit    int32     `json:"limit"`
}

// Runs that have not yet fired: status 'scheduled' or 'queued', scheduled_for
// in the future. Used for the UI upcoming preview (typically 1–3 rows).
func (q *Queries) ListUpcomingScheduleRuns(ctx context.Context, arg ListUpcomingScheduleRunsParams) ([]BackupScheduleRun, error) {
	rows, err := q.db.Query(ctx, listUpcomingScheduleRuns, arg.TenantID, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupScheduleRun
	for rows.Next() {
		var i BackupScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.ScheduleID,
			&i.SnapshotID,
			&i.ScheduledFor,
			&i.Status,
			&i.Kind,
			&i.Error,
			&i.TriggeredBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setScheduleRunSnapshot = `-- name: SetScheduleRunSnapshot :one
UPDATE backup_schedule_runs
SET snapshot_id = $3,
    status      = 'queued',
    updated_at  = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, site_id, schedule_id, snapshot_id, scheduled_for, status, kind, error, triggered_by, created_at, started_at, finished_at, updated_at
`

type SetScheduleRunSnapshotParams struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	SnapshotID pgtype.UUID `json:"snapshot_id"`
}

// Links the pending snapshot_id to a run and advances its status to 'queued'.
func (q *Queries) SetScheduleRunSnapshot(ctx context.Context, arg SetScheduleRunSnapshotParams) (BackupScheduleRun, error) {
	row := q.db.QueryRow(ctx, setScheduleRunSnapshot, arg.ID, arg.TenantID, arg.SnapshotID)
	var i BackupScheduleRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.ScheduleID,
		&i.SnapshotID,
		&i.ScheduledFor,
		&i.Status,
		&i.Kind,
		&i.Error,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setScheduleRunStatusByID = `-- name: SetScheduleRunStatusByID :one
UPDATE backup_schedule_runs
SET status      = $3,
    error       = $4,
    started_at  = CASE WHEN $5::boolean THEN now() ELSE started_at  END,
    finished_at = CASE WHEN $6::boolean THEN now() ELSE finished_at END,
    updated_at  = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, site_id, schedule_id, snapshot_id, scheduled_for, status, kind, error, triggered_by, created_at, started_at, finished_at, updated_at
`

type SetScheduleRunStatusByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
	Error    *string   `json:"error"`
	Column5  bool      `json:"column_5"`
	Column6  bool      `json:"column_6"`
}

// Advances a run to a terminal or intermediate status by its primary key.
// started_at and finished_at are set conditionally so they are only written
// once (the scheduler calls this for running→completed/failed transitions).
func (q *Queries) SetScheduleRunStatusByID(ctx context.Context, arg SetScheduleRunStatusByIDParams) (BackupScheduleRun, error) {
	row := q.db.QueryRow(ctx, setScheduleRunStatusByID,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.Error,
		arg.Column5,
		arg.Column6,
	)
	var i BackupScheduleRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.ScheduleID,
		&i.SnapshotID,
		&i.ScheduledFor,
		&i.Status,
		&i.Kind,
		&i.Error,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setScheduleRunStatusBySnapshot = `-- name: SetScheduleRunStatusBySnapshot :one
UPDATE backup_schedule_runs
SET status      = $3,
    error       = $4,
    started_at  = CASE WHEN $5::boolean THEN now() ELSE started_at  END,
    finished_at = CASE WHEN $6::boolean THEN now() ELSE finished_at END,
    updated_at  = now()
WHERE snapshot_id = $1 AND tenant_id = $2
RETURNING id, tenant_id, site_id, schedule_id, snapshot_id, scheduled_for, status, kind, error, triggered_by, created_at, started_at, finished_at, updated_at
`

type SetScheduleRunStatusBySnapshotParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	Status     string      `json:"status"`
	Error      *string     `json:"error"`
	Column5    bool        `json:"column_5"`
	Column6    bool        `json:"column_6"`
}

// Reconciliation path: when the linked snapshot reaches a terminal status,
// update the run row to match. Keyed on snapshot_id so the snapshot finalize
// path does not need to carry the run id. Runs tenant-scoped.
func (q *Queries) SetScheduleRunStatusBySnapshot(ctx context.Context, arg SetScheduleRunStatusBySnapshotParams) (BackupScheduleRun, error) {
	row := q.db.QueryRow(ctx, setScheduleRunStatusBySnapshot,
		arg.SnapshotID,
		arg.TenantID,
		arg.Status,
		arg.Error,
		arg.Column5,
		arg.Column6,
	)
	var i BackupScheduleRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.ScheduleID,
		&i.SnapshotID,
		&i.ScheduledFor,
		&i.Status,
		&i.Kind,
		&i.Error,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertScheduleRun = `-- name: UpsertScheduleRun :one


INSERT INTO backup_schedule_runs (
    tenant_id, site_id, schedule_id, scheduled_for, status, kind, triggered_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (schedule_id, scheduled_for)
DO UPDATE SET
    status       = CASE
                       WHEN backup_schedule_runs.status = 'scheduled'
                       THEN EXCLUDED.status
                       ELSE backup_schedule_runs.status
                   END,
    updated_at   = now()
RETURNING id, tenant_id, site_id, schedule_id, snapshot_id, scheduled_for, status, kind, error, triggered_by, created_at, started_at, finished_at, updated_at
`

type UpsertScheduleRunParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	SiteID       uuid.UUID `json:"site_id"`
	ScheduleID   uuid.UUID `json:"schedule_id"`
	ScheduledFor time.Time `json:"scheduled_for"`
	Status       string    `json:"status"`
	Kind         string    `json:"kind"`
	TriggeredBy  *string   `json:"triggered_by"`
}

// M17 backup_schedule_runs queries. Mirrors the restore_runs query style.
// Every tenant-scoped method is called with app.tenant_id already set.
// The scheduler's cross-tenant materializer writes run under the agent context
// (app.agent='on'), like ListDueBackupSchedules.
// ---------------------------------------------------------------------------
// backup_schedule_runs
// ---------------------------------------------------------------------------
// Pre-inserts the next scheduled run row idempotently. On conflict
// (schedule_id, scheduled_for) — e.g. CP restart — updates status only when
// the existing row is still 'scheduled' so a queued/running row is untouched.
func (q *Queries) UpsertScheduleRun(ctx context.Context, arg UpsertScheduleRunParams) (BackupScheduleRun, error) {
	row := q.db.QueryRow(ctx, upsertScheduleRun,
		arg.TenantID,
		arg.SiteID,
		arg.ScheduleID,
		arg.ScheduledFor,
		arg.Status,
		arg.Kind,
		arg.TriggeredBy,
	)
	var i BackupScheduleRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.ScheduleID,
		&i.SnapshotID,
		&i.ScheduledFor,
		&i.Status,
		&i.Kind,
		&i.Error,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}
