// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_context.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSiteContextVersion = `-- name: CreateSiteContextVersion :one
INSERT INTO site_context_versions (
    tenant_id, site_id, version, restrictions, guidance,
    author_type, author_id, provenance, restored_from_version_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, tenant_id, site_id, version, restrictions, guidance, author_type, author_id, provenance, restored_from_version_id, created_at
`

type CreateSiteContextVersionParams struct {
	TenantID              uuid.UUID   `json:"tenant_id"`
	SiteID                uuid.UUID   `json:"site_id"`
	Version               int64       `json:"version"`
	Restrictions          []byte      `json:"restrictions"`
	Guidance              []byte      `json:"guidance"`
	AuthorType            string      `json:"author_type"`
	AuthorID              pgtype.UUID `json:"author_id"`
	Provenance            string      `json:"provenance"`
	RestoredFromVersionID pgtype.UUID `json:"restored_from_version_id"`
}

func (q *Queries) CreateSiteContextVersion(ctx context.Context, arg CreateSiteContextVersionParams) (SiteContextVersion, error) {
	row := q.db.QueryRow(ctx, createSiteContextVersion,
		arg.TenantID,
		arg.SiteID,
		arg.Version,
		arg.Restrictions,
		arg.Guidance,
		arg.AuthorType,
		arg.AuthorID,
		arg.Provenance,
		arg.RestoredFromVersionID,
	)
	var i SiteContextVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Version,
		&i.Restrictions,
		&i.Guidance,
		&i.AuthorType,
		&i.AuthorID,
		&i.Provenance,
		&i.RestoredFromVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSiteContextVersion = `-- name: GetLatestSiteContextVersion :one
SELECT id, tenant_id, site_id, version, restrictions, guidance, author_type, author_id, provenance, restored_from_version_id, created_at FROM site_context_versions
WHERE tenant_id = $1 AND site_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestSiteContextVersionParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
}

// ADR-064 Decision 3: "the current context" is the latest version row, scoped
// to the CURRENT tenant. After a site transfer only post-transfer rows carry
// the current tenant_id, so this naturally returns the destination org's
// active context per Decision 12 with no extra transfer-aware logic.
func (q *Queries) GetLatestSiteContextVersion(ctx context.Context, arg GetLatestSiteContextVersionParams) (SiteContextVersion, error) {
	row := q.db.QueryRow(ctx, getLatestSiteContextVersion, arg.TenantID, arg.SiteID)
	var i SiteContextVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Version,
		&i.Restrictions,
		&i.Guidance,
		&i.AuthorType,
		&i.AuthorID,
		&i.Provenance,
		&i.RestoredFromVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteContextVersionByID = `-- name: GetSiteContextVersionByID :one
SELECT id, tenant_id, site_id, version, restrictions, guidance, author_type, author_id, provenance, restored_from_version_id, created_at FROM site_context_versions
WHERE tenant_id = $1 AND site_id = $2 AND id = $3
`

type GetSiteContextVersionByIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
	ID       uuid.UUID `json:"id"`
}

// tenant_id is explicit (defense in depth per house convention) AND is the
// mechanism that makes a restore-pointer's stamp check work: a version id
// belonging to a DIFFERENT tenant stamp (a pre-transfer row, ADR-064 Decision
// 12) returns no rows here even though the row physically exists, because RLS
// tenant_isolation also filters on tenant_id and this WHERE clause matches
// it. Callers rely on this: "not found" here means "does not exist OR belongs
// to a stamp this caller may not read", which is exactly Decision 12's rule.
func (q *Queries) GetSiteContextVersionByID(ctx context.Context, arg GetSiteContextVersionByIDParams) (SiteContextVersion, error) {
	row := q.db.QueryRow(ctx, getSiteContextVersionByID, arg.TenantID, arg.SiteID, arg.ID)
	var i SiteContextVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Version,
		&i.Restrictions,
		&i.Guidance,
		&i.AuthorType,
		&i.AuthorID,
		&i.Provenance,
		&i.RestoredFromVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteContextVersionByVersion = `-- name: GetSiteContextVersionByVersion :one
SELECT id, tenant_id, site_id, version, restrictions, guidance, author_type, author_id, provenance, restored_from_version_id, created_at FROM site_context_versions
WHERE tenant_id = $1 AND site_id = $2 AND version = $3
`

type GetSiteContextVersionByVersionParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
	Version  int64     `json:"version"`
}

// Used to fetch the immediately-prior version for a diff (ADR-064 Decision 5).
// Same tenant-stamp mechanism as GetSiteContextVersionByID: if the immediately
// prior version (version-1) is stamped to a different (pre-transfer) tenant,
// this returns no rows under the current tenant, which the caller must read
// as "no eligible predecessor, render a baseline" per Decision 5 — not as an
// error.
func (q *Queries) GetSiteContextVersionByVersion(ctx context.Context, arg GetSiteContextVersionByVersionParams) (SiteContextVersion, error) {
	row := q.db.QueryRow(ctx, getSiteContextVersionByVersion, arg.TenantID, arg.SiteID, arg.Version)
	var i SiteContextVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Version,
		&i.Restrictions,
		&i.Guidance,
		&i.AuthorType,
		&i.AuthorID,
		&i.Provenance,
		&i.RestoredFromVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const listSiteContextVersions = `-- name: ListSiteContextVersions :many
SELECT id, tenant_id, site_id, version, restrictions, guidance, author_type, author_id, provenance, restored_from_version_id, created_at FROM site_context_versions
WHERE tenant_id = $1 AND site_id = $2
  AND ($3::bigint = 0 OR version < $3::bigint)
ORDER BY version DESC
LIMIT $4
`

type ListSiteContextVersionsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
	Column3  int64     `json:"column_3"`
	Limit    int32     `json:"limit"`
}

// Keyset-paginated newest-first history, scoped to the CURRENT tenant stamp
// only — this is what makes list/item history "additionally scoped to
// versions stamped with the site's current organisation" (ADR-064 Decision 13)
// true with no extra filtering: a pre-transfer row simply never matches
// tenant_id = $1 once the site belongs to a new org. Cursor is the version
// number (unique, monotonic, gap-free per site via site_context_versions_
// version_key); 0 means first page.
func (q *Queries) ListSiteContextVersions(ctx context.Context, arg ListSiteContextVersionsParams) ([]SiteContextVersion, error) {
	rows, err := q.db.Query(ctx, listSiteContextVersions,
		arg.TenantID,
		arg.SiteID,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteContextVersion
	for rows.Next() {
		var i SiteContextVersion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Version,
			&i.Restrictions,
			&i.Guidance,
			&i.AuthorType,
			&i.AuthorID,
			&i.Provenance,
			&i.RestoredFromVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
