// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (tenant_id, url, name, status, wp_version, php_version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, url, name, status, wp_version, php_version, created_at, updated_at
`

type CreateSiteParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	Url        string    `json:"url"`
	Name       string    `json:"name"`
	Status     string    `json:"status"`
	WpVersion  string    `json:"wp_version"`
	PhpVersion string    `json:"php_version"`
}

// tenant_id is supplied explicitly for defense-in-depth; RLS additionally
// enforces that it matches the current app.tenant_id setting.
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.TenantID,
		arg.Url,
		arg.Name,
		arg.Status,
		arg.WpVersion,
		arg.PhpVersion,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :execrows
DELETE FROM sites
WHERE id = $1 AND tenant_id = $2
`

type DeleteSiteParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteSite(ctx context.Context, arg DeleteSiteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSite, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSite = `-- name: GetSite :one
SELECT id, tenant_id, url, name, status, wp_version, php_version, created_at, updated_at FROM sites
WHERE id = $1 AND tenant_id = $2
`

type GetSiteParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetSite(ctx context.Context, arg GetSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, arg.ID, arg.TenantID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT id, tenant_id, url, name, status, wp_version, php_version, created_at, updated_at FROM sites
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSitesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListSites(ctx context.Context, arg ListSitesParams) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Name,
			&i.Status,
			&i.WpVersion,
			&i.PhpVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
