// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachAgentToSite = `-- name: AttachAgentToSite :one
UPDATE sites
SET agent_public_key = $3,
    status = 'active',
    enrolled_at = now(),
    last_seen_at = now(),
    health_status = 'healthy',
    wp_version = $4,
    php_version = $5,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, url, name, status, wp_version, php_version, agent_version, agent_public_key, enrolled_at, last_seen_at, health_status, server_info, multisite, active_theme, components, components_updated_at, tags, age_recipient, wp_timezone, wp_gmt_offset, host_provider, host_provider_org, host_provider_ip, host_provider_checked_at, connection_state, connection_generation, disconnected_at, disconnected_reason, archived_at, missed_heartbeats, client_id, app_probe_path, app_alerts_disabled, monitoring_paused_at, monitoring_paused_by, monitoring_paused_reason, monitoring_resume_at, created_at, updated_at
`

type AttachAgentToSiteParams struct {
	ID             uuid.UUID `json:"id"`
	TenantID       uuid.UUID `json:"tenant_id"`
	AgentPublicKey string    `json:"agent_public_key"`
	WpVersion      string    `json:"wp_version"`
	PhpVersion     string    `json:"php_version"`
}

// Re-enrollment: rotate the agent key and mark the site active/enrolled again.
func (q *Queries) AttachAgentToSite(ctx context.Context, arg AttachAgentToSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, attachAgentToSite,
		arg.ID,
		arg.TenantID,
		arg.AgentPublicKey,
		arg.WpVersion,
		arg.PhpVersion,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.AgentVersion,
		&i.AgentPublicKey,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.HealthStatus,
		&i.ServerInfo,
		&i.Multisite,
		&i.ActiveTheme,
		&i.Components,
		&i.ComponentsUpdatedAt,
		&i.Tags,
		&i.AgeRecipient,
		&i.WpTimezone,
		&i.WpGmtOffset,
		&i.HostProvider,
		&i.HostProviderOrg,
		&i.HostProviderIp,
		&i.HostProviderCheckedAt,
		&i.ConnectionState,
		&i.ConnectionGeneration,
		&i.DisconnectedAt,
		&i.DisconnectedReason,
		&i.ArchivedAt,
		&i.MissedHeartbeats,
		&i.ClientID,
		&i.AppProbePath,
		&i.AppAlertsDisabled,
		&i.MonitoringPausedAt,
		&i.MonitoringPausedBy,
		&i.MonitoringPausedReason,
		&i.MonitoringResumeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSite = `-- name: CreateSite :one
INSERT INTO sites (tenant_id, url, name, status, wp_version, php_version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, url, name, status, wp_version, php_version, agent_version, agent_public_key, enrolled_at, last_seen_at, health_status, server_info, multisite, active_theme, components, components_updated_at, tags, age_recipient, wp_timezone, wp_gmt_offset, host_provider, host_provider_org, host_provider_ip, host_provider_checked_at, connection_state, connection_generation, disconnected_at, disconnected_reason, archived_at, missed_heartbeats, client_id, app_probe_path, app_alerts_disabled, monitoring_paused_at, monitoring_paused_by, monitoring_paused_reason, monitoring_resume_at, created_at, updated_at
`

type CreateSiteParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	Url        string    `json:"url"`
	Name       string    `json:"name"`
	Status     string    `json:"status"`
	WpVersion  string    `json:"wp_version"`
	PhpVersion string    `json:"php_version"`
}

// tenant_id is supplied explicitly for defense-in-depth; RLS additionally
// enforces that it matches the current app.tenant_id setting.
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.TenantID,
		arg.Url,
		arg.Name,
		arg.Status,
		arg.WpVersion,
		arg.PhpVersion,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.AgentVersion,
		&i.AgentPublicKey,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.HealthStatus,
		&i.ServerInfo,
		&i.Multisite,
		&i.ActiveTheme,
		&i.Components,
		&i.ComponentsUpdatedAt,
		&i.Tags,
		&i.AgeRecipient,
		&i.WpTimezone,
		&i.WpGmtOffset,
		&i.HostProvider,
		&i.HostProviderOrg,
		&i.HostProviderIp,
		&i.HostProviderCheckedAt,
		&i.ConnectionState,
		&i.ConnectionGeneration,
		&i.DisconnectedAt,
		&i.DisconnectedReason,
		&i.ArchivedAt,
		&i.MissedHeartbeats,
		&i.ClientID,
		&i.AppProbePath,
		&i.AppAlertsDisabled,
		&i.MonitoringPausedAt,
		&i.MonitoringPausedBy,
		&i.MonitoringPausedReason,
		&i.MonitoringResumeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSiteForEnroll = `-- name: CreateSiteForEnroll :one
INSERT INTO sites (tenant_id, url, name, status, wp_version, php_version,
                   agent_public_key, enrolled_at, last_seen_at, health_status, tags)
VALUES ($1, $2, $3, 'active', $4, $5, $6, now(), now(), 'healthy', $7)
RETURNING id, tenant_id, url, name, status, wp_version, php_version, agent_version, agent_public_key, enrolled_at, last_seen_at, health_status, server_info, multisite, active_theme, components, components_updated_at, tags, age_recipient, wp_timezone, wp_gmt_offset, host_provider, host_provider_org, host_provider_ip, host_provider_checked_at, connection_state, connection_generation, disconnected_at, disconnected_reason, archived_at, missed_heartbeats, client_id, app_probe_path, app_alerts_disabled, monitoring_paused_at, monitoring_paused_by, monitoring_paused_reason, monitoring_resume_at, created_at, updated_at
`

type CreateSiteForEnrollParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	Url            string    `json:"url"`
	Name           string    `json:"name"`
	WpVersion      string    `json:"wp_version"`
	PhpVersion     string    `json:"php_version"`
	AgentPublicKey string    `json:"agent_public_key"`
	Tags           []string  `json:"tags"`
}

func (q *Queries) CreateSiteForEnroll(ctx context.Context, arg CreateSiteForEnrollParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSiteForEnroll,
		arg.TenantID,
		arg.Url,
		arg.Name,
		arg.WpVersion,
		arg.PhpVersion,
		arg.AgentPublicKey,
		arg.Tags,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.AgentVersion,
		&i.AgentPublicKey,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.HealthStatus,
		&i.ServerInfo,
		&i.Multisite,
		&i.ActiveTheme,
		&i.Components,
		&i.ComponentsUpdatedAt,
		&i.Tags,
		&i.AgeRecipient,
		&i.WpTimezone,
		&i.WpGmtOffset,
		&i.HostProvider,
		&i.HostProviderOrg,
		&i.HostProviderIp,
		&i.HostProviderCheckedAt,
		&i.ConnectionState,
		&i.ConnectionGeneration,
		&i.DisconnectedAt,
		&i.DisconnectedReason,
		&i.ArchivedAt,
		&i.MissedHeartbeats,
		&i.ClientID,
		&i.AppProbePath,
		&i.AppAlertsDisabled,
		&i.MonitoringPausedAt,
		&i.MonitoringPausedBy,
		&i.MonitoringPausedReason,
		&i.MonitoringResumeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :execrows
DELETE FROM sites
WHERE id = $1 AND tenant_id = $2
`

type DeleteSiteParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteSite(ctx context.Context, arg DeleteSiteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSite, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSite = `-- name: GetSite :one
SELECT s.id, s.tenant_id, s.url, s.name, s.status, s.wp_version, s.php_version, s.agent_version, s.agent_public_key, s.enrolled_at, s.last_seen_at, s.health_status, s.server_info, s.multisite, s.active_theme, s.components, s.components_updated_at, s.tags, s.age_recipient, s.wp_timezone, s.wp_gmt_offset, s.host_provider, s.host_provider_org, s.host_provider_ip, s.host_provider_checked_at, s.connection_state, s.connection_generation, s.disconnected_at, s.disconnected_reason, s.archived_at, s.missed_heartbeats, s.client_id, s.app_probe_path, s.app_alerts_disabled, s.monitoring_paused_at, s.monitoring_paused_by, s.monitoring_paused_reason, s.monitoring_resume_at, s.created_at, s.updated_at,
       COALESCE(pc.cache_enabled, false) AS page_cache_enabled,
       COALESCE(oc.enabled, false) AS object_cache_enabled
FROM sites s
LEFT JOIN site_perf_config pc
    ON pc.site_id = s.id AND pc.tenant_id = s.tenant_id
LEFT JOIN site_object_cache_config oc
    ON oc.site_id = s.id AND oc.tenant_id = s.tenant_id
WHERE s.id = $1 AND s.tenant_id = $2
`

type GetSiteParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetSiteRow struct {
	ID                     uuid.UUID          `json:"id"`
	TenantID               uuid.UUID          `json:"tenant_id"`
	Url                    string             `json:"url"`
	Name                   string             `json:"name"`
	Status                 string             `json:"status"`
	WpVersion              string             `json:"wp_version"`
	PhpVersion             string             `json:"php_version"`
	AgentVersion           string             `json:"agent_version"`
	AgentPublicKey         string             `json:"agent_public_key"`
	EnrolledAt             pgtype.Timestamptz `json:"enrolled_at"`
	LastSeenAt             pgtype.Timestamptz `json:"last_seen_at"`
	HealthStatus           string             `json:"health_status"`
	ServerInfo             string             `json:"server_info"`
	Multisite              bool               `json:"multisite"`
	ActiveTheme            string             `json:"active_theme"`
	Components             []byte             `json:"components"`
	ComponentsUpdatedAt    pgtype.Timestamptz `json:"components_updated_at"`
	Tags                   []string           `json:"tags"`
	AgeRecipient           string             `json:"age_recipient"`
	WpTimezone             string             `json:"wp_timezone"`
	WpGmtOffset            float32            `json:"wp_gmt_offset"`
	HostProvider           string             `json:"host_provider"`
	HostProviderOrg        string             `json:"host_provider_org"`
	HostProviderIp         string             `json:"host_provider_ip"`
	HostProviderCheckedAt  pgtype.Timestamptz `json:"host_provider_checked_at"`
	ConnectionState        string             `json:"connection_state"`
	ConnectionGeneration   int32              `json:"connection_generation"`
	DisconnectedAt         pgtype.Timestamptz `json:"disconnected_at"`
	DisconnectedReason     *string            `json:"disconnected_reason"`
	ArchivedAt             pgtype.Timestamptz `json:"archived_at"`
	MissedHeartbeats       int32              `json:"missed_heartbeats"`
	ClientID               pgtype.UUID        `json:"client_id"`
	AppProbePath           *string            `json:"app_probe_path"`
	AppAlertsDisabled      bool               `json:"app_alerts_disabled"`
	MonitoringPausedAt     pgtype.Timestamptz `json:"monitoring_paused_at"`
	MonitoringPausedBy     pgtype.UUID        `json:"monitoring_paused_by"`
	MonitoringPausedReason string             `json:"monitoring_paused_reason"`
	MonitoringResumeAt     pgtype.Timestamptz `json:"monitoring_resume_at"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	PageCacheEnabled       bool               `json:"page_cache_enabled"`
	ObjectCacheEnabled     bool               `json:"object_cache_enabled"`
}

// GH #243: page_cache_enabled / object_cache_enabled surface the REAL
// drop-in config state (site_perf_config.cache_enabled / site_object_cache_
// config.enabled) via a PK-keyed LEFT JOIN (both tables are one-row-per-site,
// site_id PRIMARY KEY) instead of the old plugin-slug inference that could
// never match (both features ship as drop-ins, not plugins). Both joined
// tables carry their own tenant_isolation RLS, so this is RLS-safe; the
// explicit tenant_id match in the ON clause is defense-in-depth + keeps the
// planner on the PK index (project convention — see clients.sql).
func (q *Queries) GetSite(ctx context.Context, arg GetSiteParams) (GetSiteRow, error) {
	row := q.db.QueryRow(ctx, getSite, arg.ID, arg.TenantID)
	var i GetSiteRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.AgentVersion,
		&i.AgentPublicKey,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.HealthStatus,
		&i.ServerInfo,
		&i.Multisite,
		&i.ActiveTheme,
		&i.Components,
		&i.ComponentsUpdatedAt,
		&i.Tags,
		&i.AgeRecipient,
		&i.WpTimezone,
		&i.WpGmtOffset,
		&i.HostProvider,
		&i.HostProviderOrg,
		&i.HostProviderIp,
		&i.HostProviderCheckedAt,
		&i.ConnectionState,
		&i.ConnectionGeneration,
		&i.DisconnectedAt,
		&i.DisconnectedReason,
		&i.ArchivedAt,
		&i.MissedHeartbeats,
		&i.ClientID,
		&i.AppProbePath,
		&i.AppAlertsDisabled,
		&i.MonitoringPausedAt,
		&i.MonitoringPausedBy,
		&i.MonitoringPausedReason,
		&i.MonitoringResumeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PageCacheEnabled,
		&i.ObjectCacheEnabled,
	)
	return i, err
}

const getSiteAppHealthSettings = `-- name: GetSiteAppHealthSettings :one
SELECT app_probe_path, app_alerts_disabled FROM sites
WHERE id = $1 AND tenant_id = $2
`

type GetSiteAppHealthSettingsParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetSiteAppHealthSettingsRow struct {
	AppProbePath      *string `json:"app_probe_path"`
	AppAlertsDisabled bool    `json:"app_alerts_disabled"`
}

// Tenant-scoped read of a site's app-health settings (GH #291 Phase 3):
// the B3 override path and the per-site alerting opt-out.
func (q *Queries) GetSiteAppHealthSettings(ctx context.Context, arg GetSiteAppHealthSettingsParams) (GetSiteAppHealthSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSiteAppHealthSettings, arg.ID, arg.TenantID)
	var i GetSiteAppHealthSettingsRow
	err := row.Scan(&i.AppProbePath, &i.AppAlertsDisabled)
	return i, err
}

const getSiteByAgentKey = `-- name: GetSiteByAgentKey :one

SELECT id, tenant_id, url, name, status, wp_version, php_version, agent_version, agent_public_key, enrolled_at, last_seen_at, health_status, server_info, multisite, active_theme, components, components_updated_at, tags, age_recipient, wp_timezone, wp_gmt_offset, host_provider, host_provider_org, host_provider_ip, host_provider_checked_at, connection_state, connection_generation, disconnected_at, disconnected_reason, archived_at, missed_heartbeats, client_id, app_probe_path, app_alerts_disabled, monitoring_paused_at, monitoring_paused_by, monitoring_paused_reason, monitoring_resume_at, created_at, updated_at FROM sites
WHERE agent_public_key = $1 AND agent_public_key <> ''
`

// ---------------------------------------------------------------------------
// Agent-auth path (app.agent GUC). Resolve a site by its agent public key.
// ---------------------------------------------------------------------------
func (q *Queries) GetSiteByAgentKey(ctx context.Context, agentPublicKey string) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByAgentKey, agentPublicKey)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.AgentVersion,
		&i.AgentPublicKey,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.HealthStatus,
		&i.ServerInfo,
		&i.Multisite,
		&i.ActiveTheme,
		&i.Components,
		&i.ComponentsUpdatedAt,
		&i.Tags,
		&i.AgeRecipient,
		&i.WpTimezone,
		&i.WpGmtOffset,
		&i.HostProvider,
		&i.HostProviderOrg,
		&i.HostProviderIp,
		&i.HostProviderCheckedAt,
		&i.ConnectionState,
		&i.ConnectionGeneration,
		&i.DisconnectedAt,
		&i.DisconnectedReason,
		&i.ArchivedAt,
		&i.MissedHeartbeats,
		&i.ClientID,
		&i.AppProbePath,
		&i.AppAlertsDisabled,
		&i.MonitoringPausedAt,
		&i.MonitoringPausedBy,
		&i.MonitoringPausedReason,
		&i.MonitoringResumeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteByURLForEnroll = `-- name: GetSiteByURLForEnroll :one

SELECT id, tenant_id, url, name, status, wp_version, php_version, agent_version, agent_public_key, enrolled_at, last_seen_at, health_status, server_info, multisite, active_theme, components, components_updated_at, tags, age_recipient, wp_timezone, wp_gmt_offset, host_provider, host_provider_org, host_provider_ip, host_provider_checked_at, connection_state, connection_generation, disconnected_at, disconnected_reason, archived_at, missed_heartbeats, client_id, app_probe_path, app_alerts_disabled, monitoring_paused_at, monitoring_paused_by, monitoring_paused_reason, monitoring_resume_at, created_at, updated_at FROM sites
WHERE tenant_id = $1 AND url = $2
`

type GetSiteByURLForEnrollParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Url      string    `json:"url"`
}

// ---------------------------------------------------------------------------
// Enrollment path (app.enroll GUC). These run before any tenant scope exists.
// ---------------------------------------------------------------------------
func (q *Queries) GetSiteByURLForEnroll(ctx context.Context, arg GetSiteByURLForEnrollParams) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByURLForEnroll, arg.TenantID, arg.Url)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.AgentVersion,
		&i.AgentPublicKey,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.HealthStatus,
		&i.ServerInfo,
		&i.Multisite,
		&i.ActiveTheme,
		&i.Components,
		&i.ComponentsUpdatedAt,
		&i.Tags,
		&i.AgeRecipient,
		&i.WpTimezone,
		&i.WpGmtOffset,
		&i.HostProvider,
		&i.HostProviderOrg,
		&i.HostProviderIp,
		&i.HostProviderCheckedAt,
		&i.ConnectionState,
		&i.ConnectionGeneration,
		&i.DisconnectedAt,
		&i.DisconnectedReason,
		&i.ArchivedAt,
		&i.MissedHeartbeats,
		&i.ClientID,
		&i.AppProbePath,
		&i.AppAlertsDisabled,
		&i.MonitoringPausedAt,
		&i.MonitoringPausedBy,
		&i.MonitoringPausedReason,
		&i.MonitoringResumeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSiteIDs = `-- name: ListAllSiteIDs :many
SELECT id FROM sites
WHERE tenant_id = $1
  AND connection_state <> 'archived'
ORDER BY created_at DESC
`

// Returns all non-archived site IDs for a tenant. Lightweight alternative to
// ListSites used by fleet adapters that need the full ID set without a 500-row
// cap. Excludes archived sites (connection_state = 'archived') to match the
// default ListSites behaviour.
func (q *Queries) ListAllSiteIDs(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAllSiteIDs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientNamesForSites = `-- name: ListClientNamesForSites :many
SELECT s.id AS site_id, c.id AS client_id, c.name AS client_name
FROM sites s
JOIN clients c ON c.id = s.client_id AND c.tenant_id = s.tenant_id
WHERE s.tenant_id = $1
  AND s.id = ANY($2::uuid[])
  AND s.client_id IS NOT NULL
`

type ListClientNamesForSitesParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Column2  []uuid.UUID `json:"column_2"`
}

type ListClientNamesForSitesRow struct {
	SiteID     uuid.UUID `json:"site_id"`
	ClientID   uuid.UUID `json:"client_id"`
	ClientName string    `json:"client_name"`
}

// Returns the client id + name for sites that have a client_id set (m63).
// Used to enrich the sites-list DTO with client_name in a single batched join.
func (q *Queries) ListClientNamesForSites(ctx context.Context, arg ListClientNamesForSitesParams) ([]ListClientNamesForSitesRow, error) {
	rows, err := q.db.Query(ctx, listClientNamesForSites, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientNamesForSitesRow
	for rows.Next() {
		var i ListClientNamesForSitesRow
		if err := rows.Scan(&i.SiteID, &i.ClientID, &i.ClientName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectedSiteAgentVersions = `-- name: ListConnectedSiteAgentVersions :many
SELECT agent_version
FROM sites
WHERE tenant_id = $1
  AND connection_state = 'connected'
`

// Tenant-scoped agent_version per site, restricted to connection_state =
// 'connected' (GH #381 phase 2: email failure-detection coverage). "Connected"
// here matches ListConnectedSiteIDsForScreenshot's strict definition (not
// degraded/pending/disconnected/archived): a site whose agent is not actively
// connected cannot report a delivery failure regardless of its version, so it
// is excluded from both the coverage numerator and denominator rather than
// counted as a gap.
// Version comparison happens in Go (internal/wpversion.Compare), matching
// ListSitesAgentVersions's convention: this query returns only the raw
// per-site fact.
func (q *Queries) ListConnectedSiteAgentVersions(ctx context.Context, tenantID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listConnectedSiteAgentVersions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var agent_version string
		if err := rows.Scan(&agent_version); err != nil {
			return nil, err
		}
		items = append(items, agent_version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectedSiteIDsForScreenshot = `-- name: ListConnectedSiteIDsForScreenshot :many
SELECT id, tenant_id, url FROM sites
WHERE connection_state = 'connected'
  AND enrolled_at IS NOT NULL
ORDER BY created_at DESC, id DESC
`

type ListConnectedSiteIDsForScreenshotRow struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Url      string    `json:"url"`
}

// Cross-tenant enumeration of connected sites for the weekly screenshot fanout.
// Returns only sites in the 'connected' state (not degraded/pending/archived).
// Runs under the app.agent GUC (sites_agent policy) since it spans tenants.
func (q *Queries) ListConnectedSiteIDsForScreenshot(ctx context.Context) ([]ListConnectedSiteIDsForScreenshotRow, error) {
	rows, err := q.db.Query(ctx, listConnectedSiteIDsForScreenshot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConnectedSiteIDsForScreenshotRow
	for rows.Next() {
		var i ListConnectedSiteIDsForScreenshotRow
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrolledSitesAllTenants = `-- name: ListEnrolledSitesAllTenants :many

SELECT id, tenant_id, last_seen_at, health_status FROM sites
WHERE enrolled_at IS NOT NULL
`

type ListEnrolledSitesAllTenantsRow struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	HealthStatus string             `json:"health_status"`
}

// ---------------------------------------------------------------------------
// Health-check job (runs in each enrolled site's tenant scope).
// ---------------------------------------------------------------------------
// Cross-tenant enumeration for the periodic health job. Runs under the
// app.agent GUC (sites_agent policy) since it spans tenants.
func (q *Queries) ListEnrolledSitesAllTenants(ctx context.Context) ([]ListEnrolledSitesAllTenantsRow, error) {
	rows, err := q.db.Query(ctx, listEnrolledSitesAllTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrolledSitesAllTenantsRow
	for rows.Next() {
		var i ListEnrolledSitesAllTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LastSeenAt,
			&i.HealthStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrolledSitesForProbe = `-- name: ListEnrolledSitesForProbe :many
SELECT id, tenant_id, url, health_status, last_seen_at, app_probe_path, app_alerts_disabled, connection_state FROM sites
WHERE enrolled_at IS NOT NULL
`

type ListEnrolledSitesForProbeRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	Url               string             `json:"url"`
	HealthStatus      string             `json:"health_status"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	AppProbePath      *string            `json:"app_probe_path"`
	AppAlertsDisabled bool               `json:"app_alerts_disabled"`
	ConnectionState   string             `json:"connection_state"`
}

// Cross-tenant enumeration of enrolled sites WITH their URL for the M5 uptime
// probe job. Runs under the app.agent GUC (sites_agent policy) since it spans
// tenants. Only enrolled sites have an agent URL worth probing.
// last_seen_at and app_probe_path (m107, GH #291 Phase 2) are carried for the
// application-health prober: B0 (agent ground truth) reads last_seen_at, B3
// (per-site override) reads app_probe_path. app_alerts_disabled (m108, GH
// #291 Phase 3) is carried so the app-alert transition step can skip a site
// whose operator disabled app ALERTING (the probe itself still runs).
// connection_state (GH #291 Phase 3 Fix 2) is carried for the SAME app-alert
// transition step, so it can exclude a revoked/archived site using the
// IDENTICAL predicate GetTenantAppAlertRatio's WHERE clause enforces
// server-side (see uptime.appAlertEligible) - the fire path and the fleet
// circuit breaker's ratio must never disagree about which sites count. The
// reachability probe and the cron-kicker ignore all four.
func (q *Queries) ListEnrolledSitesForProbe(ctx context.Context) ([]ListEnrolledSitesForProbeRow, error) {
	rows, err := q.db.Query(ctx, listEnrolledSitesForProbe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrolledSitesForProbeRow
	for rows.Next() {
		var i ListEnrolledSitesForProbeRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.HealthStatus,
			&i.LastSeenAt,
			&i.AppProbePath,
			&i.AppAlertsDisabled,
			&i.ConnectionState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestBackupsForSites = `-- name: ListLatestBackupsForSites :many
SELECT DISTINCT ON (site_id)
       site_id, status, finished_at, created_at
FROM backup_snapshots
WHERE tenant_id = $1 AND site_id = ANY($2::uuid[])
ORDER BY site_id, created_at DESC
`

type ListLatestBackupsForSitesParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Column2  []uuid.UUID `json:"column_2"`
}

type ListLatestBackupsForSitesRow struct {
	SiteID     uuid.UUID          `json:"site_id"`
	Status     string             `json:"status"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

// The most-recent backup snapshot per site, for the sites-table "Backup" column.
// DISTINCT ON + ORDER BY (site_id, created_at DESC) is served by
// backup_snapshots_tenant_site_idx (tenant_id, site_id, created_at DESC) — one
// index-only seek per site, fetched in a single batched call for the listed ids.
func (q *Queries) ListLatestBackupsForSites(ctx context.Context, arg ListLatestBackupsForSitesParams) ([]ListLatestBackupsForSitesRow, error) {
	rows, err := q.db.Query(ctx, listLatestBackupsForSites, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestBackupsForSitesRow
	for rows.Next() {
		var i ListLatestBackupsForSitesRow
		if err := rows.Scan(
			&i.SiteID,
			&i.Status,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSites = `-- name: ListSites :many
SELECT s.id, s.tenant_id, s.url, s.name, s.status, s.wp_version, s.php_version, s.agent_version, s.agent_public_key, s.enrolled_at, s.last_seen_at, s.health_status, s.server_info, s.multisite, s.active_theme, s.components, s.components_updated_at, s.tags, s.age_recipient, s.wp_timezone, s.wp_gmt_offset, s.host_provider, s.host_provider_org, s.host_provider_ip, s.host_provider_checked_at, s.connection_state, s.connection_generation, s.disconnected_at, s.disconnected_reason, s.archived_at, s.missed_heartbeats, s.client_id, s.app_probe_path, s.app_alerts_disabled, s.monitoring_paused_at, s.monitoring_paused_by, s.monitoring_paused_reason, s.monitoring_resume_at, s.created_at, s.updated_at,
       COALESCE(pc.cache_enabled, false) AS page_cache_enabled,
       COALESCE(oc.enabled, false) AS object_cache_enabled
FROM sites s
LEFT JOIN site_perf_config pc
    ON pc.site_id = s.id AND pc.tenant_id = s.tenant_id
LEFT JOIN site_object_cache_config oc
    ON oc.site_id = s.id AND oc.tenant_id = s.tenant_id
WHERE s.tenant_id = $1
  AND ($4::text[] IS NULL OR s.tags && $4::text[])
  AND ($5::text[] IS NULL OR s.tags @> $5::text[])
  AND (
        ($6::text IS NULL AND s.connection_state <> 'archived')
        OR $6::text = s.connection_state
      )
  AND ($7::uuid IS NULL OR s.client_id = $7::uuid)
  AND (
        $8::text IS NULL
        OR strpos(lower(s.name), lower($8::text)) > 0
        OR strpos(lower(s.url), lower($8::text)) > 0
        OR EXISTS (
             SELECT 1 FROM unnest(s.tags) AS tg(tag)
             WHERE strpos(lower(tg.tag), lower($8::text)) > 0
           )
      )
ORDER BY
    CASE WHEN $9::text = 'name'        THEN lower(s.name)  END ASC,
    CASE WHEN $9::text = '-name'       THEN lower(s.name)  END DESC,
    CASE WHEN $9::text = 'created_at'  THEN s.created_at   END ASC,
    CASE WHEN $9::text = '-created_at' THEN s.created_at   END DESC,
    CASE WHEN $9::text = 'last_seen'   THEN s.last_seen_at END ASC NULLS LAST,
    CASE WHEN $9::text = '-last_seen'  THEN s.last_seen_at END DESC NULLS LAST,
    s.id DESC
LIMIT $2 OFFSET $3
`

type ListSitesParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	AnyTags  []string    `json:"any_tags"`
	AllTags  []string    `json:"all_tags"`
	State    *string     `json:"state"`
	ClientID pgtype.UUID `json:"client_id"`
	Q        *string     `json:"q"`
	Sort     string      `json:"sort"`
}

type ListSitesRow struct {
	ID                     uuid.UUID          `json:"id"`
	TenantID               uuid.UUID          `json:"tenant_id"`
	Url                    string             `json:"url"`
	Name                   string             `json:"name"`
	Status                 string             `json:"status"`
	WpVersion              string             `json:"wp_version"`
	PhpVersion             string             `json:"php_version"`
	AgentVersion           string             `json:"agent_version"`
	AgentPublicKey         string             `json:"agent_public_key"`
	EnrolledAt             pgtype.Timestamptz `json:"enrolled_at"`
	LastSeenAt             pgtype.Timestamptz `json:"last_seen_at"`
	HealthStatus           string             `json:"health_status"`
	ServerInfo             string             `json:"server_info"`
	Multisite              bool               `json:"multisite"`
	ActiveTheme            string             `json:"active_theme"`
	Components             []byte             `json:"components"`
	ComponentsUpdatedAt    pgtype.Timestamptz `json:"components_updated_at"`
	Tags                   []string           `json:"tags"`
	AgeRecipient           string             `json:"age_recipient"`
	WpTimezone             string             `json:"wp_timezone"`
	WpGmtOffset            float32            `json:"wp_gmt_offset"`
	HostProvider           string             `json:"host_provider"`
	HostProviderOrg        string             `json:"host_provider_org"`
	HostProviderIp         string             `json:"host_provider_ip"`
	HostProviderCheckedAt  pgtype.Timestamptz `json:"host_provider_checked_at"`
	ConnectionState        string             `json:"connection_state"`
	ConnectionGeneration   int32              `json:"connection_generation"`
	DisconnectedAt         pgtype.Timestamptz `json:"disconnected_at"`
	DisconnectedReason     *string            `json:"disconnected_reason"`
	ArchivedAt             pgtype.Timestamptz `json:"archived_at"`
	MissedHeartbeats       int32              `json:"missed_heartbeats"`
	ClientID               pgtype.UUID        `json:"client_id"`
	AppProbePath           *string            `json:"app_probe_path"`
	AppAlertsDisabled      bool               `json:"app_alerts_disabled"`
	MonitoringPausedAt     pgtype.Timestamptz `json:"monitoring_paused_at"`
	MonitoringPausedBy     pgtype.UUID        `json:"monitoring_paused_by"`
	MonitoringPausedReason string             `json:"monitoring_paused_reason"`
	MonitoringResumeAt     pgtype.Timestamptz `json:"monitoring_resume_at"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	PageCacheEnabled       bool               `json:"page_cache_enabled"`
	ObjectCacheEnabled     bool               `json:"object_cache_enabled"`
}

// Defaults to hiding archived sites (ADR-041). When sqlc.narg('state') is set
// the list is filtered to exactly that connection_state (e.g. 'archived' for
// the archived chip); when it is NULL every non-archived site is returned.
// When sqlc.narg('client_id') is set only sites belonging to that client are returned (m63).
// M100 (GH #230 "rich tags"): any_tags (tags && ...) and all_tags (tags @> ...)
// replace the single-tag filter; both are served by the sites_tags_idx GIN
// index. The service maps exactly ONE of them per request (legacy ?tag=
// becomes any_tags=[tag]).
// GH #243: page_cache_enabled / object_cache_enabled — see GetSite's comment
// above. Both LEFT JOINs are PK lookups (site_id), so this stays O(sites) per
// page (an index-only nested-loop per row) and does not regress the
// optimized /sites path.
//
// GH #349 free-text search + ordering. Both moved SERVER side on purpose: the
// web used to filter an already-fetched page client side, which silently
// searched only the first page (50 newest sites by default) and told an agency
// with more sites than that "no results" for a site it owns. A filter applied
// after the server truncated the list is wrong at any page size.
//
//	sqlc.narg('q') substring-matches, case-insensitively, the site NAME, the
//	site URL, or ANY of the site's tags. The tag arm reads s.tags, the very
//	array this query returns, so any tag the operator can see on a site is a
//	tag they can find that site by. strpos(lower(..), lower(..)) is used
//	rather than ILIKE because the operator typed a search string, not a
//	pattern: with ILIKE a literal % or _ in the query would silently become a
//	wildcard. NULL (absent) disables the whole predicate.
//
//	sqlc.arg('sort') selects the order. It is BOUND AS A PARAMETER and
//	compared against fixed literals; no SQL text is ever concatenated, and the
//	set of accepted values is closed in Go (site.ParseListSort, which 422s an
//	unrecognised value rather than silently falling back). Every branch that
//	is not the selected sort evaluates to NULL for every row, which makes that
//	ORDER BY term a constant and therefore a no-op, so one query serves all
//	six orders.
//	  - lower(s.name) sorts names case-insensitively, so "acme" and "Acme"
//	    sit together regardless of the server's collation.
//	  - NULLS LAST on BOTH last_seen directions: last_seen_at is NULL for a
//	    site that has never reported in. Never-seen sites therefore land at
//	    the END of the list in either direction, never crowding the top of a
//	    descending "most recently seen" sort, and never vanishing.
//	  - s.id DESC is the TOTAL-ORDER tiebreak. Two sites can share a name and
//	    two can share a created_at; without a final unique key, LIMIT/OFFSET
//	    paging is free to drop one row and repeat another across pages.
func (q *Queries) ListSites(ctx context.Context, arg ListSitesParams) ([]ListSitesRow, error) {
	rows, err := q.db.Query(ctx, listSites,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.AnyTags,
		arg.AllTags,
		arg.State,
		arg.ClientID,
		arg.Q,
		arg.Sort,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSitesRow
	for rows.Next() {
		var i ListSitesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Name,
			&i.Status,
			&i.WpVersion,
			&i.PhpVersion,
			&i.AgentVersion,
			&i.AgentPublicKey,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.HealthStatus,
			&i.ServerInfo,
			&i.Multisite,
			&i.ActiveTheme,
			&i.Components,
			&i.ComponentsUpdatedAt,
			&i.Tags,
			&i.AgeRecipient,
			&i.WpTimezone,
			&i.WpGmtOffset,
			&i.HostProvider,
			&i.HostProviderOrg,
			&i.HostProviderIp,
			&i.HostProviderCheckedAt,
			&i.ConnectionState,
			&i.ConnectionGeneration,
			&i.DisconnectedAt,
			&i.DisconnectedReason,
			&i.ArchivedAt,
			&i.MissedHeartbeats,
			&i.ClientID,
			&i.AppProbePath,
			&i.AppAlertsDisabled,
			&i.MonitoringPausedAt,
			&i.MonitoringPausedBy,
			&i.MonitoringPausedReason,
			&i.MonitoringResumeAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PageCacheEnabled,
			&i.ObjectCacheEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitesAgentVersions = `-- name: ListSitesAgentVersions :many
SELECT
    s.id,
    s.name,
    s.agent_version,
    COALESCE((
        SELECT jsonb_agg(jsonb_build_object('slug', p ->> 'slug', 'name', p ->> 'name'))
        FROM jsonb_array_elements(
            CASE WHEN jsonb_typeof(s.components -> 'plugins') = 'array'
                 THEN s.components -> 'plugins'
                 ELSE '[]'::jsonb
            END
        ) AS p
    ), '[]'::jsonb)::jsonb AS plugin_identities
FROM sites s
WHERE s.tenant_id = $1
  AND s.connection_state <> 'archived'
ORDER BY s.name
`

type ListSitesAgentVersionsRow struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	AgentVersion     string    `json:"agent_version"`
	PluginIdentities []byte    `json:"plugin_identities"`
}

// Tenant-scoped site_id/name/agent_version rollup for the read-only agent
// fleet-version dashboard (internal/agentrelease): "how many of my sites are
// running an outdated agent?". Excludes archived sites, matching the
// ListSites/ListAllSiteIDs default (ADR-041). Classification against the
// currently published version happens in Go (internal/agentrelease.Classify);
// this query only returns the raw per-site facts.
//
// plugin_identities is a narrow {slug,name} projection of the site's plugin
// inventory, carrying just enough for Go to recognize which build of the agent
// the site runs (internal/agentplugin.DistributionOf): the plugin-directory
// build cannot self-update, so its sites are classified ineligible instead of
// being reported outdated forever against a channel they cannot consume.
// The projection is deliberate: shipping the whole components document would
// move megabytes per dashboard load on a large fleet, and matching the agent's
// identity in SQL would duplicate literals that must live in exactly one place.
// The CASE guards a components document whose "plugins" key is absent or is not
// an array, which jsonb_array_elements would otherwise error on.
func (q *Queries) ListSitesAgentVersions(ctx context.Context, tenantID uuid.UUID) ([]ListSitesAgentVersionsRow, error) {
	rows, err := q.db.Query(ctx, listSitesAgentVersions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSitesAgentVersionsRow
	for rows.Next() {
		var i ListSitesAgentVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AgentVersion,
			&i.PluginIdentities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitesForMCPScope = `-- name: ListSitesForMCPScope :many
SELECT s.id, s.tenant_id, s.url, s.name, s.status, s.wp_version, s.php_version, s.agent_version, s.agent_public_key, s.enrolled_at, s.last_seen_at, s.health_status, s.server_info, s.multisite, s.active_theme, s.components, s.components_updated_at, s.tags, s.age_recipient, s.wp_timezone, s.wp_gmt_offset, s.host_provider, s.host_provider_org, s.host_provider_ip, s.host_provider_checked_at, s.connection_state, s.connection_generation, s.disconnected_at, s.disconnected_reason, s.archived_at, s.missed_heartbeats, s.client_id, s.app_probe_path, s.app_alerts_disabled, s.monitoring_paused_at, s.monitoring_paused_by, s.monitoring_paused_reason, s.monitoring_resume_at, s.created_at, s.updated_at
FROM sites s
WHERE s.tenant_id = $1
  AND s.id = ANY($2::uuid[])
  AND s.connection_state <> 'archived'
ORDER BY lower(s.name) ASC, s.id DESC
LIMIT $3
`

type ListSitesForMCPScopeParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	SiteIds  []uuid.UUID `json:"site_ids"`
	RowLimit int32       `json:"row_limit"`
}

// The assistant surface's site read (internal/mcp). It exists so that the row
// bound is taken over THE CALLER'S OWN SCOPE and never over the tenant.
//
// What it replaces: internal/mcp read ListSites over the whole tenant with
// Limit = bound+1 and Sort = 'name', then applied the connection's site scope
// in Go AFTERWARDS. An in-scope site whose name sorted past the tenant's first
// page was therefore never in the rows the filter ran over. The order is
// deterministic, so no number of retries could ever produce it, and the caller
// was told to retry. Worse, the shortfall could only arise once the TENANT held
// more rows than the bound, so its arrival was a fact about sites the caller is
// not entitled to know exist.
//
// WHY THIS IS A SEPARATE QUERY AND NOT A NULLABLE ARM ON ListSites.
// The alternative was sqlc.narg('site_ids') on ListSites, read as "NULL means
// no scope filter" so the dashboard's callers keep working untouched. Reject it,
// and the reason is specific rather than stylistic: for an ARRAY parameter sqlc
// emits the same Go type, []uuid.UUID, for sqlc.arg and sqlc.narg alike, because
// a Go slice is already nullable. The two options are therefore INDISTINGUISHABLE
// AT THE CALL SITE and differ only in what a nil slice means. On the narg arm nil
// means the whole tenant; here nil means zero rows, because `id = ANY(NULL::uuid[])`
// evaluates to NULL and `id = ANY('{}'::uuid[])` evaluates to false, and WHERE
// keeps neither. One identical mistake -- a scope set lost on an error path, a
// struct field left unassigned -- returns the fleet in one design and nothing in
// the other. That asymmetry is the whole justification for a second query over
// this table.
//
// It is not a copy of ListSites and must not become one. This surface has one
// order and no filters, so there is deliberately no state/client_id/any_tags/
// all_tags/q arm here to drift out of step with the dashboard's. ListSites is
// unchanged by this addition.
//
// No LEFT JOINs. ListSites carries site_perf_config and site_object_cache_config
// for the dashboard's cache badges; internal/mcp's toSiteRecord reads neither
// column, so joining them here would buy two index lookups per row, across the
// whole page, to produce two values nobody reads. `SELECT s.*` also means sqlc
// returns the shared `Site` model rather than a bespoke row struct.
//
// The scope predicate is defense in depth and NOT the only gate, but it is the
// one that cannot be forgotten. `sites` carries the RESTRICTIVE sites_site_scope
// policy (m19, 20260531050000_m19_orgs_sharing.sql:330), whose USING clause is
// `app.site_scope <> 'on' OR id = ANY(app.allowed_site_ids)`. That is permissive
// whenever the GUC is unset -- correct, because the dashboard's org-scoped
// callers must not be filtered -- which also means the policy is inert for any
// caller that opens its transaction with InTenantTx rather than RunTenantTx.
// This predicate holds under either helper.
//
// ORDER BY reproduces ListSites' 'name' sort exactly: lower(s.name) so "acme"
// and "Acme" sit together whatever the server's collation, then s.id DESC as the
// total-order tiebreak, without which two sites sharing a name are free to swap
// places between calls. Archived sites are excluded to match ListSites' default
// (ADR-041), which is what this surface was getting before.
func (q *Queries) ListSitesForMCPScope(ctx context.Context, arg ListSitesForMCPScopeParams) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSitesForMCPScope, arg.TenantID, arg.SiteIds, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Name,
			&i.Status,
			&i.WpVersion,
			&i.PhpVersion,
			&i.AgentVersion,
			&i.AgentPublicKey,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.HealthStatus,
			&i.ServerInfo,
			&i.Multisite,
			&i.ActiveTheme,
			&i.Components,
			&i.ComponentsUpdatedAt,
			&i.Tags,
			&i.AgeRecipient,
			&i.WpTimezone,
			&i.WpGmtOffset,
			&i.HostProvider,
			&i.HostProviderOrg,
			&i.HostProviderIp,
			&i.HostProviderCheckedAt,
			&i.ConnectionState,
			&i.ConnectionGeneration,
			&i.DisconnectedAt,
			&i.DisconnectedReason,
			&i.ArchivedAt,
			&i.MissedHeartbeats,
			&i.ClientID,
			&i.AppProbePath,
			&i.AppAlertsDisabled,
			&i.MonitoringPausedAt,
			&i.MonitoringPausedBy,
			&i.MonitoringPausedReason,
			&i.MonitoringResumeAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSiteUnreachable = `-- name: MarkSiteUnreachable :execrows
UPDATE sites
SET health_status = 'unreachable', updated_at = now()
WHERE id = $1 AND health_status <> 'unreachable'
`

// Marks a site unreachable. Runs under app.agent GUC (cross-tenant job).
func (q *Queries) MarkSiteUnreachable(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSiteUnreachable, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSiteAgeRecipient = `-- name: SetSiteAgeRecipient :one
UPDATE sites
SET age_recipient = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, url, name, status, wp_version, php_version, agent_version, agent_public_key, enrolled_at, last_seen_at, health_status, server_info, multisite, active_theme, components, components_updated_at, tags, age_recipient, wp_timezone, wp_gmt_offset, host_provider, host_provider_org, host_provider_ip, host_provider_checked_at, connection_state, connection_generation, disconnected_at, disconnected_reason, archived_at, missed_heartbeats, client_id, app_probe_path, app_alerts_disabled, monitoring_paused_at, monitoring_paused_by, monitoring_paused_reason, monitoring_resume_at, created_at, updated_at
`

type SetSiteAgeRecipientParams struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	AgeRecipient string    `json:"age_recipient"`
}

// Stores the per-site age PUBLIC recipient backups are encrypted to. The CP
// never holds the matching identity (private key); it cannot decrypt backups.
func (q *Queries) SetSiteAgeRecipient(ctx context.Context, arg SetSiteAgeRecipientParams) (Site, error) {
	row := q.db.QueryRow(ctx, setSiteAgeRecipient, arg.ID, arg.TenantID, arg.AgeRecipient)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.AgentVersion,
		&i.AgentPublicKey,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.HealthStatus,
		&i.ServerInfo,
		&i.Multisite,
		&i.ActiveTheme,
		&i.Components,
		&i.ComponentsUpdatedAt,
		&i.Tags,
		&i.AgeRecipient,
		&i.WpTimezone,
		&i.WpGmtOffset,
		&i.HostProvider,
		&i.HostProviderOrg,
		&i.HostProviderIp,
		&i.HostProviderCheckedAt,
		&i.ConnectionState,
		&i.ConnectionGeneration,
		&i.DisconnectedAt,
		&i.DisconnectedReason,
		&i.ArchivedAt,
		&i.MissedHeartbeats,
		&i.ClientID,
		&i.AppProbePath,
		&i.AppAlertsDisabled,
		&i.MonitoringPausedAt,
		&i.MonitoringPausedBy,
		&i.MonitoringPausedReason,
		&i.MonitoringResumeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSiteHealthStatus = `-- name: SetSiteHealthStatus :execrows
UPDATE sites
SET health_status = $2, updated_at = now()
WHERE id = $1 AND health_status <> $2
`

type SetSiteHealthStatusParams struct {
	ID           uuid.UUID `json:"id"`
	HealthStatus string    `json:"health_status"`
}

// Sets a site's health_status from an M5 probe result (cross-tenant probe job,
// app.agent GUC). Only writes when the value actually changes to avoid churn.
func (q *Queries) SetSiteHealthStatus(ctx context.Context, arg SetSiteHealthStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSiteHealthStatus, arg.ID, arg.HealthStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSiteTags = `-- name: SetSiteTags :one
UPDATE sites
SET tags = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, url, name, status, wp_version, php_version, agent_version, agent_public_key, enrolled_at, last_seen_at, health_status, server_info, multisite, active_theme, components, components_updated_at, tags, age_recipient, wp_timezone, wp_gmt_offset, host_provider, host_provider_org, host_provider_ip, host_provider_checked_at, connection_state, connection_generation, disconnected_at, disconnected_reason, archived_at, missed_heartbeats, client_id, app_probe_path, app_alerts_disabled, monitoring_paused_at, monitoring_paused_by, monitoring_paused_reason, monitoring_resume_at, created_at, updated_at
`

type SetSiteTagsParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Tags     []string  `json:"tags"`
}

func (q *Queries) SetSiteTags(ctx context.Context, arg SetSiteTagsParams) (Site, error) {
	row := q.db.QueryRow(ctx, setSiteTags, arg.ID, arg.TenantID, arg.Tags)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.AgentVersion,
		&i.AgentPublicKey,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.HealthStatus,
		&i.ServerInfo,
		&i.Multisite,
		&i.ActiveTheme,
		&i.Components,
		&i.ComponentsUpdatedAt,
		&i.Tags,
		&i.AgeRecipient,
		&i.WpTimezone,
		&i.WpGmtOffset,
		&i.HostProvider,
		&i.HostProviderOrg,
		&i.HostProviderIp,
		&i.HostProviderCheckedAt,
		&i.ConnectionState,
		&i.ConnectionGeneration,
		&i.DisconnectedAt,
		&i.DisconnectedReason,
		&i.ArchivedAt,
		&i.MissedHeartbeats,
		&i.ClientID,
		&i.AppProbePath,
		&i.AppAlertsDisabled,
		&i.MonitoringPausedAt,
		&i.MonitoringPausedBy,
		&i.MonitoringPausedReason,
		&i.MonitoringResumeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSiteSeen = `-- name: TouchSiteSeen :one
UPDATE sites
SET last_seen_at = now(),
    health_status = 'healthy',
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, url, name, status, wp_version, php_version, agent_version, agent_public_key, enrolled_at, last_seen_at, health_status, server_info, multisite, active_theme, components, components_updated_at, tags, age_recipient, wp_timezone, wp_gmt_offset, host_provider, host_provider_org, host_provider_ip, host_provider_checked_at, connection_state, connection_generation, disconnected_at, disconnected_reason, archived_at, missed_heartbeats, client_id, app_probe_path, app_alerts_disabled, monitoring_paused_at, monitoring_paused_by, monitoring_paused_reason, monitoring_resume_at, created_at, updated_at
`

type TouchSiteSeenParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) TouchSiteSeen(ctx context.Context, arg TouchSiteSeenParams) (Site, error) {
	row := q.db.QueryRow(ctx, touchSiteSeen, arg.ID, arg.TenantID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.AgentVersion,
		&i.AgentPublicKey,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.HealthStatus,
		&i.ServerInfo,
		&i.Multisite,
		&i.ActiveTheme,
		&i.Components,
		&i.ComponentsUpdatedAt,
		&i.Tags,
		&i.AgeRecipient,
		&i.WpTimezone,
		&i.WpGmtOffset,
		&i.HostProvider,
		&i.HostProviderOrg,
		&i.HostProviderIp,
		&i.HostProviderCheckedAt,
		&i.ConnectionState,
		&i.ConnectionGeneration,
		&i.DisconnectedAt,
		&i.DisconnectedReason,
		&i.ArchivedAt,
		&i.MissedHeartbeats,
		&i.ClientID,
		&i.AppProbePath,
		&i.AppAlertsDisabled,
		&i.MonitoringPausedAt,
		&i.MonitoringPausedBy,
		&i.MonitoringPausedReason,
		&i.MonitoringResumeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteAppHealthSettings = `-- name: UpdateSiteAppHealthSettings :one
UPDATE sites
SET app_probe_path = $1,
    app_alerts_disabled = $2,
    updated_at = now()
WHERE id = $3 AND tenant_id = $4
RETURNING app_probe_path, app_alerts_disabled
`

type UpdateSiteAppHealthSettingsParams struct {
	AppProbePath      *string   `json:"app_probe_path"`
	AppAlertsDisabled bool      `json:"app_alerts_disabled"`
	ID                uuid.UUID `json:"id"`
	TenantID          uuid.UUID `json:"tenant_id"`
}

type UpdateSiteAppHealthSettingsRow struct {
	AppProbePath      *string `json:"app_probe_path"`
	AppAlertsDisabled bool    `json:"app_alerts_disabled"`
}

// Tenant-scoped write of a site's app-health settings (GH #291 Phase 3).
// app_probe_path is sqlc.narg so an empty override clears back to
// auto-detect (NULL); the service layer is responsible for path validation
// (site-relative, no scheme/host/traversal - see uptime.ValidateAppProbePath).
func (q *Queries) UpdateSiteAppHealthSettings(ctx context.Context, arg UpdateSiteAppHealthSettingsParams) (UpdateSiteAppHealthSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateSiteAppHealthSettings,
		arg.AppProbePath,
		arg.AppAlertsDisabled,
		arg.ID,
		arg.TenantID,
	)
	var i UpdateSiteAppHealthSettingsRow
	err := row.Scan(&i.AppProbePath, &i.AppAlertsDisabled)
	return i, err
}

const updateSiteMetadata = `-- name: UpdateSiteMetadata :one
UPDATE sites
SET wp_version   = $3,
    php_version  = $4,
    server_info  = $5,
    multisite    = $6,
    active_theme = $7,
    agent_version = $8,
    components   = $9,
    components_updated_at = now(),
    last_seen_at = now(),
    health_status = 'healthy',
    updated_at   = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, url, name, status, wp_version, php_version, agent_version, agent_public_key, enrolled_at, last_seen_at, health_status, server_info, multisite, active_theme, components, components_updated_at, tags, age_recipient, wp_timezone, wp_gmt_offset, host_provider, host_provider_org, host_provider_ip, host_provider_checked_at, connection_state, connection_generation, disconnected_at, disconnected_reason, archived_at, missed_heartbeats, client_id, app_probe_path, app_alerts_disabled, monitoring_paused_at, monitoring_paused_by, monitoring_paused_reason, monitoring_resume_at, created_at, updated_at
`

type UpdateSiteMetadataParams struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	WpVersion    string    `json:"wp_version"`
	PhpVersion   string    `json:"php_version"`
	ServerInfo   string    `json:"server_info"`
	Multisite    bool      `json:"multisite"`
	ActiveTheme  string    `json:"active_theme"`
	AgentVersion string    `json:"agent_version"`
	Components   []byte    `json:"components"`
}

// Tenant-scoped metadata update (used by the agent path inside the resolved
// site's own tenant scope).
//
// m121 (GH #553): this is the ONLY statement in the tree that writes
// sites.components, so it is the only one that may write
// components_updated_at. Verified by grepping every db/query/*.sql and every
// raw UPDATE/INSERT on sites in non-test Go; the other two raw writers
// (diagnostics.UpdateSiteTimezone, diagnostics.SetSiteHostProvider) touch
// neither column. The two must move together: a write of components without
// its stamp re-creates the undated-inventory bug, and a write of the stamp
// without components would date an inventory that was not refreshed.
//
// It is now() on the CONTROL PLANE, not the agent's collection instant, and it
// is written on every push even when the document is unchanged -- "as of T this
// was the inventory" is a truer statement than the previous stamp regardless.
//
// NOTE FOR THE HEARTBEAT: TouchSiteHeartbeat (db/query/site_connection.sql)
// must NEVER add this column. Bumping updated_at on a 60s heartbeat that does
// not touch components is the whole of GH #553.
func (q *Queries) UpdateSiteMetadata(ctx context.Context, arg UpdateSiteMetadataParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSiteMetadata,
		arg.ID,
		arg.TenantID,
		arg.WpVersion,
		arg.PhpVersion,
		arg.ServerInfo,
		arg.Multisite,
		arg.ActiveTheme,
		arg.AgentVersion,
		arg.Components,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.WpVersion,
		&i.PhpVersion,
		&i.AgentVersion,
		&i.AgentPublicKey,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.HealthStatus,
		&i.ServerInfo,
		&i.Multisite,
		&i.ActiveTheme,
		&i.Components,
		&i.ComponentsUpdatedAt,
		&i.Tags,
		&i.AgeRecipient,
		&i.WpTimezone,
		&i.WpGmtOffset,
		&i.HostProvider,
		&i.HostProviderOrg,
		&i.HostProviderIp,
		&i.HostProviderCheckedAt,
		&i.ConnectionState,
		&i.ConnectionGeneration,
		&i.DisconnectedAt,
		&i.DisconnectedReason,
		&i.ArchivedAt,
		&i.MissedHeartbeats,
		&i.ClientID,
		&i.AppProbePath,
		&i.AppAlertsDisabled,
		&i.MonitoringPausedAt,
		&i.MonitoringPausedBy,
		&i.MonitoringPausedReason,
		&i.MonitoringResumeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
