/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptRouteImport } from './routes/accept'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedVulnerabilitiesRouteImport } from './routes/_authed/vulnerabilities'
import { Route as AuthedUptimeRouteImport } from './routes/_authed/uptime'
import { Route as AuthedSharedWithMeRouteImport } from './routes/_authed/shared-with-me'
import { Route as AuthedPerformanceRouteImport } from './routes/_authed/performance'
import { Route as AuthedMigrationsRouteImport } from './routes/_authed/migrations'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedUpdatesIndexRouteImport } from './routes/_authed/updates/index'
import { Route as AuthedSitesIndexRouteImport } from './routes/_authed/sites/index'
import { Route as AuthedBackupsIndexRouteImport } from './routes/_authed/backups/index'
import { Route as AuthedUpdatesRunIdRouteImport } from './routes/_authed/updates/$runId'
import { Route as AuthedSitesSiteIdRouteImport } from './routes/_authed/sites/$siteId'
import { Route as AuthedSettingsOrganizationRouteImport } from './routes/_authed/settings/organization'
import { Route as AuthedSettingsMembersRouteImport } from './routes/_authed/settings/members'
import { Route as AuthedSettingsDestinationsRouteImport } from './routes/_authed/settings/destinations'
import { Route as AuthedSettingsApiKeysRouteImport } from './routes/_authed/settings/api-keys'
import { Route as AuthedSettingsAlertsRouteImport } from './routes/_authed/settings/alerts'
import { Route as AuthedSettingsAccountRouteImport } from './routes/_authed/settings/account'
import { Route as AuthedScheduleRunsRunIdRouteImport } from './routes/_authed/schedule-runs/$runId'
import { Route as AuthedRestoresRestoreIdRouteImport } from './routes/_authed/restores/$restoreId'
import { Route as AuthedBackupsSnapshotIdRouteImport } from './routes/_authed/backups/$snapshotId'
import { Route as AuthedSitesSiteIdIndexRouteImport } from './routes/_authed/sites/$siteId.index'
import { Route as AuthedSitesSiteIdUpdatesRouteImport } from './routes/_authed/sites/$siteId.updates'
import { Route as AuthedSitesSiteIdSettingsRouteImport } from './routes/_authed/sites/$siteId.settings'
import { Route as AuthedSitesSiteIdSecurityRouteImport } from './routes/_authed/sites/$siteId.security'
import { Route as AuthedSitesSiteIdMediaRouteImport } from './routes/_authed/sites/$siteId.media'
import { Route as AuthedSitesSiteIdHealthRouteImport } from './routes/_authed/sites/$siteId.health'
import { Route as AuthedSitesSiteIdErrorsRouteImport } from './routes/_authed/sites/$siteId.errors'
import { Route as AuthedSitesSiteIdBackupsRouteImport } from './routes/_authed/sites/$siteId.backups'
import { Route as AuthedSitesSiteIdActivityRouteImport } from './routes/_authed/sites/$siteId.activity'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptRoute = AcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVulnerabilitiesRoute = AuthedVulnerabilitiesRouteImport.update({
  id: '/vulnerabilities',
  path: '/vulnerabilities',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUptimeRoute = AuthedUptimeRouteImport.update({
  id: '/uptime',
  path: '/uptime',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSharedWithMeRoute = AuthedSharedWithMeRouteImport.update({
  id: '/shared-with-me',
  path: '/shared-with-me',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPerformanceRoute = AuthedPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMigrationsRoute = AuthedMigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUpdatesIndexRoute = AuthedUpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSitesIndexRoute = AuthedSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBackupsIndexRoute = AuthedBackupsIndexRouteImport.update({
  id: '/backups/',
  path: '/backups/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUpdatesRunIdRoute = AuthedUpdatesRunIdRouteImport.update({
  id: '/updates/$runId',
  path: '/updates/$runId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSitesSiteIdRoute = AuthedSitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsOrganizationRoute =
  AuthedSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsMembersRoute = AuthedSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsDestinationsRoute =
  AuthedSettingsDestinationsRouteImport.update({
    id: '/settings/destinations',
    path: '/settings/destinations',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsApiKeysRoute = AuthedSettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsAlertsRoute = AuthedSettingsAlertsRouteImport.update({
  id: '/settings/alerts',
  path: '/settings/alerts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsAccountRoute = AuthedSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRunsRunIdRoute = AuthedScheduleRunsRunIdRouteImport.update({
  id: '/schedule-runs/$runId',
  path: '/schedule-runs/$runId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRestoresRestoreIdRoute = AuthedRestoresRestoreIdRouteImport.update({
  id: '/restores/$restoreId',
  path: '/restores/$restoreId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBackupsSnapshotIdRoute = AuthedBackupsSnapshotIdRouteImport.update({
  id: '/backups/$snapshotId',
  path: '/backups/$snapshotId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSitesSiteIdIndexRoute = AuthedSitesSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSitesSiteIdRoute,
} as any)
const AuthedSitesSiteIdUpdatesRoute =
  AuthedSitesSiteIdUpdatesRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => AuthedSitesSiteIdRoute,
  } as any)
const AuthedSitesSiteIdSettingsRoute =
  AuthedSitesSiteIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedSitesSiteIdRoute,
  } as any)
const AuthedSitesSiteIdSecurityRoute =
  AuthedSitesSiteIdSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthedSitesSiteIdRoute,
  } as any)
const AuthedSitesSiteIdMediaRoute = AuthedSitesSiteIdMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthedSitesSiteIdRoute,
} as any)
const AuthedSitesSiteIdHealthRoute = AuthedSitesSiteIdHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthedSitesSiteIdRoute,
} as any)
const AuthedSitesSiteIdErrorsRoute = AuthedSitesSiteIdErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AuthedSitesSiteIdRoute,
} as any)
const AuthedSitesSiteIdBackupsRoute =
  AuthedSitesSiteIdBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AuthedSitesSiteIdRoute,
  } as any)
const AuthedSitesSiteIdActivityRoute =
  AuthedSitesSiteIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthedSitesSiteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept': typeof AcceptRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/audit': typeof AuthedAuditRoute
  '/migrations': typeof AuthedMigrationsRoute
  '/performance': typeof AuthedPerformanceRoute
  '/shared-with-me': typeof AuthedSharedWithMeRoute
  '/uptime': typeof AuthedUptimeRoute
  '/vulnerabilities': typeof AuthedVulnerabilitiesRoute
  '/backups/$snapshotId': typeof AuthedBackupsSnapshotIdRoute
  '/restores/$restoreId': typeof AuthedRestoresRestoreIdRoute
  '/schedule-runs/$runId': typeof AuthedScheduleRunsRunIdRoute
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/alerts': typeof AuthedSettingsAlertsRoute
  '/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/settings/destinations': typeof AuthedSettingsDestinationsRoute
  '/settings/members': typeof AuthedSettingsMembersRoute
  '/settings/organization': typeof AuthedSettingsOrganizationRoute
  '/sites/$siteId': typeof AuthedSitesSiteIdRouteWithChildren
  '/updates/$runId': typeof AuthedUpdatesRunIdRoute
  '/backups/': typeof AuthedBackupsIndexRoute
  '/sites/': typeof AuthedSitesIndexRoute
  '/updates/': typeof AuthedUpdatesIndexRoute
  '/sites/$siteId/activity': typeof AuthedSitesSiteIdActivityRoute
  '/sites/$siteId/backups': typeof AuthedSitesSiteIdBackupsRoute
  '/sites/$siteId/errors': typeof AuthedSitesSiteIdErrorsRoute
  '/sites/$siteId/health': typeof AuthedSitesSiteIdHealthRoute
  '/sites/$siteId/media': typeof AuthedSitesSiteIdMediaRoute
  '/sites/$siteId/security': typeof AuthedSitesSiteIdSecurityRoute
  '/sites/$siteId/settings': typeof AuthedSitesSiteIdSettingsRoute
  '/sites/$siteId/updates': typeof AuthedSitesSiteIdUpdatesRoute
  '/sites/$siteId/': typeof AuthedSitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept': typeof AcceptRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/audit': typeof AuthedAuditRoute
  '/migrations': typeof AuthedMigrationsRoute
  '/performance': typeof AuthedPerformanceRoute
  '/shared-with-me': typeof AuthedSharedWithMeRoute
  '/uptime': typeof AuthedUptimeRoute
  '/vulnerabilities': typeof AuthedVulnerabilitiesRoute
  '/backups/$snapshotId': typeof AuthedBackupsSnapshotIdRoute
  '/restores/$restoreId': typeof AuthedRestoresRestoreIdRoute
  '/schedule-runs/$runId': typeof AuthedScheduleRunsRunIdRoute
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/alerts': typeof AuthedSettingsAlertsRoute
  '/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/settings/destinations': typeof AuthedSettingsDestinationsRoute
  '/settings/members': typeof AuthedSettingsMembersRoute
  '/settings/organization': typeof AuthedSettingsOrganizationRoute
  '/updates/$runId': typeof AuthedUpdatesRunIdRoute
  '/backups': typeof AuthedBackupsIndexRoute
  '/sites': typeof AuthedSitesIndexRoute
  '/updates': typeof AuthedUpdatesIndexRoute
  '/sites/$siteId/activity': typeof AuthedSitesSiteIdActivityRoute
  '/sites/$siteId/backups': typeof AuthedSitesSiteIdBackupsRoute
  '/sites/$siteId/errors': typeof AuthedSitesSiteIdErrorsRoute
  '/sites/$siteId/health': typeof AuthedSitesSiteIdHealthRoute
  '/sites/$siteId/media': typeof AuthedSitesSiteIdMediaRoute
  '/sites/$siteId/security': typeof AuthedSitesSiteIdSecurityRoute
  '/sites/$siteId/settings': typeof AuthedSitesSiteIdSettingsRoute
  '/sites/$siteId/updates': typeof AuthedSitesSiteIdUpdatesRoute
  '/sites/$siteId': typeof AuthedSitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/accept': typeof AcceptRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/migrations': typeof AuthedMigrationsRoute
  '/_authed/performance': typeof AuthedPerformanceRoute
  '/_authed/shared-with-me': typeof AuthedSharedWithMeRoute
  '/_authed/uptime': typeof AuthedUptimeRoute
  '/_authed/vulnerabilities': typeof AuthedVulnerabilitiesRoute
  '/_authed/backups/$snapshotId': typeof AuthedBackupsSnapshotIdRoute
  '/_authed/restores/$restoreId': typeof AuthedRestoresRestoreIdRoute
  '/_authed/schedule-runs/$runId': typeof AuthedScheduleRunsRunIdRoute
  '/_authed/settings/account': typeof AuthedSettingsAccountRoute
  '/_authed/settings/alerts': typeof AuthedSettingsAlertsRoute
  '/_authed/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/_authed/settings/destinations': typeof AuthedSettingsDestinationsRoute
  '/_authed/settings/members': typeof AuthedSettingsMembersRoute
  '/_authed/settings/organization': typeof AuthedSettingsOrganizationRoute
  '/_authed/sites/$siteId': typeof AuthedSitesSiteIdRouteWithChildren
  '/_authed/updates/$runId': typeof AuthedUpdatesRunIdRoute
  '/_authed/backups/': typeof AuthedBackupsIndexRoute
  '/_authed/sites/': typeof AuthedSitesIndexRoute
  '/_authed/updates/': typeof AuthedUpdatesIndexRoute
  '/_authed/sites/$siteId/activity': typeof AuthedSitesSiteIdActivityRoute
  '/_authed/sites/$siteId/backups': typeof AuthedSitesSiteIdBackupsRoute
  '/_authed/sites/$siteId/errors': typeof AuthedSitesSiteIdErrorsRoute
  '/_authed/sites/$siteId/health': typeof AuthedSitesSiteIdHealthRoute
  '/_authed/sites/$siteId/media': typeof AuthedSitesSiteIdMediaRoute
  '/_authed/sites/$siteId/security': typeof AuthedSitesSiteIdSecurityRoute
  '/_authed/sites/$siteId/settings': typeof AuthedSitesSiteIdSettingsRoute
  '/_authed/sites/$siteId/updates': typeof AuthedSitesSiteIdUpdatesRoute
  '/_authed/sites/$siteId/': typeof AuthedSitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept'
    | '/login'
    | '/register'
    | '/audit'
    | '/migrations'
    | '/performance'
    | '/shared-with-me'
    | '/uptime'
    | '/vulnerabilities'
    | '/backups/$snapshotId'
    | '/restores/$restoreId'
    | '/schedule-runs/$runId'
    | '/settings/account'
    | '/settings/alerts'
    | '/settings/api-keys'
    | '/settings/destinations'
    | '/settings/members'
    | '/settings/organization'
    | '/sites/$siteId'
    | '/updates/$runId'
    | '/backups/'
    | '/sites/'
    | '/updates/'
    | '/sites/$siteId/activity'
    | '/sites/$siteId/backups'
    | '/sites/$siteId/errors'
    | '/sites/$siteId/health'
    | '/sites/$siteId/media'
    | '/sites/$siteId/security'
    | '/sites/$siteId/settings'
    | '/sites/$siteId/updates'
    | '/sites/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept'
    | '/login'
    | '/register'
    | '/audit'
    | '/migrations'
    | '/performance'
    | '/shared-with-me'
    | '/uptime'
    | '/vulnerabilities'
    | '/backups/$snapshotId'
    | '/restores/$restoreId'
    | '/schedule-runs/$runId'
    | '/settings/account'
    | '/settings/alerts'
    | '/settings/api-keys'
    | '/settings/destinations'
    | '/settings/members'
    | '/settings/organization'
    | '/updates/$runId'
    | '/backups'
    | '/sites'
    | '/updates'
    | '/sites/$siteId/activity'
    | '/sites/$siteId/backups'
    | '/sites/$siteId/errors'
    | '/sites/$siteId/health'
    | '/sites/$siteId/media'
    | '/sites/$siteId/security'
    | '/sites/$siteId/settings'
    | '/sites/$siteId/updates'
    | '/sites/$siteId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/accept'
    | '/login'
    | '/register'
    | '/_authed/audit'
    | '/_authed/migrations'
    | '/_authed/performance'
    | '/_authed/shared-with-me'
    | '/_authed/uptime'
    | '/_authed/vulnerabilities'
    | '/_authed/backups/$snapshotId'
    | '/_authed/restores/$restoreId'
    | '/_authed/schedule-runs/$runId'
    | '/_authed/settings/account'
    | '/_authed/settings/alerts'
    | '/_authed/settings/api-keys'
    | '/_authed/settings/destinations'
    | '/_authed/settings/members'
    | '/_authed/settings/organization'
    | '/_authed/sites/$siteId'
    | '/_authed/updates/$runId'
    | '/_authed/backups/'
    | '/_authed/sites/'
    | '/_authed/updates/'
    | '/_authed/sites/$siteId/activity'
    | '/_authed/sites/$siteId/backups'
    | '/_authed/sites/$siteId/errors'
    | '/_authed/sites/$siteId/health'
    | '/_authed/sites/$siteId/media'
    | '/_authed/sites/$siteId/security'
    | '/_authed/sites/$siteId/settings'
    | '/_authed/sites/$siteId/updates'
    | '/_authed/sites/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AcceptRoute: typeof AcceptRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept': {
      id: '/accept'
      path: '/accept'
      fullPath: '/accept'
      preLoaderRoute: typeof AcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/vulnerabilities': {
      id: '/_authed/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof AuthedVulnerabilitiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/uptime': {
      id: '/_authed/uptime'
      path: '/uptime'
      fullPath: '/uptime'
      preLoaderRoute: typeof AuthedUptimeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/shared-with-me': {
      id: '/_authed/shared-with-me'
      path: '/shared-with-me'
      fullPath: '/shared-with-me'
      preLoaderRoute: typeof AuthedSharedWithMeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/performance': {
      id: '/_authed/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthedPerformanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/migrations': {
      id: '/_authed/migrations'
      path: '/migrations'
      fullPath: '/migrations'
      preLoaderRoute: typeof AuthedMigrationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/updates/': {
      id: '/_authed/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof AuthedUpdatesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sites/': {
      id: '/_authed/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthedSitesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/backups/': {
      id: '/_authed/backups/'
      path: '/backups'
      fullPath: '/backups/'
      preLoaderRoute: typeof AuthedBackupsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/updates/$runId': {
      id: '/_authed/updates/$runId'
      path: '/updates/$runId'
      fullPath: '/updates/$runId'
      preLoaderRoute: typeof AuthedUpdatesRunIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sites/$siteId': {
      id: '/_authed/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AuthedSitesSiteIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/organization': {
      id: '/_authed/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthedSettingsOrganizationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/members': {
      id: '/_authed/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthedSettingsMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/destinations': {
      id: '/_authed/settings/destinations'
      path: '/settings/destinations'
      fullPath: '/settings/destinations'
      preLoaderRoute: typeof AuthedSettingsDestinationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/api-keys': {
      id: '/_authed/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthedSettingsApiKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/alerts': {
      id: '/_authed/settings/alerts'
      path: '/settings/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof AuthedSettingsAlertsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/account': {
      id: '/_authed/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthedSettingsAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule-runs/$runId': {
      id: '/_authed/schedule-runs/$runId'
      path: '/schedule-runs/$runId'
      fullPath: '/schedule-runs/$runId'
      preLoaderRoute: typeof AuthedScheduleRunsRunIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/restores/$restoreId': {
      id: '/_authed/restores/$restoreId'
      path: '/restores/$restoreId'
      fullPath: '/restores/$restoreId'
      preLoaderRoute: typeof AuthedRestoresRestoreIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/backups/$snapshotId': {
      id: '/_authed/backups/$snapshotId'
      path: '/backups/$snapshotId'
      fullPath: '/backups/$snapshotId'
      preLoaderRoute: typeof AuthedBackupsSnapshotIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sites/$siteId/': {
      id: '/_authed/sites/$siteId/'
      path: '/'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof AuthedSitesSiteIdIndexRouteImport
      parentRoute: typeof AuthedSitesSiteIdRoute
    }
    '/_authed/sites/$siteId/updates': {
      id: '/_authed/sites/$siteId/updates'
      path: '/updates'
      fullPath: '/sites/$siteId/updates'
      preLoaderRoute: typeof AuthedSitesSiteIdUpdatesRouteImport
      parentRoute: typeof AuthedSitesSiteIdRoute
    }
    '/_authed/sites/$siteId/settings': {
      id: '/_authed/sites/$siteId/settings'
      path: '/settings'
      fullPath: '/sites/$siteId/settings'
      preLoaderRoute: typeof AuthedSitesSiteIdSettingsRouteImport
      parentRoute: typeof AuthedSitesSiteIdRoute
    }
    '/_authed/sites/$siteId/security': {
      id: '/_authed/sites/$siteId/security'
      path: '/security'
      fullPath: '/sites/$siteId/security'
      preLoaderRoute: typeof AuthedSitesSiteIdSecurityRouteImport
      parentRoute: typeof AuthedSitesSiteIdRoute
    }
    '/_authed/sites/$siteId/media': {
      id: '/_authed/sites/$siteId/media'
      path: '/media'
      fullPath: '/sites/$siteId/media'
      preLoaderRoute: typeof AuthedSitesSiteIdMediaRouteImport
      parentRoute: typeof AuthedSitesSiteIdRoute
    }
    '/_authed/sites/$siteId/health': {
      id: '/_authed/sites/$siteId/health'
      path: '/health'
      fullPath: '/sites/$siteId/health'
      preLoaderRoute: typeof AuthedSitesSiteIdHealthRouteImport
      parentRoute: typeof AuthedSitesSiteIdRoute
    }
    '/_authed/sites/$siteId/errors': {
      id: '/_authed/sites/$siteId/errors'
      path: '/errors'
      fullPath: '/sites/$siteId/errors'
      preLoaderRoute: typeof AuthedSitesSiteIdErrorsRouteImport
      parentRoute: typeof AuthedSitesSiteIdRoute
    }
    '/_authed/sites/$siteId/backups': {
      id: '/_authed/sites/$siteId/backups'
      path: '/backups'
      fullPath: '/sites/$siteId/backups'
      preLoaderRoute: typeof AuthedSitesSiteIdBackupsRouteImport
      parentRoute: typeof AuthedSitesSiteIdRoute
    }
    '/_authed/sites/$siteId/activity': {
      id: '/_authed/sites/$siteId/activity'
      path: '/activity'
      fullPath: '/sites/$siteId/activity'
      preLoaderRoute: typeof AuthedSitesSiteIdActivityRouteImport
      parentRoute: typeof AuthedSitesSiteIdRoute
    }
  }
}

interface AuthedSitesSiteIdRouteChildren {
  AuthedSitesSiteIdActivityRoute: typeof AuthedSitesSiteIdActivityRoute
  AuthedSitesSiteIdBackupsRoute: typeof AuthedSitesSiteIdBackupsRoute
  AuthedSitesSiteIdErrorsRoute: typeof AuthedSitesSiteIdErrorsRoute
  AuthedSitesSiteIdHealthRoute: typeof AuthedSitesSiteIdHealthRoute
  AuthedSitesSiteIdMediaRoute: typeof AuthedSitesSiteIdMediaRoute
  AuthedSitesSiteIdSecurityRoute: typeof AuthedSitesSiteIdSecurityRoute
  AuthedSitesSiteIdSettingsRoute: typeof AuthedSitesSiteIdSettingsRoute
  AuthedSitesSiteIdUpdatesRoute: typeof AuthedSitesSiteIdUpdatesRoute
  AuthedSitesSiteIdIndexRoute: typeof AuthedSitesSiteIdIndexRoute
}

const AuthedSitesSiteIdRouteChildren: AuthedSitesSiteIdRouteChildren = {
  AuthedSitesSiteIdActivityRoute: AuthedSitesSiteIdActivityRoute,
  AuthedSitesSiteIdBackupsRoute: AuthedSitesSiteIdBackupsRoute,
  AuthedSitesSiteIdErrorsRoute: AuthedSitesSiteIdErrorsRoute,
  AuthedSitesSiteIdHealthRoute: AuthedSitesSiteIdHealthRoute,
  AuthedSitesSiteIdMediaRoute: AuthedSitesSiteIdMediaRoute,
  AuthedSitesSiteIdSecurityRoute: AuthedSitesSiteIdSecurityRoute,
  AuthedSitesSiteIdSettingsRoute: AuthedSitesSiteIdSettingsRoute,
  AuthedSitesSiteIdUpdatesRoute: AuthedSitesSiteIdUpdatesRoute,
  AuthedSitesSiteIdIndexRoute: AuthedSitesSiteIdIndexRoute,
}

const AuthedSitesSiteIdRouteWithChildren =
  AuthedSitesSiteIdRoute._addFileChildren(AuthedSitesSiteIdRouteChildren)

interface AuthedRouteChildren {
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedMigrationsRoute: typeof AuthedMigrationsRoute
  AuthedPerformanceRoute: typeof AuthedPerformanceRoute
  AuthedSharedWithMeRoute: typeof AuthedSharedWithMeRoute
  AuthedUptimeRoute: typeof AuthedUptimeRoute
  AuthedVulnerabilitiesRoute: typeof AuthedVulnerabilitiesRoute
  AuthedBackupsSnapshotIdRoute: typeof AuthedBackupsSnapshotIdRoute
  AuthedRestoresRestoreIdRoute: typeof AuthedRestoresRestoreIdRoute
  AuthedScheduleRunsRunIdRoute: typeof AuthedScheduleRunsRunIdRoute
  AuthedSettingsAccountRoute: typeof AuthedSettingsAccountRoute
  AuthedSettingsAlertsRoute: typeof AuthedSettingsAlertsRoute
  AuthedSettingsApiKeysRoute: typeof AuthedSettingsApiKeysRoute
  AuthedSettingsDestinationsRoute: typeof AuthedSettingsDestinationsRoute
  AuthedSettingsMembersRoute: typeof AuthedSettingsMembersRoute
  AuthedSettingsOrganizationRoute: typeof AuthedSettingsOrganizationRoute
  AuthedSitesSiteIdRoute: typeof AuthedSitesSiteIdRouteWithChildren
  AuthedUpdatesRunIdRoute: typeof AuthedUpdatesRunIdRoute
  AuthedBackupsIndexRoute: typeof AuthedBackupsIndexRoute
  AuthedSitesIndexRoute: typeof AuthedSitesIndexRoute
  AuthedUpdatesIndexRoute: typeof AuthedUpdatesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedMigrationsRoute: AuthedMigrationsRoute,
  AuthedPerformanceRoute: AuthedPerformanceRoute,
  AuthedSharedWithMeRoute: AuthedSharedWithMeRoute,
  AuthedUptimeRoute: AuthedUptimeRoute,
  AuthedVulnerabilitiesRoute: AuthedVulnerabilitiesRoute,
  AuthedBackupsSnapshotIdRoute: AuthedBackupsSnapshotIdRoute,
  AuthedRestoresRestoreIdRoute: AuthedRestoresRestoreIdRoute,
  AuthedScheduleRunsRunIdRoute: AuthedScheduleRunsRunIdRoute,
  AuthedSettingsAccountRoute: AuthedSettingsAccountRoute,
  AuthedSettingsAlertsRoute: AuthedSettingsAlertsRoute,
  AuthedSettingsApiKeysRoute: AuthedSettingsApiKeysRoute,
  AuthedSettingsDestinationsRoute: AuthedSettingsDestinationsRoute,
  AuthedSettingsMembersRoute: AuthedSettingsMembersRoute,
  AuthedSettingsOrganizationRoute: AuthedSettingsOrganizationRoute,
  AuthedSitesSiteIdRoute: AuthedSitesSiteIdRouteWithChildren,
  AuthedUpdatesRunIdRoute: AuthedUpdatesRunIdRoute,
  AuthedBackupsIndexRoute: AuthedBackupsIndexRoute,
  AuthedSitesIndexRoute: AuthedSitesIndexRoute,
  AuthedUpdatesIndexRoute: AuthedUpdatesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AcceptRoute: AcceptRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
