/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUpdatesIndexRouteImport } from './routes/_authed/updates/index'
import { Route as AuthedSitesIndexRouteImport } from './routes/_authed/sites/index'
import { Route as AuthedUpdatesRunIdRouteImport } from './routes/_authed/updates/$runId'
import { Route as AuthedSitesSiteIdRouteImport } from './routes/_authed/sites/$siteId'
import { Route as AuthedSettingsApiKeysRouteImport } from './routes/_authed/settings/api-keys'
import { Route as AuthedSettingsAlertsRouteImport } from './routes/_authed/settings/alerts'
import { Route as AuthedBackupsSnapshotIdRouteImport } from './routes/_authed/backups/$snapshotId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUpdatesIndexRoute = AuthedUpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSitesIndexRoute = AuthedSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUpdatesRunIdRoute = AuthedUpdatesRunIdRouteImport.update({
  id: '/updates/$runId',
  path: '/updates/$runId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSitesSiteIdRoute = AuthedSitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsApiKeysRoute = AuthedSettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsAlertsRoute = AuthedSettingsAlertsRouteImport.update({
  id: '/settings/alerts',
  path: '/settings/alerts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBackupsSnapshotIdRoute = AuthedBackupsSnapshotIdRouteImport.update({
  id: '/backups/$snapshotId',
  path: '/backups/$snapshotId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/backups/$snapshotId': typeof AuthedBackupsSnapshotIdRoute
  '/settings/alerts': typeof AuthedSettingsAlertsRoute
  '/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/sites/$siteId': typeof AuthedSitesSiteIdRoute
  '/updates/$runId': typeof AuthedUpdatesRunIdRoute
  '/sites/': typeof AuthedSitesIndexRoute
  '/updates/': typeof AuthedUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/backups/$snapshotId': typeof AuthedBackupsSnapshotIdRoute
  '/settings/alerts': typeof AuthedSettingsAlertsRoute
  '/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/sites/$siteId': typeof AuthedSitesSiteIdRoute
  '/updates/$runId': typeof AuthedUpdatesRunIdRoute
  '/sites': typeof AuthedSitesIndexRoute
  '/updates': typeof AuthedUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/backups/$snapshotId': typeof AuthedBackupsSnapshotIdRoute
  '/_authed/settings/alerts': typeof AuthedSettingsAlertsRoute
  '/_authed/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/_authed/sites/$siteId': typeof AuthedSitesSiteIdRoute
  '/_authed/updates/$runId': typeof AuthedUpdatesRunIdRoute
  '/_authed/sites/': typeof AuthedSitesIndexRoute
  '/_authed/updates/': typeof AuthedUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/backups/$snapshotId'
    | '/settings/alerts'
    | '/settings/api-keys'
    | '/sites/$siteId'
    | '/updates/$runId'
    | '/sites/'
    | '/updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/backups/$snapshotId'
    | '/settings/alerts'
    | '/settings/api-keys'
    | '/sites/$siteId'
    | '/updates/$runId'
    | '/sites'
    | '/updates'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/backups/$snapshotId'
    | '/_authed/settings/alerts'
    | '/_authed/settings/api-keys'
    | '/_authed/sites/$siteId'
    | '/_authed/updates/$runId'
    | '/_authed/sites/'
    | '/_authed/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/updates/': {
      id: '/_authed/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof AuthedUpdatesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sites/': {
      id: '/_authed/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthedSitesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/updates/$runId': {
      id: '/_authed/updates/$runId'
      path: '/updates/$runId'
      fullPath: '/updates/$runId'
      preLoaderRoute: typeof AuthedUpdatesRunIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sites/$siteId': {
      id: '/_authed/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AuthedSitesSiteIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/api-keys': {
      id: '/_authed/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthedSettingsApiKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/alerts': {
      id: '/_authed/settings/alerts'
      path: '/settings/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof AuthedSettingsAlertsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/backups/$snapshotId': {
      id: '/_authed/backups/$snapshotId'
      path: '/backups/$snapshotId'
      fullPath: '/backups/$snapshotId'
      preLoaderRoute: typeof AuthedBackupsSnapshotIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBackupsSnapshotIdRoute: typeof AuthedBackupsSnapshotIdRoute
  AuthedSettingsAlertsRoute: typeof AuthedSettingsAlertsRoute
  AuthedSettingsApiKeysRoute: typeof AuthedSettingsApiKeysRoute
  AuthedSitesSiteIdRoute: typeof AuthedSitesSiteIdRoute
  AuthedUpdatesRunIdRoute: typeof AuthedUpdatesRunIdRoute
  AuthedSitesIndexRoute: typeof AuthedSitesIndexRoute
  AuthedUpdatesIndexRoute: typeof AuthedUpdatesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBackupsSnapshotIdRoute: AuthedBackupsSnapshotIdRoute,
  AuthedSettingsAlertsRoute: AuthedSettingsAlertsRoute,
  AuthedSettingsApiKeysRoute: AuthedSettingsApiKeysRoute,
  AuthedSitesSiteIdRoute: AuthedSitesSiteIdRoute,
  AuthedUpdatesRunIdRoute: AuthedUpdatesRunIdRoute,
  AuthedSitesIndexRoute: AuthedSitesIndexRoute,
  AuthedUpdatesIndexRoute: AuthedUpdatesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
