package mcp

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The agent's tests replay this file. It is regenerated, never hand-edited
// (WPMGR_WRITE_FIXTURES=1).
const restDigestVectorPath = "../../../agent/tests/fixtures/rest-call/digest-vector.json"

type restDigestVector struct {
	Note            string `json:"note"`
	EntrySHA256     string `json:"entry_sha256"`
	RouteSHA256     string `json:"route_sha256"`
	Input           string `json:"input"`
	BaseFingerprint string `json:"base_fingerprint"`
	PrecheckDigest  string `json:"precheck_digest"`
}

func buildRestDigestVector(t *testing.T) []byte {
	t.Helper()
	input := `{"route_id":"wp-v2-pages-update-fields","path":{"id":412},"query":{},"body":{"title":"Café & croissants 🥐","excerpt":"Prix: 5€ — naïve 日本語"}}`
	v := restDigestVector{
		Note:            "Generated by Go (internal/mcp/ability_rest_digest_vector_test.go) from restPrecheckDigest. Regenerate with WPMGR_WRITE_FIXTURES=1.",
		EntrySHA256:     sha256Hex([]byte("digest-vector-entry")),
		RouteSHA256:     sha256Hex([]byte("digest-vector-route")),
		Input:           input,
		BaseFingerprint: sha256Hex([]byte("digest-vector-base-fingerprint")),
	}
	v.PrecheckDigest = restPrecheckDigest(v.EntrySHA256, v.RouteSHA256, []byte(v.Input), v.BaseFingerprint)
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// TestRestDigestVectorFixture: the vector the agent asserts against is what
// Go's restPrecheckDigest produces now.
func TestRestDigestVectorFixture(t *testing.T) {
	want := buildRestDigestVector(t)
	if os.Getenv("WPMGR_WRITE_FIXTURES") == "1" {
		if err := os.MkdirAll(filepath.Dir(restDigestVectorPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(restDigestVectorPath, want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(restDigestVectorPath)
	if err != nil {
		t.Fatalf("read fixture: %v; regenerate with WPMGR_WRITE_FIXTURES=1", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("%s differs from what Go produces now; regenerate with WPMGR_WRITE_FIXTURES=1", restDigestVectorPath)
	}
}
