package abilities

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/google/uuid"

	"github.com/mosamlife/wpmgr/apps/api/internal/agentcmd"
	"github.com/mosamlife/wpmgr/apps/api/internal/db/sqlc"
)

// pageCreateFixturePath is the data file the agent's tests replay. It is
// regenerated, never hand-edited.
const pageCreateFixturePath = "../../../agent/tests/fixtures/ability-run/page-create.json"

// seededPageCreateRow is the wpmgr/page-create row as the m157 seed leaves it
// (columns the seed does not name take the m155 defaults).
func seededPageCreateRow() sqlc.AbilityCatalogue {
	minAgent := "0.61.156"
	perm := "site.content.edit"
	return sqlc.AbilityCatalogue{
		Name: "wpmgr/page-create", Source: "wpmgr", Class: "write", Status: "admitted",
		Enabled: true, ApprovalMode: "per_call", PermissionMode: "principal",
		MinAgentVersion: &minAgent, Title: "Create a draft page",
		Description:        "Creates a new draft page or post from a text outline. Nothing is published. Undo moves the draft to the trash.",
		OperatorPermission: &perm, Snapshot: "created_post_trash", EffectCopy: "draft",
		ArgRender: []byte("{}"), Limits: []byte("{}"), Admission: []byte("{}"),
	}
}

type pageCreateFixture struct {
	Note        string `json:"note"`
	SiteID      string `json:"site_id"`
	RequestID   string `json:"request_id"`
	Entry       string `json:"entry"`
	EntrySHA256 string `json:"entry_sha256"`
	Input       string `json:"input"`
	Precheck    struct {
		P string `json:"p"`
	} `json:"precheck"`
	Write struct {
		Expected agentcmd.AbilityRunExpected `json:"expected"`
		P        string                      `json:"p"`
	} `json:"write"`
	Revert struct {
		P string `json:"p"`
	} `json:"revert"`
}

func buildPageCreateFixture(t *testing.T) []byte {
	t.Helper()
	entry, sum, err := EntryBytes(seededPageCreateRow())
	if err != nil {
		t.Fatal(err)
	}
	input := []byte(`{"post_type":"page","editor":"wordpress_blocks","title":"Café launch 🚀","outline":[{"type":"heading","level":2,"text":"Héllo wörld 🌍"},{"type":"paragraph","text":"Prix: 5€ — naïve 日本語"}]}`)
	reqID := uuid.MustParse("11111111-2222-4333-8444-555555555555")

	f := pageCreateFixture{
		Note:        "Generated by Go (internal/abilities/pagecreate_fixture_test.go). Regenerate with WPMGR_WRITE_FIXTURES=1. The expected digests are fixed stand-ins.",
		SiteID:      "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
		RequestID:   reqID.String(),
		Entry:       string(entry),
		EntrySHA256: sum,
		Input:       string(input),
	}
	build := func(c agentcmd.AbilityRunCall) string {
		c.RequestID, c.Entry, c.EntrySHA256 = reqID, entry, sum
		p, _, err := agentcmd.BuildAbilityRunParams(c)
		if err != nil {
			t.Fatal(err)
		}
		return string(p)
	}
	f.Precheck.P = build(agentcmd.AbilityRunCall{Mode: agentcmd.AbilityRunModePrecheck, Input: input})
	f.Write.Expected = agentcmd.AbilityRunExpected{
		PrecheckDigest: agentcmd.SHA256Hex([]byte("precheck-digest-stand-in")),
		PreviewDigest:  agentcmd.SHA256Hex([]byte("preview-digest-stand-in")),
	}
	f.Write.P = build(agentcmd.AbilityRunCall{Mode: agentcmd.AbilityRunModeWrite, Input: input, Expected: &f.Write.Expected})
	f.Revert.P = build(agentcmd.AbilityRunCall{Mode: agentcmd.AbilityRunModeRevert})

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(f); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func TestPageCreateFixture(t *testing.T) {
	want := buildPageCreateFixture(t)
	if os.Getenv("WPMGR_WRITE_FIXTURES") == "1" {
		if err := os.MkdirAll(filepath.Dir(pageCreateFixturePath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(pageCreateFixturePath, want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(pageCreateFixturePath)
	if err != nil {
		t.Fatalf("read fixture: %v; regenerate with WPMGR_WRITE_FIXTURES=1", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("%s differs from what Go produces now; regenerate with WPMGR_WRITE_FIXTURES=1", pageCreateFixturePath)
	}
}
