package abilities

import (
	"bytes"
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/uuid"

	"github.com/mosamlife/wpmgr/apps/api/internal/agentcmd"
	"github.com/mosamlife/wpmgr/apps/api/internal/db/sqlc"
	"github.com/mosamlife/wpmgr/apps/api/migrations"
)

// pageCreateFixturePath is the data file the agent's tests replay. It is
// regenerated, never hand-edited. The agent's layout fixture
// (page-create-layout.json) is built from the entry it carries.
const (
	pageCreateFixturePath       = "../../../agent/tests/fixtures/ability-run/page-create.json"
	pageCreateLayoutFixturePath = "../../../agent/tests/fixtures/ability-run/page-create-layout.json"
	m162PageCreateCopy          = "20261009000000_m162_page_create_layout_copy.sql"
)

// m162Constant is the text of a constant m162 declares: its quoted pieces
// joined, with a doubled quote read as one, up to the ';' that ends it.
func m162Constant(t *testing.T, name string) string {
	t.Helper()
	b, err := fs.ReadFile(migrations.FS, m162PageCreateCopy)
	if err != nil {
		t.Fatalf("read %s: %v", m162PageCreateCopy, err)
	}
	sql := string(b)
	i := strings.Index(sql, name+" constant ")
	if i < 0 {
		t.Fatalf("%s: no constant %s", m162PageCreateCopy, name)
	}
	rest := sql[i:]
	rest = rest[strings.Index(rest, ":=")+2:]
	var out strings.Builder
	in := false
	for j := 0; j < len(rest); j++ {
		switch c := rest[j]; {
		case in && c == '\'' && j+1 < len(rest) && rest[j+1] == '\'':
			out.WriteByte('\'')
			j++
		case c == '\'':
			in = !in
		case in:
			out.WriteByte(c)
		case c == ';':
			if out.Len() == 0 {
				t.Fatalf("%s: constant %s is empty", m162PageCreateCopy, name)
			}
			return out.String()
		}
	}
	t.Fatalf("%s: constant %s is not terminated", m162PageCreateCopy, name)
	return ""
}

// seededPageCreateRow is the wpmgr/page-create row as the migrations leave
// it: the m157 seed (columns the seed does not name take the m155
// defaults), with the description, usage and limits m162 sets, read from
// m162 itself.
func seededPageCreateRow(t *testing.T) sqlc.AbilityCatalogue {
	t.Helper()
	minAgent := "0.61.156"
	perm := "site.content.edit"
	usage := m162Constant(t, "v_usage")
	return sqlc.AbilityCatalogue{
		Name: "wpmgr/page-create", Source: "wpmgr", Class: "write", Status: "admitted",
		Enabled: true, ApprovalMode: "per_call", PermissionMode: "principal",
		MinAgentVersion: &minAgent, Title: "Create a draft page",
		Description: m162Constant(t, "v_description"), Usage: &usage,
		OperatorPermission: &perm, Snapshot: "created_post_trash", EffectCopy: "draft",
		ArgRender: []byte("{}"), Limits: []byte(m162Constant(t, "v_limits")), Admission: []byte("{}"),
	}
}

type pageCreateFixture struct {
	Note        string `json:"note"`
	SiteID      string `json:"site_id"`
	RequestID   string `json:"request_id"`
	Entry       string `json:"entry"`
	EntrySHA256 string `json:"entry_sha256"`
	Input       string `json:"input"`
	Precheck    struct {
		P string `json:"p"`
	} `json:"precheck"`
	Write struct {
		Expected agentcmd.AbilityRunExpected `json:"expected"`
		P        string                      `json:"p"`
	} `json:"write"`
	Revert struct {
		P string `json:"p"`
	} `json:"revert"`
}

func buildPageCreateFixture(t *testing.T) []byte {
	t.Helper()
	entry, sum, err := EntryBytes(seededPageCreateRow(t))
	if err != nil {
		t.Fatal(err)
	}
	input := []byte(`{"post_type":"page","editor":"wordpress_blocks","title":"Café launch 🚀","outline":[{"type":"heading","level":2,"text":"Héllo wörld 🌍"},{"type":"paragraph","text":"Prix: 5€ — naïve 日本語"}]}`)
	reqID := uuid.MustParse("11111111-2222-4333-8444-555555555555")

	f := pageCreateFixture{
		Note:        "Generated by Go (internal/abilities/pagecreate_fixture_test.go). Regenerate with WPMGR_WRITE_FIXTURES=1. The expected digests are fixed stand-ins.",
		SiteID:      "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
		RequestID:   reqID.String(),
		Entry:       string(entry),
		EntrySHA256: sum,
		Input:       string(input),
	}
	build := func(c agentcmd.AbilityRunCall) string {
		c.RequestID, c.Entry, c.EntrySHA256 = reqID, entry, sum
		p, _, err := agentcmd.BuildAbilityRunParams(c)
		if err != nil {
			t.Fatal(err)
		}
		return string(p)
	}
	f.Precheck.P = build(agentcmd.AbilityRunCall{Mode: agentcmd.AbilityRunModePrecheck, Input: input})
	f.Write.Expected = agentcmd.AbilityRunExpected{
		PrecheckDigest: agentcmd.SHA256Hex([]byte("precheck-digest-stand-in")),
		PreviewDigest:  agentcmd.SHA256Hex([]byte("preview-digest-stand-in")),
	}
	f.Write.P = build(agentcmd.AbilityRunCall{Mode: agentcmd.AbilityRunModeWrite, Input: input, Expected: &f.Write.Expected})
	f.Revert.P = build(agentcmd.AbilityRunCall{Mode: agentcmd.AbilityRunModeRevert})

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(f); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func TestPageCreateFixture(t *testing.T) {
	want := buildPageCreateFixture(t)
	if os.Getenv("WPMGR_WRITE_FIXTURES") == "1" {
		if err := os.MkdirAll(filepath.Dir(pageCreateFixturePath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(pageCreateFixturePath, want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(pageCreateFixturePath)
	if err != nil {
		t.Fatalf("read fixture: %v; regenerate with WPMGR_WRITE_FIXTURES=1", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("%s differs from what Go produces now; regenerate with WPMGR_WRITE_FIXTURES=1", pageCreateFixturePath)
	}
}

// TestPageCreateLayoutFixtureCarriesTheEntry: the agent builds its layout
// fixture from the entry page-create.json carries, so the precheck digests
// it records bind the entry the control plane sends after m162, the one
// that names the layout floor.
func TestPageCreateLayoutFixtureCarriesTheEntry(t *testing.T) {
	entry, sum, err := EntryBytes(seededPageCreateRow(t))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(entry), "Layout blocks need the WPMgr plugin "+agentcmd.MinAgentVersionForPageLayout+" or later") {
		t.Fatalf("the page-create entry does not name the layout floor %s: %s", agentcmd.MinAgentVersionForPageLayout, entry)
	}
	b, err := os.ReadFile(pageCreateLayoutFixturePath)
	if err != nil {
		t.Fatalf("read %s: %v", pageCreateLayoutFixturePath, err)
	}
	var doc struct {
		Entry       string `json:"entry"`
		EntrySHA256 string `json:"entry_sha256"`
	}
	if err := json.Unmarshal(b, &doc); err != nil {
		t.Fatalf("decode %s: %v", pageCreateLayoutFixturePath, err)
	}
	if doc.Entry != string(entry) || doc.EntrySHA256 != sum {
		t.Fatalf("%s carries another entry (sha256 %s, want %s); regenerate page-create.json here, "+
			"then the layout fixture with the agent's WPMGR_WRITE_FIXTURES=1", pageCreateLayoutFixturePath, doc.EntrySHA256, sum)
	}
}
