<?php
/**
 * GUT: the layout grammar, serializer, escaping and the three contract
 * fixtures shared with the control plane.
 *
 * Fixtures (regenerate with WPMGR_WRITE_FIXTURES=1, never hand-edit):
 *   page-create-schema.json        the input schema text the AI sees
 *   page-create-layout-cases.json  accept/refuse table (agent code + Go verdict)
 *   page-create-layout.json        inputs, media facts, content and digests
 *
 * @package WPMgr\Agent\Tests
 */

declare(strict_types=1);

namespace WPMgr\Agent\Tests;

use WPMgr\Agent\Abilities\OwnAbilities;
use WPMgr\Agent\Abilities\PageCreateBuilder;
use Yoast\PHPUnitPolyfills\TestCases\TestCase;

/**
 * @covers \WPMgr\Agent\Abilities\PageCreateBuilder
 */
final class PageCreateLayoutTest extends TestCase
{
    private const FIXTURE_DIR = __DIR__ . '/fixtures/ability-run/';

    /** The m157 entry text the existing page-create fixture carries. */
    private static function entryText(): string
    {
        $raw = file_get_contents(self::FIXTURE_DIR . 'page-create.json');
        self::assertIsString($raw);
        $f = json_decode($raw, true);
        self::assertIsArray($f);

        return (string) $f['entry'];
    }

    // -------------------------------------------------------------------------
    // Contract fixtures
    // -------------------------------------------------------------------------

    public function test_schema_fixture_is_the_schema_the_agent_registers(): void
    {
        $this->assertFixture('page-create-schema.json', self::schemaFixture());
        $this->assertSame(
            PageCreateBuilder::inputSchema(),
            OwnAbilities::inputSchema(OwnAbilities::NAME_PAGE_CREATE),
            'the inventory and the builder publish one schema'
        );
    }

    public function test_cases_fixture_matches_the_builder(): void
    {
        $cases = self::caseTable();
        foreach ($cases as $c) {
            $this->assertSame($c['agent'], self::agentVerdict($c['input']), $c['name']);
        }
        $this->assertFixture('page-create-layout-cases.json', self::casesFixture($cases));
    }

    public function test_layout_fixture_matches_the_builder(): void
    {
        $this->assertFixture('page-create-layout.json', self::layoutFixture());
    }

    // -------------------------------------------------------------------------
    // Fixture builders
    // -------------------------------------------------------------------------

    private function assertFixture(string $name, string $want): void
    {
        $path = self::FIXTURE_DIR . $name;
        if (getenv('WPMGR_WRITE_FIXTURES') === '1') {
            $this->assertNotFalse(file_put_contents($path, $want), 'could not write ' . $name);
        }
        $got = file_get_contents($path);
        $this->assertIsString($got, $name . ' is missing; regenerate with WPMGR_WRITE_FIXTURES=1');
        $this->assertSame($want, $got, $name . ' differs from what the agent produces now; regenerate with WPMGR_WRITE_FIXTURES=1');
    }

    public static function schemaFixture(): string
    {
        return json_encode(PageCreateBuilder::inputSchema(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR) . "\n";
    }

    /**
     * The agent's verdict on one input text: "ok" or the refusal code.
     */
    public static function agentVerdict(string $inputText): string
    {
        $input = json_decode($inputText, false, 32);
        if (!is_object($input)) {
            return 'bad_input';
        }
        $r = PageCreateBuilder::validate($input);

        return isset($r['spec']) ? 'ok' : (string) $r['code'];
    }

    /**
     * @param list<array{name:string,input:string,agent:string,go:string}> $cases
     */
    private static function casesFixture(array $cases): string
    {
        $doc = [
            'note'  => 'Generated by the agent (tests/PageCreateLayoutTest.php). Regenerate with WPMGR_WRITE_FIXTURES=1. '
                . '"input" is the exact JSON text. "agent" is what PageCreateBuilder::validate answers: "ok" or the refusal code. '
                . '"go" is what the control plane validation must answer before precheck: "accept" or "refuse". '
                . 'Text-character rules (create_content_invalid with go "accept") are the agent\'s alone.',
            'cases' => $cases,
        ];

        return json_encode($doc, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR) . "\n";
    }

    /**
     * The scenario fixture: what precheck answers for three inputs.
     */
    public static function layoutFixture(): string
    {
        $entry = self::entryText();
        $sha   = hash('sha256', $entry);
        $out   = [];
        foreach (self::scenarios() as $s) {
            $input = json_decode($s['input'], false, 32);
            self::assertIsObject($input);
            $r = PageCreateBuilder::validate($input);
            self::assertArrayHasKey('spec', $r, $s['name'] . ': ' . json_encode($r));
            $spec  = $r['spec'];
            $facts = [];
            $byId  = [];
            foreach (PageCreateBuilder::mediaIds($spec) as $id) {
                $facts[]   = $s['media'][$id];
                $byId[$id] = $s['media'][$id];
            }
            $content = PageCreateBuilder::render($spec, $byId);
            self::assertNull(PageCreateBuilder::retokenise($content), $s['name']);
            $base    = PageCreateBuilder::baseFingerprint($spec['post_type'], $facts);
            $preview = PageCreateBuilder::previewDigest($spec, $content);
            $pv      = [
                'post_type' => $spec['post_type'],
                'editor'    => $spec['editor'],
                'status'    => 'draft',
                'title'     => $spec['title'],
                'content'   => $content,
            ];
            if ($facts !== []) {
                $pv['media'] = $facts;
            }
            $out[] = [
                'name'             => $s['name'],
                'input'            => $s['input'],
                'media_ids'        => PageCreateBuilder::mediaIds($spec),
                'stored_title'     => PageCreateBuilder::storedTitle($spec['title']),
                'base_fingerprint' => $base,
                'preview_digest'   => $preview,
                'precheck_digest'  => hash('sha256', (string) json_encode([$sha, hash('sha256', $s['input']), $base, $preview])),
                'preview'          => $pv,
            ];
        }
        $doc = [
            'note'         => 'Generated by the agent (tests/PageCreateLayoutTest.php). Regenerate with WPMGR_WRITE_FIXTURES=1. '
                . 'Each case is what precheck answers for "input" on a site whose images have the facts in preview.media: '
                . 'base_fingerprint = sha256(json_encode(["new_post", post_type, [[id,url,filename,mime,width,height,modified_gmt], ...]])) '
                . 'in media_ids order (without images: sha256(json_encode(["new_post", post_type]))); '
                . 'preview_digest = sha256(json_encode([editor, post_type, "draft", title, content])); '
                . 'precheck_digest = sha256(json_encode([entry_sha256, sha256(input), base_fingerprint, preview_digest])). '
                . 'json_encode with default flags. preview.media is present only when the outline has an image.',
            'entry'        => $entry,
            'entry_sha256' => $sha,
            'limits'       => PageCreateBuilder::limits(),
            'cases'        => $out,
        ];

        return json_encode($doc, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR) . "\n";
    }

    /**
     * Media facts a site could answer for the scenario ids.
     *
     * @return array<int,array<string,mixed>>
     */
    public static function media(): array
    {
        return [
            42 => [
                'id' => 42, 'url' => 'https://example.com/wp-content/uploads/2026/10/team-photo-1024x683.jpg',
                'filename' => 'team-photo.jpg', 'mime' => 'image/jpeg', 'width' => 1200, 'height' => 800,
                'modified_gmt' => '2026-10-01 09:00:00',
            ],
            7 => [
                'id' => 7, 'url' => 'https://cdn.example.com/caf%C3%A9-menu.png?w=1024&h=683',
                'filename' => 'café-menu.png', 'mime' => 'image/png', 'width' => 640, 'height' => 480,
                'modified_gmt' => '2026-09-30 18:30:05',
            ],
            9 => [
                'id' => 9, 'url' => 'http://example.com/wp-content/uploads/2026/09/banner.webp',
                'filename' => 'banner.webp', 'mime' => 'image/webp', 'width' => 0, 'height' => 0,
                'modified_gmt' => '2026-09-02 07:00:00',
            ],
        ];
    }

    /**
     * @return list<array{name:string,input:string,media:array<int,array<string,mixed>>}>
     */
    public static function scenarios(): array
    {
        $everything = [
            ['type' => 'heading', 'level' => 2, 'text' => 'Welcome to Café Ünï 🚀'],
            ['type' => 'paragraph', 'text' => 'We serve breakfast & lunch [1]. "Fresh" daily, it\'s true.'],
            ['type' => 'group', 'children' => [
                ['type' => 'heading', 'level' => 3, 'text' => 'Our team'],
                ['type' => 'columns', 'widths' => [60, 40], 'columns' => [
                    ['children' => [
                        ['type' => 'image', 'attachment_id' => 42, 'alt' => 'Bob\'s "dog" & cat', 'caption' => 'Rex, our mascot [2]'],
                        ['type' => 'paragraph', 'text' => 'Left'],
                    ]],
                    ['children' => [
                        ['type' => 'heading', 'level' => 4, 'text' => 'Right'],
                        ['type' => 'buttons', 'align' => 'center', 'buttons' => [
                            ['text' => 'Book a call', 'url' => 'https://calendly.example/acme/30min'],
                            ['text' => 'Contact & map', 'url' => '/contact?x=1&y=2#map', 'style' => 'outline'],
                        ]],
                    ]],
                ]],
            ]],
            ['type' => 'columns', 'columns' => [
                ['children' => [['type' => 'image', 'attachment_id' => 7, 'alt' => '', 'align' => 'center']]],
                ['children' => [['type' => 'list', 'ordered' => false, 'items' => ['One', 'Two']]]],
                ['children' => [['type' => 'quote', 'paragraphs' => ['To be & not to be.', 'Second [3].'], 'citation' => 'Jane & John']]],
            ]],
            ['type' => 'image', 'attachment_id' => 42, 'alt' => 'Again', 'align' => 'wide'],
            ['type' => 'image', 'attachment_id' => 9, 'alt' => 'Full width', 'align' => 'full'],
            ['type' => 'separator'],
            ['type' => 'spacer', 'size' => 'medium'],
            ['type' => 'table', 'header' => ['Plan', 'Price'], 'rows' => [['Basic', '$10'], ['Pro [1]', '']]],
            ['type' => 'list', 'ordered' => true, 'items' => ['First', 'Second']],
        ];
        $classic = [
            ['type' => 'heading', 'level' => 2, 'text' => 'Hours & prices'],
            ['type' => 'paragraph', 'text' => 'Open daily.'],
            ['type' => 'list', 'ordered' => false, 'items' => ['Tea', 'Coffee']],
            ['type' => 'image', 'attachment_id' => 42, 'alt' => 'Bob\'s café', 'align' => 'center'],
            ['type' => 'quote', 'paragraphs' => ['Q & q'], 'citation' => 'Who [2]'],
            ['type' => 'table', 'rows' => [['a & b', '']]],
            ['type' => 'separator'],
        ];
        $media = self::media();

        return [
            ['name' => 'blocks-every-node', 'input' => self::page($everything), 'media' => $media],
            ['name' => 'classic-subset', 'input' => self::page($classic, 'wordpress_classic', 'post'), 'media' => $media],
            [
                'name'  => 'text-only-unchanged',
                // The existing page-create.json input: its v1 bytes and digests must not move.
                'input' => '{"post_type":"page","editor":"wordpress_blocks","title":"Café launch 🚀","outline":[{"type":"heading","level":2,"text":"Héllo wörld 🌍"},{"type":"paragraph","text":"Prix: 5€ — naïve 日本語"}]}',
                'media' => [],
            ],
        ];
    }

    /**
     * @param list<mixed> $outline
     */
    private static function page(array $outline, string $editor = 'wordpress_blocks', string $type = 'page'): string
    {
        return json_encode(['post_type' => $type, 'editor' => $editor, 'title' => 'T', 'outline' => $outline], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);
    }

    /**
     * @param list<mixed> $outline
     * @return array{name:string,input:string,agent:string,go:string}
     */
    private static function c(string $name, string $agent, array $outline, string $editor = 'wordpress_blocks'): array
    {
        return self::raw($name, $agent, self::page($outline, $editor));
    }

    /**
     * @return array{name:string,input:string,agent:string,go:string}
     */
    private static function raw(string $name, string $agent, string $input, ?string $go = null): array
    {
        if ($go === null) {
            $go = $agent === 'ok' ? 'accept' : 'refuse';
        }

        return ['name' => $name, 'input' => $input, 'agent' => $agent, 'go' => $go];
    }

    /**
     * A text-rule refusal: the agent refuses, the control plane passes it on.
     *
     * @param list<mixed> $outline
     * @return array{name:string,input:string,agent:string,go:string}
     */
    private static function text(string $name, array $outline, string $editor = 'wordpress_blocks'): array
    {
        return self::raw($name, 'create_content_invalid', self::page($outline, $editor), 'accept');
    }

    /**
     * @return list<array{name:string,input:string,agent:string,go:string}>
     */
    public static function caseTable(): array
    {
        $p   = static fn (string $t = 'x'): array => ['type' => 'paragraph', 'text' => $t];
        $img = static fn (int $id, array $extra = []): array => ['type' => 'image', 'attachment_id' => $id, 'alt' => 'A'] + $extra;
        $btn = static fn (string $url, array $extra = []): array => ['type' => 'buttons', 'buttons' => [['text' => 'Go', 'url' => $url] + $extra]];
        $col = static fn (array ...$kids): array => ['children' => $kids];
        $cols = static fn (array $columns, ?array $widths = null): array => $widths === null
            ? ['type' => 'columns', 'columns' => $columns]
            : ['type' => 'columns', 'widths' => $widths, 'columns' => $columns];
        $tbl = static fn (array $rows, ?array $header = null): array => $header === null
            ? ['type' => 'table', 'rows' => $rows]
            : ['type' => 'table', 'header' => $header, 'rows' => $rows];
        $many = static fn (int $n, callable $make): array => array_map($make, range(1, $n));

        $nodes400 = [];
        for ($g = 0; $g < 8; $g++) {
            $nodes400[] = ['type' => 'group', 'children' => $many($g < 7 ? 50 : 42, static fn () => ['type' => 'separator'])];
        }
        $nodes401 = $nodes400;
        $nodes401[7]['children'][] = ['type' => 'separator'];

        return [
            // Accepted.
            self::c('v1-heading-paragraph-list', 'ok', [['type' => 'heading', 'level' => 3, 'text' => 'H'], $p(), ['type' => 'list', 'ordered' => true, 'items' => ['a']]]),
            self::c('image-minimal', 'ok', [$img(42)]),
            self::c('image-empty-alt', 'ok', [['type' => 'image', 'attachment_id' => 42, 'alt' => '']]),
            self::c('image-every-field', 'ok', [$img(42, ['caption' => 'Cap & more [2]', 'align' => 'center'])]),
            self::c('image-align-none-explicit', 'ok', [$img(42, ['align' => 'none'])]),
            self::c('image-alt-apostrophe-quote-amp', 'ok', [['type' => 'image', 'attachment_id' => 1, 'alt' => 'Bob\'s "dog" & cat']]),
            self::c('image-id-max', 'ok', [$img(2147483647)]),
            self::c('buttons-three-mixed', 'ok', [['type' => 'buttons', 'align' => 'center', 'buttons' => [
                ['text' => 'A', 'url' => 'https://example.com/a?x=1&y=2', 'style' => 'fill'],
                ['text' => 'B & C', 'url' => 'https://example.com/b#frag', 'style' => 'outline'],
                ['text' => 'D', 'url' => '/contact'],
            ]]]),
            self::c('link-port-query-fragment', 'ok', [$btn('https://shop.example.com:8443/a?x=1&y=2#top')]),
            self::c('link-percent-encoded', 'ok', [$btn('https://example.com/a%20b%C3%A9')]),
            self::c('link-site-root', 'ok', [$btn('/')]),
            self::c('link-punycode-host', 'ok', [$btn('https://xn--bcher-kva.example/')]),
            self::c('link-other-website', 'ok', [$btn('https://calendly.example/acme/30min')]),
            // An ampersand that does not start a character reference, and a colon WordPress keeps.
            self::c('link-ampersand-not-a-reference', 'ok', [$btn('https://example.com/?a=1&copy=2&b=3&;c&#;d&#x;e&#xg;')]),
            self::c('link-path-ampersand-not-a-reference', 'ok', [$btn('/shop?x=1&copy=2#top')]),
            self::c('link-path-colon-percent-encoded', 'ok', [$btn('/shop/sale%3Asummer')]),
            self::c('link-https-colon-in-path', 'ok', [$btn('https://example.com/shop/sale:summer?t=10:30')]),
            self::c('image-alt-ampersand-not-a-reference', 'ok', [['type' => 'image', 'attachment_id' => 1, 'alt' => 'Logo &copy 2026, a & b, AT&T, &; &#; &#x; &#xg; & amp;']]),
            self::c('quote-with-citation', 'ok', [['type' => 'quote', 'paragraphs' => ['One.', 'Two [3].'], 'citation' => 'Jane & John']]),
            self::c('separator', 'ok', [['type' => 'separator']]),
            self::c('spacers', 'ok', [['type' => 'spacer', 'size' => 'small'], ['type' => 'spacer', 'size' => 'medium'], ['type' => 'spacer', 'size' => 'large']]),
            self::c('table-header-and-empty-cells', 'ok', [$tbl([['', 'b'], ['c', '']], ['A', ''])]),
            self::c('table-6-by-50', 'ok', [$tbl($many(50, static fn () => ['a', 'b', 'c', 'd', 'e', 'f']))]),
            self::c('group-with-columns', 'ok', [['type' => 'group', 'children' => [['type' => 'heading', 'level' => 2, 'text' => 'In a group'], $cols([$col($p('a')), $col($p('b'))])]]]),
            self::c('columns-2-equal', 'ok', [$cols([$col($p()), $col($p())])]),
            self::c('columns-3-widths', 'ok', [$cols([$col($p()), $col($p()), $col($p())], [25, 50, 25])]),
            self::c('columns-4', 'ok', [$cols([$col($p()), $col($p()), $col($p()), $col($p())])]),
            self::c('columns-widths-10-90', 'ok', [$cols([$col($p()), $col($p())], [10, 90])]),
            self::c('group-50-children', 'ok', [['type' => 'group', 'children' => $many(50, static fn () => ['type' => 'separator'])]]),
            self::c('images-20', 'ok', $many(20, static fn (int $i) => ['type' => 'image', 'attachment_id' => $i, 'alt' => ''])),
            self::c('buttons-12', 'ok', $many(4, static fn () => ['type' => 'buttons', 'buttons' => [['text' => 'a', 'url' => '/a'], ['text' => 'b', 'url' => '/b'], ['text' => 'c', 'url' => '/c']]])),
            self::c('tables-10', 'ok', $many(10, static fn () => ['type' => 'table', 'rows' => [['a']]])),
            self::c('nodes-exactly-400', 'ok', $nodes400),
            self::c('classic-subset', 'ok', [
                ['type' => 'heading', 'level' => 2, 'text' => 'H'], $p(), ['type' => 'list', 'ordered' => false, 'items' => ['a']],
                $img(42, ['align' => 'full']), ['type' => 'quote', 'paragraphs' => ['q'], 'citation' => 'c'],
                $tbl([['a']], ['h']), ['type' => 'separator'],
            ], 'wordpress_classic'),

            // Wrong keys, types and enum values.
            self::c('image-unknown-key', 'bad_input', [$img(1, ['width' => 3])]),
            self::c('image-missing-alt', 'bad_input', [['type' => 'image', 'attachment_id' => 42]]),
            self::c('image-id-string', 'bad_input', [['type' => 'image', 'attachment_id' => '42', 'alt' => '']]),
            self::raw('image-id-float', 'bad_input', '{"post_type":"page","editor":"wordpress_blocks","title":"T","outline":[{"type":"image","attachment_id":42.0,"alt":""}]}'),
            self::c('image-id-zero', 'bad_input', [$img(0)]),
            self::c('image-id-too-big', 'bad_input', [$img(2147483648)]),
            self::c('image-align-left', 'bad_input', [$img(1, ['align' => 'left'])]),
            self::c('image-caption-null', 'bad_input', [$img(1, ['caption' => null])]),
            self::c('image-alt-number', 'bad_input', [['type' => 'image', 'attachment_id' => 1, 'alt' => 5]]),
            self::c('buttons-align-right', 'bad_input', [['type' => 'buttons', 'align' => 'right', 'buttons' => [['text' => 'a', 'url' => '/a']]]]),
            self::c('button-unknown-key', 'bad_input', [$btn('/a', ['target' => '_blank'])]),
            self::c('button-missing-url', 'bad_input', [['type' => 'buttons', 'buttons' => [['text' => 'a']]]]),
            self::c('button-style-ghost', 'bad_input', [$btn('/a', ['style' => 'ghost'])]),
            self::c('button-not-object', 'bad_input', [['type' => 'buttons', 'buttons' => ['/a']]]),
            self::c('separator-extra-key', 'bad_input', [['type' => 'separator', 'text' => 'x']]),
            self::c('spacer-missing-size', 'bad_input', [['type' => 'spacer']]),
            self::c('spacer-size-huge', 'bad_input', [['type' => 'spacer', 'size' => 'huge']]),
            self::c('table-cell-number', 'bad_input', [$tbl([['a', 2]])]),
            self::c('table-row-not-list', 'bad_input', [$tbl(['a'])]),
            self::c('quote-paragraphs-not-list', 'bad_input', [['type' => 'quote', 'paragraphs' => 'x']]),
            self::c('group-children-not-list', 'bad_input', [['type' => 'group', 'children' => $p()]]),
            self::c('columns-widths-string', 'bad_input', [$cols([$col($p()), $col($p())], ['50%', '50%'])]),
            self::raw('columns-widths-float', 'bad_input', '{"post_type":"page","editor":"wordpress_blocks","title":"T","outline":[{"type":"columns","widths":[50.0,50],"columns":[{"children":[{"type":"separator"}]},{"children":[{"type":"separator"}]}]}]}'),
            self::c('column-unknown-key', 'bad_input', [$cols([['children' => [$p()], 'width' => 50], $col($p())])]),
            self::c('column-not-object', 'bad_input', [$cols([[$p()], $col($p())])]),
            self::c('unknown-node-html', 'create_content_invalid', [['type' => 'html', 'text' => 'x']]),
            self::c('unknown-node-cover', 'create_content_invalid', [['type' => 'cover', 'children' => [$p()]]]),

            // Placement, counts, widths and table shape.
            self::c('group-inside-group', 'layout_invalid', [['type' => 'group', 'children' => [['type' => 'group', 'children' => [$p()]]]]]),
            self::c('group-inside-column', 'layout_invalid', [$cols([$col(['type' => 'group', 'children' => [$p()]]), $col($p())])]),
            self::c('columns-inside-column', 'layout_invalid', [$cols([$col($cols([$col($p()), $col($p())])), $col($p())])]),
            self::c('group-no-children', 'layout_invalid', [['type' => 'group', 'children' => []]]),
            self::c('group-51-children', 'layout_invalid', [['type' => 'group', 'children' => $many(51, static fn () => ['type' => 'separator'])]]),
            self::c('column-no-children', 'layout_invalid', [$cols([['children' => []], $col($p())])]),
            self::c('columns-one', 'layout_invalid', [$cols([$col($p())])]),
            self::c('columns-five', 'layout_invalid', [$cols([$col($p()), $col($p()), $col($p()), $col($p()), $col($p())])]),
            self::c('widths-33-33-33', 'layout_invalid', [$cols([$col($p()), $col($p()), $col($p())], [33, 33, 33])]),
            self::c('widths-count-mismatch', 'layout_invalid', [$cols([$col($p()), $col($p()), $col($p())], [50, 50])]),
            self::c('widths-5-95', 'layout_invalid', [$cols([$col($p()), $col($p())], [5, 95])]),
            self::c('buttons-none', 'layout_invalid', [['type' => 'buttons', 'buttons' => []]]),
            self::c('buttons-four', 'layout_invalid', [['type' => 'buttons', 'buttons' => $many(4, static fn () => ['text' => 'a', 'url' => '/a'])]]),
            self::c('buttons-13', 'layout_invalid', array_merge(
                $many(4, static fn () => ['type' => 'buttons', 'buttons' => [['text' => 'a', 'url' => '/a'], ['text' => 'b', 'url' => '/b'], ['text' => 'c', 'url' => '/c']]]),
                [$btn('/d')]
            )),
            self::c('quote-no-paragraphs', 'layout_invalid', [['type' => 'quote', 'paragraphs' => []]]),
            self::c('quote-11-paragraphs', 'layout_invalid', [['type' => 'quote', 'paragraphs' => $many(11, static fn () => 'p')]]),
            self::c('table-no-rows', 'layout_invalid', [$tbl([])]),
            self::c('table-51-rows', 'layout_invalid', [$tbl($many(51, static fn () => ['a']))]),
            self::c('table-7-columns', 'layout_invalid', [$tbl([['a', 'b', 'c', 'd', 'e', 'f', 'g']])]),
            self::c('table-ragged-rows', 'layout_invalid', [$tbl([['a', 'b'], ['c']])]),
            self::c('table-header-width-mismatch', 'layout_invalid', [$tbl([['a', 'b']], ['h'])]),
            self::c('table-empty-header', 'layout_invalid', [$tbl([['a']], [])]),
            self::c('table-empty-row', 'layout_invalid', [$tbl([[]])]),
            self::c('tables-11', 'layout_invalid', $many(11, static fn () => ['type' => 'table', 'rows' => [['a']]])),
            self::c('images-21', 'layout_invalid', $many(21, static fn (int $i) => ['type' => 'image', 'attachment_id' => $i, 'alt' => ''])),
            self::c('nodes-401', 'layout_invalid', $nodes401),

            // Links.
            self::c('link-http', 'link_invalid', [$btn('http://example.com/')]),
            self::c('link-javascript', 'link_invalid', [$btn('javascript:alert(1)')]),
            self::c('link-javascript-mixed-case', 'link_invalid', [$btn('JaVaScRiPt:alert(1)')]),
            self::c('link-https-uppercase', 'link_invalid', [$btn('HTTPS://example.com/')]),
            self::c('link-protocol-relative', 'link_invalid', [$btn('//evil.example/x')]),
            self::c('link-backslash-host', 'link_invalid', [$btn('/\\evil.example/x')]),
            self::c('link-userinfo', 'link_invalid', [$btn('https://bank.example@evil.example/')]),
            self::c('link-userinfo-password', 'link_invalid', [$btn('https://user:pass@example.com/')]),
            self::c('link-data', 'link_invalid', [$btn('data:text/html,x')]),
            self::c('link-mailto', 'link_invalid', [$btn('mailto:a@example.com')]),
            self::c('link-tel', 'link_invalid', [$btn('tel:+15551234')]),
            self::c('link-host-without-dot', 'link_invalid', [$btn('https://localhost/')]),
            self::c('link-host-trailing-dot', 'link_invalid', [$btn('https://example.com./')]),
            self::c('link-empty-host', 'link_invalid', [$btn('https:///x')]),
            self::c('link-port-zero', 'link_invalid', [$btn('https://example.com:0/')]),
            self::c('link-port-65536', 'link_invalid', [$btn('https://example.com:65536/')]),
            self::c('link-bad-percent', 'link_invalid', [$btn('https://example.com/%zz')]),
            self::c('link-space', 'link_invalid', [$btn('https://example.com/a b')]),
            self::c('link-double-quote', 'link_invalid', [$btn('https://example.com/a"b')]),
            self::c('link-apostrophe', 'link_invalid', [$btn('https://example.com/a\'b')]),
            self::c('link-angle-bracket', 'link_invalid', [$btn('https://example.com/<x>')]),
            self::c('link-square-bracket', 'link_invalid', [$btn('https://example.com/[1]')]),
            self::c('link-non-ascii', 'link_invalid', [$btn('https://exämple.com/')]),
            self::c('link-empty', 'link_invalid', [$btn('')]),
            self::c('link-too-long', 'link_invalid', [$btn('https://example.com/' . str_repeat('a', 2029))]),
            self::c('link-relative-without-slash', 'link_invalid', [$btn('contact')]),
            // A character reference: the block editor writes its ampersand bare.
            self::c('link-reference-amp', 'link_invalid', [$btn('https://example.com/?a=1&amp;b=2')]),
            self::c('link-reference-named', 'link_invalid', [$btn('/shop?x=1&copy;=2')]),
            self::c('link-reference-unknown-name', 'link_invalid', [$btn('https://example.com/?a=1&b;c')]),
            self::c('link-reference-decimal', 'link_invalid', [$btn('/&#47;evil.example/login')]),
            self::c('link-reference-hex', 'link_invalid', [$btn('https://example.com/a&#x2F;b')]),
            self::c('link-reference-hex-upper', 'link_invalid', [$btn('https://example.com/a&#X2f;b')]),
            // A colon in a site path, in any spelling: WordPress drops the text before it.
            self::c('link-path-colon', 'link_invalid', [$btn('/shop/sale:summer')]),
            self::c('link-path-colon-in-query', 'link_invalid', [$btn('/shop?time=10:30')]),
            self::c('link-path-colon-in-fragment', 'link_invalid', [$btn('/shop#a:b')]),
            self::c('link-path-colon-after-slash-query', 'link_invalid', [$btn('/shop/?time=10:30')]),
            self::c('link-path-numeric-colon-no-semicolon', 'link_invalid', [$btn('/a&#58b')]),
            self::c('link-path-hex-colon-no-semicolon', 'link_invalid', [$btn('/a&#x3ag')]),
            self::c('link-path-ampersand-hash', 'link_invalid', [$btn('/a?x=1&#top')]),

            // The classic editor holds no layout.
            self::c('classic-columns', 'layout_needs_block_editor', [$cols([$col($p()), $col($p())])], 'wordpress_classic'),
            self::c('classic-group', 'layout_needs_block_editor', [['type' => 'group', 'children' => [$p()]]], 'wordpress_classic'),
            self::c('classic-buttons', 'layout_needs_block_editor', [$btn('/a')], 'wordpress_classic'),
            self::c('classic-spacer', 'layout_needs_block_editor', [['type' => 'spacer', 'size' => 'small']], 'wordpress_classic'),
            self::c('classic-image-caption', 'layout_needs_block_editor', [$img(1, ['caption' => 'c'])], 'wordpress_classic'),

            // Text rules: the agent's alone.
            self::text('alt-bracketed-number', [['type' => 'image', 'attachment_id' => 1, 'alt' => 'Figure [1]']]),
            self::text('alt-markup', [['type' => 'image', 'attachment_id' => 1, 'alt' => '<b>x</b>']]),
            self::text('alt-whitespace-only', [['type' => 'image', 'attachment_id' => 1, 'alt' => ' ']]),
            self::text('alt-301-chars', [['type' => 'image', 'attachment_id' => 1, 'alt' => str_repeat('a', 301)]]),
            self::text('alt-reference-amp', [['type' => 'image', 'attachment_id' => 1, 'alt' => 'Already &amp; encoded']]),
            self::text('alt-reference-named', [['type' => 'image', 'attachment_id' => 1, 'alt' => 'Logo &copy; 2026']]),
            self::text('alt-reference-nbsp', [['type' => 'image', 'attachment_id' => 1, 'alt' => 'a&nbsp;b']]),
            self::text('alt-reference-unknown-name', [['type' => 'image', 'attachment_id' => 1, 'alt' => 'AT&T; and more']]),
            self::text('alt-reference-decimal', [['type' => 'image', 'attachment_id' => 1, 'alt' => 'Alt &#39; text']]),
            self::text('alt-reference-hex', [['type' => 'image', 'attachment_id' => 1, 'alt' => 'Alt &#x27; text']]),
            self::text('alt-reference-hex-upper', [['type' => 'image', 'attachment_id' => 1, 'alt' => 'Alt &#X27; text']]),
            self::text('caption-empty', [$img(1, ['caption' => ''])]),
            self::text('caption-501-chars', [$img(1, ['caption' => str_repeat('a', 501)])]),
            self::text('button-text-empty', [['type' => 'buttons', 'buttons' => [['text' => '', 'url' => '/a']]]]),
            self::text('button-text-81-chars', [['type' => 'buttons', 'buttons' => [['text' => str_repeat('a', 81), 'url' => '/a']]]]),
            self::text('button-text-shortcode', [['type' => 'buttons', 'buttons' => [['text' => '[gallery]', 'url' => '/a']]]]),
            self::text('quote-template-syntax', [['type' => 'quote', 'paragraphs' => ['{{ x }}']]]),
            self::text('citation-201-chars', [['type' => 'quote', 'paragraphs' => ['q'], 'citation' => str_repeat('a', 201)]]),
            self::text('cell-bracket', [$tbl([['[x]']])]),
            self::text('cell-501-chars', [$tbl([[str_repeat('a', 501)]])]),
            self::text('cell-newline', [$tbl([["a\nb"]])]),
            self::text('column-paragraph-markup', [$cols([$col($p('<script>')), $col($p())])]),
        ];
    }

    // -------------------------------------------------------------------------
    // Behaviour
    // -------------------------------------------------------------------------

    public function test_v1_outlines_render_byte_identical_to_the_previous_release(): void
    {
        $outline = [
            ['type' => 'heading', 'level' => 2, 'text' => 'Our hours & prices'],
            ['type' => 'heading', 'level' => 3, 'text' => 'H3 [1]'],
            ['type' => 'heading', 'level' => 4, 'text' => 'H4'],
            ['type' => 'paragraph', 'text' => 'Open daily. Café "Ünïcode" it\'s fine.'],
            ['type' => 'list', 'ordered' => true, 'items' => ['One', 'Two']],
            ['type' => 'list', 'ordered' => false, 'items' => ['Q&A']],
        ];
        // The bytes agent 0.61.158 wrote for this outline.
        $blocks = "<!-- wp:heading -->\n<h2 class=\"wp-block-heading\">Our hours &amp; prices</h2>\n<!-- /wp:heading -->\n\n"
            . "<!-- wp:heading {\"level\":3} -->\n<h3 class=\"wp-block-heading\">H3 &#091;1&#093;</h3>\n<!-- /wp:heading -->\n\n"
            . "<!-- wp:heading {\"level\":4} -->\n<h4 class=\"wp-block-heading\">H4</h4>\n<!-- /wp:heading -->\n\n"
            . "<!-- wp:paragraph -->\n<p>Open daily. Café \"Ünïcode\" it's fine.</p>\n<!-- /wp:paragraph -->\n\n"
            . "<!-- wp:list {\"ordered\":true} -->\n<ol class=\"wp-block-list\"><!-- wp:list-item -->\n<li>One</li>\n<!-- /wp:list-item --><!-- wp:list-item -->\n<li>Two</li>\n<!-- /wp:list-item --></ol>\n<!-- /wp:list -->\n\n"
            . "<!-- wp:list -->\n<ul class=\"wp-block-list\"><!-- wp:list-item -->\n<li>Q&amp;A</li>\n<!-- /wp:list-item --></ul>\n<!-- /wp:list -->";
        $classic = "<h2>Our hours &amp; prices</h2>\n\n<h3>H3 &#091;1&#093;</h3>\n\n<h4>H4</h4>\n\n"
            . "<p>Open daily. Café \"Ünïcode\" it's fine.</p>\n\n<ol>\n<li>One</li>\n<li>Two</li>\n</ol>\n\n<ul>\n<li>Q&amp;A</li>\n</ul>";

        $b = self::validate($outline);
        $c = self::validate($outline, 'wordpress_classic');
        $this->assertSame($blocks, PageCreateBuilder::render($b['spec']));
        $this->assertSame($classic, PageCreateBuilder::render($c['spec']));
        $this->assertSame([], PageCreateBuilder::mediaIds($b['spec']));
        $this->assertSame(hash('sha256', (string) json_encode(['new_post', 'page'])), PageCreateBuilder::baseFingerprint('page'));
    }

    public function test_alt_text_is_escaped_to_the_forms_every_core_keeps(): void
    {
        $r    = self::validate([['type' => 'image', 'attachment_id' => 5, 'alt' => 'Bob\'s "dog" & cat &amp']]);
        $html = PageCreateBuilder::render($r['spec'], [5 => ['url' => 'https://example.com/a.jpg?x=1&y=2']]);

        $this->assertStringContainsString('alt="Bob&apos;s &quot;dog&quot; &amp; cat &amp;amp"', $html);
        $this->assertStringContainsString('src="https://example.com/a.jpg?x=1&amp;y=2"', $html);
        $this->assertStringContainsString('class="wp-image-5" />', $html, 'void elements end in a space and a slash');
        $this->assertStringNotContainsString('"/>', $html);
        $this->assertStringNotContainsString("'", substr($html, (int) strpos($html, '<img')), 'no raw apostrophe in an attribute');
    }

    public function test_retokenise_accepts_every_template_and_refuses_anything_else(): void
    {
        foreach (json_decode(self::layoutFixture(), true)['cases'] as $case) {
            $this->assertNull(PageCreateBuilder::retokenise($case['preview']['content']), $case['name']);
        }
        $img = '<img src="https://example.com/a.jpg" alt="" class="wp-image-1" />';
        $this->assertNull(PageCreateBuilder::retokenise($img));
        $bad = [
            'unknown attribute' => '<img src="https://example.com/a.jpg" alt="" class="wp-image-1" onerror="alert(1)" />',
            'attribute order'   => '<img alt="" src="https://example.com/a.jpg" class="wp-image-1" />',
            'javascript src'    => '<img src="javascript:alert(1)" alt="" class="wp-image-1" />',
            'protocol-relative' => '<a class="wp-block-button__link wp-element-button" href="//evil.example/">x</a>',
            'style injection'   => '<div class="wp-block-column" style="flex-basis:50%;background:url(x)">',
            'spacer height'     => '<div style="height:47px" aria-hidden="true" class="wp-block-spacer">',
            'class injection'   => '<div class="wp-block-group evil">',
            'quote in alt'      => '<img src="https://example.com/a.jpg" alt="a"b" class="wp-image-1" />',
            'comment json'      => '<!-- wp:image {"id":1,"sizeSlug":"large","linkDestination":"none","url":"x"} -->',
            'unknown block'     => '<!-- wp:html -->',
            'width 100%'        => '<!-- wp:column {"width":"100%"} -->',
            'script tag'        => '<script>',
            'bracket in text'   => '<p>[gallery]</p>',
        ];
        foreach ($bad as $why => $html) {
            $this->assertNotNull(PageCreateBuilder::retokenise($html), $why);
        }
    }

    public function test_the_classic_editor_never_flattens_layout(): void
    {
        $spec = [
            'post_type' => 'page', 'editor' => 'wordpress_classic', 'title' => 'T',
            'outline'   => [['type' => 'group', 'children' => [['type' => 'paragraph', 'text' => 'x']]]],
        ];
        $this->expectException(\UnexpectedValueException::class);
        PageCreateBuilder::render($spec);
    }

    public function test_an_image_without_a_resolved_address_is_never_rendered(): void
    {
        $r = self::validate([['type' => 'image', 'attachment_id' => 5, 'alt' => '']]);
        $this->expectException(\UnexpectedValueException::class);
        PageCreateBuilder::render($r['spec'], [5 => ['url' => 'javascript:alert(1)']]);
    }

    public function test_media_ids_are_distinct_in_document_order(): void
    {
        $r = self::validate([
            ['type' => 'image', 'attachment_id' => 9, 'alt' => ''],
            ['type' => 'group', 'children' => [
                ['type' => 'columns', 'columns' => [
                    ['children' => [['type' => 'image', 'attachment_id' => 3, 'alt' => '']]],
                    ['children' => [['type' => 'image', 'attachment_id' => 9, 'alt' => '']]],
                ]],
            ]],
            ['type' => 'image', 'attachment_id' => 1, 'alt' => ''],
        ]);
        $this->assertSame([9, 3, 1], PageCreateBuilder::mediaIds($r['spec']));
    }

    public function test_links_and_alt_count_toward_the_total(): void
    {
        $long = str_repeat('a', 4990);
        $outline = [];
        for ($i = 0; $i < 11; $i++) {
            $outline[] = ['type' => 'paragraph', 'text' => $long];
        }
        // 11 x 4990 + the title = 54891; 4 buttons of 2000-byte links push it past 60000.
        $url = 'https://example.com/' . str_repeat('b', 1980);
        $outline[] = ['type' => 'buttons', 'buttons' => [['text' => 'a', 'url' => $url], ['text' => 'b', 'url' => $url], ['text' => 'c', 'url' => $url]]];
        $this->assertSame('create_content_invalid', self::validate($outline)['code'] ?? 'ok');
        array_pop($outline);
        $this->assertArrayHasKey('spec', self::validate($outline));
    }

    public function test_limits_are_the_published_limits(): void
    {
        $this->assertSame(
            '{"max_top_level_nodes":200,"max_nodes":400,"max_columns":4,"max_children":50,"max_images":20,"max_buttons":12,"max_tables":10,"max_table_rows":50,"max_table_columns":6,"max_title_chars":200,"max_text_chars":5000,"max_total_chars":60000,"max_input_bytes":65536}',
            json_encode(PageCreateBuilder::limits())
        );
    }

    // -------------------------------------------------------------------------
    // Helpers for the behaviour tests
    // -------------------------------------------------------------------------

    /**
     * @param list<mixed> $outline
     * @return array<string,mixed>
     */
    private static function validate(array $outline, string $editor = 'wordpress_blocks'): array
    {
        $input = json_decode(self::page($outline, $editor), false);
        self::assertIsObject($input);

        return PageCreateBuilder::validate($input);
    }
}
